### ISSUE TITLE
Suggest a wallet

### ISSUE THREAD

**Issue by KrystalWallet** [ethereum/ethereum-org-website#10076]
### Wallet name

Krystal Wallet

### Wallet description

[Krystal](https://krystal.app) is the simplest web3 wallet for everyone. On a single application, access cutting-edge portfolio management & market insights tools, swap & bridge tokens, earn passive income and participate in token sales via its IDO launchpad, KrystalGO. Additionally, users earn points and rewards from in-app activities as part of its loyalty program.

### Wallet logo

![Krystal_icon_512](https://user-images.githubusercontent.com/131853278/234514467-9521aab7-d539-43e0-bbd9-860a32e4ce3f.png)

### Background color for brand logo

#000000

### URL to the project

https://krystal.app/

### When did the wallet go live to users?

15 April 2021

### Does the wallet have an active development team?

Yes

### Is the wallet globally accessible?

Yes, beside these countries Cuba, Palestine, Russia, Syria, Yemen, Iran, Zimbabwe, Democratic People's Republic of Korea (DPRK), United States of America, People’s Republic of China, Hong Kong SAR, Macau SAR, Singapore, Myanmar 

### What social links are there for the project?

https://twitter.com/KrystalWallet

### Does the wallet have a mobile app? If yes, which operating systems are supported (iOS, Android)?

Yes, both Android and iOS
 https://krystal.app.link

### Who holds the private keys?

Users

### Does the wallet support connecting to a hardware wallet?

No

### Does the wallet support WalletConnect?

Yes

### Does the wallet support viewing and interacting with NFTs?

Yes

### Does the wallet support connecting to Ethereum applications?

https://docs.krystal.app/features/dapp-browser

### Does the wallet support staking directly?

https://docs.krystal.app/features/earn

### Does the wallet support swaps directly?

https://docs.krystal.app/features/swap

### Does the wallet support multi-chain networks?

https://docs.krystal.app/features/multichain-features

### Does the wallet support Ethereum layer 2 networks?

Yes

### Does the wallet allow the user to customize gas fees?

Yes

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by KrystalWallet** [comment]
@nhsz @chuyeow @matthieu @shazow @jpanachida Please help us with this request

**Comment by cryptocoinpurse** [comment]
up

**Comment by KrystalWallet** [comment]
Yes, since March 2023 we have rebranded and position us as a wallet, all of our media channels have been changed to Krystal Wallet. We also fully focusing to build as a wallet, so you can see our app is similar to other wallets like 1inch, Metamask, Bitkeep etc...

**Comment by KrystalWallet** [comment]
@corwintines friendly reminder

**Comment by KrystalWallet** [comment]
up

**Comment by corwintines** [comment]
@KrystalWallet a few things. I don't think just rebranding addresses the issues that had come up with your app in the past https://github.com/ethereum/ethereum-org-website/issues/6999

There is a lot of no response in this issue, which leads me to believe this wasn't even fully filled out. I'm not willing to go through and find the answers to all the no responses that are left here. There are a lot of wallets that we have rejected due to not sharing security audits with us, as well as their source code, and I'm noticing the same issue here. Given hacks going on in wallets, this is something I need to see before I'm willing to consider a wallet.

The interface of the app is still quite confusing. The main call to action is a portfolio manager, not a wallet (regardless of branding). With the goal of this page being easily onboarding users to a wallet, this really doesn't fit that goal.

I am rejecting this with the above reasoning. Will give another core member a chance to review before closing.

**Comment by KrystalWallet** [comment]
Thanks you guys for your feedback, i will elaborate it to the team.
