### ISSUE TITLE
dart and flutter language and tooling for making blockchain app

### ISSUE THREAD

**Issue by davidAg9** [ethereum/ethereum-org-website#1022]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Comment by samajammin** [comment]
@davidAg9 thanks for the issue! Do you adding more information on what you're looking for? Are you suggesting we create Dark/Flutter pages similar to the existing programming language pages, e.g. https://ethereum.org/python/ ?

Filling out the prompts in the issue template will always help ensure your issue is addressed.

**Comment by davidAg9** [comment]
there aren't enough packages to develop a flutter app powered by blockchain for.
so far there is only one package (solid ) in the flutters package library

**Comment by samajammin** [comment]
Have you checked out https://github.com/simolus3/web3dart ?

**Comment by samajammin** [comment]
@davidAg9 feel free to re-open this issue if you think a page should be created to list Dart/Flutter resource pages. It sounds like you're looking to see more software packages/libraries created for Dart/Flutter developers though, which is out of scope of this website.
