### ISSUE TITLE
Security threats to the Ethereum ecosystem and ways of mitigation.

### ISSUE THREAD

**Issue by Asuzor11** [ethereum/ethereum-org-website#10445]
### Is your feature request related to a problem? Please describe.

Most web3 technologies are documented in their whitePaper or litepaper. Some or the source codes are open source and iterable on their repository- which leaves us with the all important question, what are the measures in place to prevent malware manufacturing or shooting in the ecosystem?
Most viruses are manufactured by studying how their anti viruses work and then building something similar with a reverse technology

### Describe the solution you'd like

Security checks should be ran on people that run nodes and edit them.
Consensual webcam monitoring and screen recording should they be subjected to before they are granted editors access to the ethereum repository 

Due and thorough security diligence checks should be carried out on potential investors so as to ensure they are not hacker sponsors, because most investors have a great influence on new protocol roll outs and how they can work. They can act as double informats for malware manufacturers.
Their communication should be obligatorily monitored and they should sign a code of conduct not to discuss any protocol upgrade outside of the ecosystem iteration committee.

### Describe alternatives you've considered

Periodical security threat hackathons should be implemented for freelance hackers to test for security leakages in the Ethereum ecosystem. Subsequent improvements should be made after the security tests, and the troubleshooters should be rewarded with Eth.
Cybersecurity hackathons should be organized to look at possible security leakages on the network and give recommendations for tighter security protocols.
Employ the best performers to give better security to the network.

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
Hey @Asuzor11, appreciate your thoughts.

Just clarifying to start, this repo is dedicated to the maintenance of a website (https://ethereum.org) acting as an open/collaborative/free educational resource for all things Ethereum. This is different than the Ethereum protocol, or any client implementation. Issues posted here should be related to the ethereum.org website only, and not issues related to the protocol, Ethereum R&D, Ethereum governance, or otherwise.

The things you're suggesting fall far outside of the scope of this website so I'm going to close this out, but I'd encourage you to voice your thoughts/concerns/suggestions in a more appropriate forum! Check out "How to get involved" on the ethereum.org governance page to find some helpful links: https://ethereum.org/en/governance/#get-involved

Thanks again!
