### ISSUE TITLE
Secondary buttons styling does not correctly reflect design system

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#10739]
### Describe the bug

Across the website, we are using the primary outline variant of the button instead of the secondary variant of the button.

E.g., in the design system, we use a secondary button (black outline) for the secondary button.

<img width="1269" alt="Screenshot 2023-07-20 at 10 00 54" src="https://github.com/ethereum/ethereum-org-website/assets/62268199/c0ab6728-232c-4b52-a826-1d8aee743f05">

Here is the difference:

<img width="345" alt="Screenshot 2023-07-20 at 09 57 44 1" src="https://github.com/ethereum/ethereum-org-website/assets/62268199/aab0bc09-3f24-482a-bb0b-9a84f23ff472">

However, on production, we use the primary 'outline' variant ([see Layer 2 page](https://ethereum.org/en/layer-2/)) also everywhere.

<img width="1435" alt="Screenshot 2023-07-20 at 10 02 49" src="https://github.com/ethereum/ethereum-org-website/assets/62268199/569ce763-486f-4553-b631-f2377a0ed2e8">

We accidentally do the same on the homepage:

<img width="1494" alt="Screenshot 2023-07-20 at 10 08 33" src="https://github.com/ethereum/ethereum-org-website/assets/62268199/d72e0fcd-6341-4107-90f7-e537c3bd67ac">

And on the docs:

<img width="1080" alt="Screenshot 2023-07-20 at 10 08 40" src="https://github.com/ethereum/ethereum-org-website/assets/62268199/bce9dae3-f1cf-49f9-bfcc-ca14cab24d6e">

### To reproduce

1. Go to 'https://ethereum.org/en/layer-2/'
1. See error

### Expected behavior

I'm currently unsure about the correct button designs. It appears that around 90% of our buttons should feature black outlines (secondary outline).

To avoid inconsistencies, I suggest we standardize all outline button variants to secondary outline buttons. We can revise this as needed once we establish clearer design rules or exceptions.

**Comment by MwitahJob** [comment]
Could you assign me the issue

**Comment by TylerAPfledderer** [comment]
Hey @minimalsm! I didn't get that far in implementation, waiting to determine which was the appropriate option.

I did add an `isSecondary` boolean prop to be used in both the `Button` and `ButtonLink` components. Can default it to `true` if `variant="outline"`, if that is the expectation.

**Comment by TylerAPfledderer** [comment]
@nloureiro tagging for your awareness of this open issue that is now stale. Any thoughts at this time? This looks to still be a relevant question.

**Comment by nloureiro** [comment]
> 

Hello. Thank you for calling it out. Let me see if I can help.

The base concept: Each section should only have one Primary action > in this case, a button with a primary color

So, every time we have two buttons side by side, only one should be primary, and the other one should be secondary
![Screen Shot 2023-09-05 10 29 20 AM](https://github.com/ethereum/ethereum-org-website/assets/1120748/5f946791-f2b9-4efb-b33c-1a2a9ffe3fb5)


The goal is to make clear what is the main CTA to the user, we want to make the experience clear on what isomer relevant but with some side(secondary) options.

@TylerAPfledderer does it make sense to you? We probably need to add this as a rule on Figma. 😅

**Comment by TylerAPfledderer** [comment]
@nloureiro all good by me! 

From the coding side, might have to simply apply `isSecondary` to the outlined button on every instance of this pairing. I can't think of a way to conditionally apply it.

Or, we are creating a molecule-level button group component for the added re-usability since this choice of styling needs to be consistent.

@pettinarip based on the inquiry you gave me regarding what I did for `ButtonTwoLines`, maybe a rehashing here on what should be considered DRY and too DRY?? 😅 I understand the grey area on creating overhead for the sake of something that seems minor. That's me trying to think ahead. 🤪

**Comment by nloureiro** [comment]
> 
great! thank you.
My wild guess would be to get this on molecule-level group logic. I tend to like the core components as free of extra logic as possible and leave it to the parent.

**Comment by pettinarip** [comment]
@TylerAPfledderer haha :P

Not a strong opinion about creating a new component for this but....I would be opposed. Since I believe this is a styling rule and should be defined in the Design System, and someone trying to create a new page should follow those design rules. Also, if we start creating components for every style rule that we have, we would end up having a bunch of components that would make it hard to understand for a newcomer.

However, I understand the re-usability argument. Either decision is fine for me.

**Comment by TylerAPfledderer** [comment]
@pettinarip @nloureiro Can for now do a sweep of the project and just mark buttons with `isSecondary` as needed.

In regards to any re-usability considerations, maybe there is a chance as we continue hashing out the DS that this might take care of itself, where a new parent component for the given sections would supply the needed alterations?

**Comment by pettinarip** [comment]
@TylerAPfledderer @nloureiro I would lean towards that, yes. I agree as well with your second thought 👍🏼

**Comment by TylerAPfledderer** [comment]
@pettinarip cool. I can take assignment on this then, please. 😁
