### ISSUE TITLE
Refactor Quiz Hub logic

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#10887]
### Description

The current [Quiz Hub logic is crashing](https://github.com/ethereum/ethereum-org-website/issues/10828) when we add new quizzes to it.

### Refactor goals

- Pull all logic from quiz component higher up the component order as possible to help create component re-usability (preferably to the quiz hub page).
- Reorganize the logic and condense / refactor where necessary
- The localStorage issue should be solved after the above two objectives are met, and not just creating a patch.
- Consider the use of [useLocalStorage from useHooks-ts](https://usehooks-ts.com/react-hook/use-local-storage) as a more robust version of the hook already in the project.

**Comment by TylerAPfledderer** [comment]
@pettinarip commenting for assignment.

Public note: based on private discussion, this issue is expected to be part of a larger refactor of the logic for the quizzes.

Primary goals:
- Pull all logic from quiz component higher up the component order as possible (preferably to the quiz hub page).
- Reorganize the logic and condense / refactor where necessary
- The localStorage issue should be solved after the above two objectives are met, and not just creating a patch.
- Consider the use of [useLocalStorage from useHooks-ts](https://usehooks-ts.com/react-hook/use-local-storage) as a more robust version of the hook already in the project.

Pablo: would you prefer a new GH issue be created to address the complete refactor, and note this localStorage issue as a dependency?

**Comment by pettinarip** [comment]
@TylerAPfledderer great!

I've updated the title & description to match what you wrote 💯

**Comment by TylerAPfledderer** [comment]
My assignment is retained here, but addressing this issue over in the Next fork repo, per private discussion.

**Comment by TylerAPfledderer** [comment]
@pettinarip I think this should be considered closed

**Comment by pettinarip** [comment]
@TylerAPfledderer thanks, yes, this refactor is not going to be done for now. For ref. this was the progress done #11933.
