### ISSUE TITLE
Markdown links that reference `/` in design principles throw a Github 404

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#1103]
**Describe the bug**
When trying to navigate via the links that refer to the root structure of ethereum.org rather than a full hyperlink in the design principles file, I'm sent to GitHub 404s instead of intended pages.

For example:
`[Ethereum.org](http://ethereum.org)` **works**
`[across our site](/)` **doesn't work**

**To Reproduce**
1. Go to https://github.com/ethereum/ethereum-org-website/blob/dev/design-principles.md
2. Scroll to the bottom
3. Follow "Across our site" or "style guide"
4. See 404 page

Note: this affects most links on the page but this is the clearest way of demoing the bug.

**Expected behavior**
The links should take you to pages on the ethereum.org site and not github 404s

**Screenshots**
![image](https://user-images.githubusercontent.com/40891631/84125503-8c794300-aa34-11ea-9335-6934f7d4f149.png)
![image](https://user-images.githubusercontent.com/40891631/84125523-91d68d80-aa34-11ea-82c5-e9d914bda9a5.png)

**Desktop (please complete the following information):**
 - iOS
 - Chrome version 83.0.4103.61
 - Brave version 1.8.96 Chromium: 81.0.4044.138

**Comment by ryancreatescopy** [comment]
We could replace them with hyperlinks: `https://ethereum.org` for example but this might not be the best option if we can work out a way to reference specific files in the structure like `/` or `/style-guide`

**Comment by samajammin** [comment]
Nice catch. I think I know why this is broken - when I originally added the [About page](https://ethereum.org/about/), I added the Purpose & Design Principles docs as web pages as well (at ethereum.org/about/purpose/ & ethereum.org/about/principles, respectively).

Here's the PR: https://github.com/ethereum/ethereum-org-website/pull/918

We decided to take them down since they weren't fully fleshed out / intended as pages on our website but I'd like to re-add them. What do you think @ryancreatescopy @jjmstark? Perhaps this could be an initiative next sprint: revamping the project README, the purpose & design principles pages.
