### ISSUE TITLE
Roadmap menu needs strings set up for translation

### ISSUE THREAD

**Issue by MrJithil** [ethereum/ethereum-org-website#11689]
### Describe the bug

Roadmap https://ethereum.org/en/roadmap/ is only showing english texts in Roadmap Options dropdown

### To reproduce

1. Go to https://ethereum.org/es/roadmap/
2. Click on Roadmap options
3. Observe the options are in English

### Expected behavior

Roadmap options should be in the user selected language

### Screenshots

![Uploading Screenshot 2023-11-19 at 1.15.20 am.png…]()

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by MrJithil** [comment]
I need help to add a translate  key in all languages.

**Comment by wackerow** [comment]
@MrJithil These strings are located in the `dropdownLinks` object inside `src/layouts/Roadmap.tsx`.

Instead of English strings here, what we need to pass is a _key_ that will be used to look up the correct phrase in our intl JSON files... These use the "common" namespace, so the strings should be inside `src/intl/en/common.json`. 

An example:

```ts
// File: src/layouts/Roadmap.tsx

text: "Roadmap home" as TranslationKey,
```

Inside `src/intl/en/common.json`, add an entry that looks kinda like this:

```json
  "nav-roadmap-home": "Roadmap home",
```

Then back inside `src/layouts/Roadmap.tsx` change the entry to:

```ts
text: "nav-roadmap-home",
```

These will of course only be in English to start, but when this is done we'll send these off for translation through Crowdin. Let us know if you have any issues!
