### ISSUE TITLE
Warrant canary

### ISSUE THREAD

**Issue by unipaul** [ethereum/ethereum-org-website#117]
Ethereum.org doesn't have a warrent canary in the footer anymore. The foundation page https://ethereum.foundation/ has one. Is that enough or should ethereum.org also have one?
If it's wanted I could create this pull request.

**Comment by jjmstark** [comment]
Because the purpose of a warrant canary is to communicate information on behalf of a particular organization (e.g. the Ethereum Foundation), it makes more sense for it to appear on the Ethereum Foundation website, rather than on ethereum.org.

I can also refer you to @ethjoe's comment in the corresponding Reddit thread ([link](https://old.reddit.com/r/ethereum/comments/bqc55w/the_warrant_canary/eo5ka79/)). Going to close this issue for now!
