### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by opixelum** [ethereum/ethereum-org-website#11918]
### Describe the bug

A link to the original whitepaper is broken.

### To reproduce

1. Go to https://ethereum.org/en/whitepaper;
2. Click on [Researchers and academics seeking a historical or canonical version of the whitepaper [from December 2014] should use this PDF.(opens in a new tab)](https://ethereum.org/en/content/whitepaper/whitepaper-pdf/Ethereum_Whitepaper_-_Buterin_2014.pdf).

### Expected behavior

It should open the whitepaper in PDF format.

### Screenshots

![image](https://github.com/ethereum/ethereum-org-website/assets/48217573/ecd6fa48-bec3-48a7-938c-ac279a0677de)

### Desktop (please complete the following information)

- OS: Ubuntu - Browser: Brave - Version 1.61.116

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by lucas-amberg** [comment]
One thing to note, if you access the whitepaper via /content/whitepaper/whitepaper-pdf/Ethereum_Whitepaper_-_Buterin_2014.pdf rather than /*/content/whitepaper/whitepaper-pdf/Ethereum_Whitepaper_-_Buterin_2014.pdf it will work, likely an issue with Next.js routing via the locale URLs, I've found this issue mentioned [here](https://github.com/vercel/next.js/issues/54765).

**Comment by NorutoSDK** [comment]
Hahaha bug report
