### ISSUE TITLE
"Edit page" link on TOC is broken

### ISSUE THREAD

**Issue by visvirial** [ethereum/ethereum-org-website#11994]
### Describe the bug

The "Edit page" button link on the top of the TOC is broken.

Currently, it will redirect to e.g.:
https://ethereum.org/github.com/ethereum/ethereum-org-website/tree/dev/public/content/developers/docs/index.md

But it should be:
https://github.com/ethereum/ethereum-org-website/tree/dev/public/content/developers/docs/index.md

instead.

It seems to be the link href is parsed as a relative path, but we should treat it as an absolute path.

### To reproduce

1. Go to somewhere in the "Developers => Docs" page
2. Click on the "Edit page" button

### Expected behavior

It should be redirected to Github, instead of ethereum.org.

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by NorutoSDK** [comment]
Hahaha you Know WHO ethereum

**Comment by tutizaraz** [comment]
It seems that this has already been fixed but not deployed to production

**Comment by HiroyukiNaito** [comment]
If it is not fixed, I would like to work on  the issue.

**Comment by wackerow** [comment]
A patch was put up for this, but it appears there is still a bug with it:

```ts
// Inside /src/lib/utils/editPath.ts, we return:

join(EDIT_CONTENT_URL, CONTENT_DIR, relativePath, "index.md")
```

`EDIT_CONTENT_URL` has `https://` at the beginning of it... we cannot pass this to `join()` because that function will collapse repeating slashes (`/`) down to only one, as it's forming a path.

We should use construct a URL with `new URL(path, base)` instead and return the `href` value from the resulting object, passing `join(CONTENT_DIR, relativePath, "index.md")` as the `path` argument, and `EDIT_CONTENT_URL` as the `base`... this will properly parse these into a URL.

ie. `(new URL(join(CONTENT_DIR, relativePath, "index.md"), EDIT_CONTENT_URL)).href`

@HiroyukiNaito Assigning you for this =)

**Comment by HiroyukiNaito** [comment]
@wackerow Thanks for the tips! I work on it.

**Comment by wackerow** [comment]
Hey @HiroyukiNaito! Thanks for offering to patch this... Just want to mention that this bug is somewhat important since it's breaking all the edit links in the docs. We were hoping to get this patched ASAP... 

Any chance you're able to make this patch in the next few hours? Otherwise I may put up a patch so we can hot-fix the deploy planned for later today. Sorry for the time crunch 🙏

**Comment by HiroyukiNaito** [comment]
@wackerow Sure, thanks for notifying that.

**Comment by visvirial** [comment]
@corwintines @HiroyukiNaito 
Thank you for the fix and the deployment.
I could confirm that the links are correct on the production.
