### ISSUE TITLE
Clean the `/public` dir

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#12023]
Move standalone images inside `/public/images` to clean the `/public` dir.

Previous try: https://github.com/ethereum/ethereum-org-fork/pull/265 cc @corwintines

**Comment by wackerow** [comment]
@corwintines Wondering if we should maybe break this into smaller units, so we don't end up with a 900 file diff again.

I would suggest that as a next step here—decide a way to break this up into a few smaller units, and then we could open up for anyone who'd like to contribute. 

---

```
public
  assets
    [images]
    [folders_of_images]
  fonts
  [images]
  [folders_of_images]
```

Also, @pettinarip any thoughts on renaming "assets"?

Instead of "adding" `/public/images/`, we rename `/public/assets/` to `/public/images/`, then add all the images and folder of other images from `/public/` into that folder as well. Fonts (`/public/fonts/`) are the only other type of asset I see other than images, which is already outside of the `/public/assets/` directory.

**Comment by corwintines** [comment]
@wackerow I actually made a PR for this today, was working on it yesterday 😓 

If you want me to close this out let me know, I know its exactly what you described wanting to avoid.

**Comment by wackerow** [comment]
Oh great... no big deal, if you have something I would just go ahead and post it. It'll be fine. Thanks!

**Comment by pettinarip** [comment]
Sounds good @wackerow. Yeah, open to "delete" the `/assets` folder as well. I think the main point here is to move the top level files and group them in a new folder to make it easier to read. Corwin's PR looks good.
