### ISSUE TITLE
Language resources ABC order

### ISSUE THREAD

**Issue by Satglow** [ethereum/ethereum-org-website#12098]
### Is your feature request related to a problem? Please describe.

Language resources – ABC order for the listed languages on the English page and on the translated pages would be great. Currently the English page is probably manually handled, and the new addition (Japanese) was put to the end instead of the right place. 
For the translation this stays in the same order as the English, but would be better in ABC as per the translation. This is more logical when you are looking for a given language, so you don't want to read all items.

https://ethereum.org/community/language-resources#community
https://ethereum.org/hu/community/language-resources#community

![Language resources - ordering](https://github.com/ethereum/ethereum-org-website/assets/151942349/9aafbeef-7e52-4428-8704-3bce8f48d7c2)

![Language resources - translated page ordering](https://github.com/ethereum/ethereum-org-website/assets/151942349/11871266-f350-4dc6-9f34-b64727025874)

### Describe the solution you'd like

List of languages in ABC order (all versions of this page).

### Describe alternatives you've considered

None

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by AkimBW** [comment]
The ABC order makes sense. If possible I can take this issue.

**Comment by corwintines** [comment]
Thanks @Satglow 

Opened up an issue to fix the ordering of the languages on the english page. Since translated resources are translated in markdown from this, I don't think we will easily be able to sort this on translated pages. But I agree, these should be in alphabetical order on the English page as a base.

**Comment by wackerow** [comment]
@AkimBW Thanks for offering! Are you still interested in this? Assigning you if you're available

**Comment by wackerow** [comment]
This makes me wonder if we could build (or search for) a remark/rehype plugin that alphabetizes headers between a particular custom tag. 

We're in the midst of building out custom glossary components because we struggled with alphabetizing the markdown. This issue highlights a similar problem, which basically surfaces anywhere we'd like to alphabetize items inside markdown, which end up not being correctly ABC-ordered when translated into other languages.
