### ISSUE TITLE
Update All Core Devs YouTube link

### ISSUE THREAD

**Issue by ykaravas** [ethereum/ethereum-org-website#12198]
"Watch or participate in the [Core Dev calls](https://www.youtube.com/playlist?list=PLaM7G4Llrb7zfMXCZVEXEABT8OSnd4-7w)" line on the https://ethereum.org/community/get-involved page needs to be updated (specifically the link).

The link above is misleading. Needs to be updated to some playlist here: https://www.youtube.com/@EthereumProtocol

Ethereum Foundation YouTube channel is no longer posting dev calls.

**Comment by ashiskumar-1999** [comment]
@corwintines @pettinarip Is there any other platform where everyone can attend the Coredev call?
If there are any, then I think we should update them on the given page.

**Comment by ykaravas** [comment]
Aside from the updated YouTube channel I mentioned in the issue above which needs to be used instead of the stale one in the existing link, I am not sure about others.

**Comment by reetbatra** [comment]
can i work on this issue please?

**Comment by wackerow** [comment]
@ykaravas Thanks for reporting! Yes, I see the existing link takes us to a playlist that hasn't been updated in six years. I think the replacement link you posted would work great.

@ashiskumar-1999 Not that I am aware of

@reetbatra Thanks for offering to help, assigning you!

**Comment by wackerow** [comment]
@all-contributors please add @ykaravas for bug report

**Comment by wackerow** [comment]
@reetbatra Couple things here... this link is not only on the `/community/get-involved/` page, but also the `/developers/docs/standards/` page. It is also on the non-English versions of these pages.

With your PR, could you please replace `https://www.youtube.com/playlist?list=PLaM7G4Llrb7zfMXCZVEXEABT8OSnd4-7w` with `https://www.youtube.com/@EthereumProtocol` throughout the entire repo? Let us know if you need a hand with this since it can be a little tricky if you're only using GitHub.

**Comment by reetbatra** [comment]
Thanks a lot for the update, I'll get started with this and ping you here in case of any doubts.

**Comment by reetbatra** [comment]
Raised a PR to fix this. I cloned the repo locally to search and replace all instances of the link.

https://github.com/ethereum/ethereum-org-website/pull/12525
