### ISSUE TITLE
Add a "back to top" button on pages

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#12194]
### Is your feature request related to a problem? Please describe.

Some pages on ethereum.org are very long, and could benefit from a "back to top" button to help reset the user

### Describe the solution you'd like

At the bottom of the page (or a button that floats at some point), we add a back to top button that takes the user to the top of the page. 

- [ ] Needs design first

### Describe alternatives you've considered

Not having this button at all, may not be necessary as all nav is still accessible from wherever you are in the content generally.

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by wackerow** [comment]
Hey folks! Sounds like we need design first, then the dev implementation... @cypherspeare you mentioned wanting to help with design... I can assign you here, and will also assign @nloureiro to help out internally. For design contributions, it can be helpful to [hop into our Discord](https://ethereum.org/discord) and go to the `💅｜ux-ui-design` channel to collaborate or get feedback. 

If you're helping with design it's probably easier to just let you do the dev implementation too as you expressed interest in. Would work with Nuno on design stuff first, but then feel free to put a PR up for this when that is complete. If you'd rather let @alex1092 jump in at that point to contribute just let us know here! Otherwise @alex1092, we'll try to get you another one... [Good First Issues](https://github.com/ethereum/ethereum-org-website/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) labels are always a decent place to start =)

**Comment by nloureiro** [comment]
Hey @cypherspeare 

Let's do it! I am happy to assist you on the design side.

My take on this would be to try to fit a button/link on the footer so that the same behavior can be achieved on all the pages.

What do you think? I'm open to other ideas. Feel free to use this issue to keep the conversation going.

Are you comfortable working on Figma? If not al good, just post here your design ideas, an we can follow from it

If you want to use Figma, [here](https://www.figma.com/file/cKWwsQVF762HM7IuSnH8xn/Footer-links-update?type=design&node-id=1%3A48&mode=design&t=enQ9bDbPJWvYWuF7-1) is the link to our latest changes on the footer and it as the design system in it. Use it or copy it if you think it's useful

Thank you! I am looking forward to seeing your ideas.

**Comment by alex1092** [comment]
I’m easy, thanks guys… happy for you to forward any issues you have my way On 22 Mar 2024, at 4:36 pm, Nuno Loureiro ***@***.***> wrote:﻿
Hey @cypherspeare
Let's do it! I am happy to assist you on the design side.
My take on this would be to try to fit a button/link on the footer so that the same behavior can be achieved on all the pages.
What do you think? I'm open to other ideas. Feel free to use this issue to keep the conversation going.
Are you comfortable working on Figma? If not al good, just post here your design ideas, an we can follow from it
If you want to use Figma, here is the link to our latest changes on the footer and it as the design system in it. Use it or copy it if you think it's useful
Thank you! I am looking forward to seeing your ideas.

**Comment by nloureiro** [comment]
@cypherspeare @alex1092 

My idea was to go with something like this, not sure what´s on the left and what´s on the right, but overall is adding a button on the footer.

any other ideas?

![Screen Shot 2024-04-01 04 48 18 PM](https://github.com/ethereum/ethereum-org-website/assets/1120748/ebff9360-3b84-4767-ac82-68619b10df6a)
![Screen Shot 2024-04-01 04 48 10 PM](https://github.com/ethereum/ethereum-org-website/assets/1120748/e1e43c33-1511-4ce2-8c29-161943578dba)

figma link: https://www.figma.com/file/cKWwsQVF762HM7IuSnH8xn/Footer-links-update?type=design&node-id=110%3A1413&mode=design&t=QlqfZecVjoZBd4fF-1

**Comment by alex1092** [comment]
Amazing work, I'm wondering if the return to top should be floating and not fixed to the footer though, this will allow users to return the top regardless of page position

**Comment by nloureiro** [comment]
> Amazing work, I'm wondering if the return to top should be floating and not fixed to the footer though, this will allow users to return the top regardless of page position

I've considered the floating, but we already have the feedback widget floating and think it's more important in terms of function than this one.

The footer would be a simpler way to make it accessible on all pages and consistent.

The placement of the button is still open, I did an early exploration of it but open to ideas.

**Comment by nloureiro** [comment]
@alex1092 hello :) any update on this issue?

**Comment by alex1092** [comment]
Is this work ready for dev?

**Comment by alex1092** [comment]
Awaiting Reviews 

https://github.com/ethereum/ethereum-org-website/pull/12906
