### ISSUE TITLE
Broken link in dev docs /nodes-and-clients/run-a-node

### ISSUE THREAD

**Issue by gndelia** [ethereum/ethereum-org-website#12412]
### Describe the bug

The [requirements](https://ethereum.org/en/developers/docs/nodes-and-clients/run-a-node/#requirements) section in the `Run a node` docs have a section with the following [medium link](https://medium.com/@migalabs/analysis-of-ethereum-2-consensus-clients-dfede8e0145e) which is broken. The page takes you to this

> ERROR
>
> 410
> This account is under investigation or was found in violation of the Medium Rules.
> There are thousands of stories to read on Medium. Visit our homepage to find one that’s right for you.

That link is in [this file](https://github.com/ethereum/ethereum-org-website/blob/299715d22967744fd31d174affba017e3360e305/public/content/developers/docs/nodes-and-clients/run-a-node/index.md?plain=1#L103)

### To reproduce

1. Go to [the requirements to run a node page](https://ethereum.org/en/developers/docs/nodes-and-clients/run-a-node/#requirements)
2. Click on link that says [details on consensus client requirements in this analysis](https://medium.com/@migalabs/analysis-of-ethereum-2-consensus-clients-dfede8e0145e)

### Expected behavior

Either a new link is needed, or it should be removed

### Screenshots

Screenshot of the link that does not work

<img width="778" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/352474/f85da9f2-e61a-4095-970e-a387110c95a7">

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
Hey @gndelia, thanks for reporting! Assigning you...

Was just peeking at the [archive of this page](https://web.archive.org/web/20220916225737/https://medium.com/@migalabs/analysis-of-ethereum-2-consensus-clients-dfede8e0145e)... at a glance looks like much could still be relevant, but seems they've taken the post down and probably best to just respect that and pull the link.

If you spot another link worth replacing it with please include it, otherwise would just remove this sentence.

@all-contributors please add @gndelia for bug report
