### ISSUE TITLE
Suggest a developer tool: Bitquery

### ISSUE THREAD

**Issue by divyasshree-BQ** [ethereum/ethereum-org-website#12565]
### Dev tool name

Bitquery

### Dev tool description

Ethereum APIs to access on-chain data such as tokens, NFTs, dexTrades, token holders, and more. Additionally, there are separate Beacon Chain APIs that provide information on deposits, validators, slashing, and attention.

### When did the dev tool go live?

2019

### Where do you think this page should be shown?

https://ethereum.org/en/developers/docs/apis/backend/

### Is the product open source?

Yes

### GitHub URL

https://github.com/bitquery/explorer

### Documentation URL

https://docs.bitquery.io/v1/docs/intro

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
Hey @divyasshree-BQ, thanks for the issue... We have an open issue (#12545) about how to handle the growing list of choices on this page since it's already quite unwieldy and becoming detrimental to user experience. 

Would like to see if any discussion evolves around that, or if anyone is willing to help organize these better before we list many more. Can review your suggestion here though and get back. Any features in Bitquery not already provided by the others on this page?

**Comment by wackerow** [comment]
Progress being made on organizing this list in PR #12605... can circle back here when that one is finished...

> 1. Infrastructure and Node Services
> 2. Development Tools
> 3. Blockchain Services

@divyasshree-BQ Out of these potential categories, which do you think Bitquery would fit into?

**Comment by wackerow** [comment]
Hey @divyasshree-BQ, checking in... #12605 has been merged. See previous comment and let me know; else we can close this out until ready. Thanks!

**Comment by corwintines** [comment]
@divyasshree-BQ I have assigned to you since you marked yourself as yes for wanting to work on this issue. Will follow up soon to see if there is progress otherwise will close this out. Thanks!

**Comment by minimalsm** [comment]
@divyasshree-BQ are you still wanting to work on this?

**Comment by corwintines** [comment]
Going to close this out as stale. @divyasshree-BQ if you are still interested, feel free to reopen :)
