### ISSUE TITLE
Typo, missing spaces

### ISSUE THREAD

**Issue by UNOFFICIALbgd** [ethereum/ethereum-org-website#12680]
### Describe the bug

missing spaces before and after dash

### To reproduce

1. Go to 'https://ethereum.org/en/run-a-node/'
2. Scroll down to 'Who should run a node?'
3. See error

### Expected behavior

.

### Screenshots

![image_2024-04-09_00-26-37](https://github.com/ethereum/ethereum-org-website/assets/71248977/126abe7d-5d8e-47b8-8eea-7a720fee6a28)

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by wackerow** [comment]
Thanks @UNOFFICIALbgd!... So these are "em" dashes, the widest of the em/en/hyphen forms of a dash:

- [How to Use Em Dashes (—), En Dashes (–) , and Hyphens (-)](https://www.merriam-webster.com/grammar/em-dash-en-dash-how-to-use)

Leaving the spaces out is the appropriate usage for this type of dash in this context. 

We could potentially go through and try to clean these up across the repo, since there are plenty of uses of the wrong type of dash or spacing, but would argue these are fairly low on the priority/impact scale.

Going to close this one out, but if others feel that consistency here would be that beneficial we could open a new task to focus on that.

**Comment by UNOFFICIALbgd** [comment]
@wackerow Sorry, didn't know about Em dashes, since they aren't used in my language

**Comment by wackerow** [comment]
You're not alone =)
