### ISSUE TITLE
Bug report: Broken link in Design and UX page

### ISSUE THREAD

**Issue by HayattiQ** [ethereum/ethereum-org-website#12711]
### Describe the bug

This article https://ethereum.org/ja/developers/docs/design-and-ux/
[Web3 needs more UX Researchers and Designers] (https://akasha.org/blog/2022/10/11/akasha-conversation-09-web3-ux-researchers-and-designers)  is no longer available.

### To reproduce

1. Go to 'https://ethereum.org/ja/developers/docs/design-and-ux/'
2. Click on 'Web3 needs more UX Researchers and Designers'
3. See error

### Expected behavior

Delete this line because it no longer exists.

### Additional context

This is small fix. So I can send Pull Request

### Would you like to work on this issue?

- [X] Yes
- [ ] No

**Comment by isabelladebrito** [comment]
Hi @HayattiQ, thanks for pointing this out! 

It seems the new URL for 'Web3 needs more UX Researchers and Designers' article is this one: https://blog.akasha.org/akasha-conversations-9-web3-needs-more-ux-researchers-and-designers

Since you've mentioned you'd like to work on fixing this, I'm gonna assign this issue to you. Let us know if you need any help!
