### ISSUE TITLE
An answer and its explanation are contradictory

### ISSUE THREAD

**Issue by iridiumcao** [ethereum/ethereum-org-website#13247]
### Page URL

https://ethereum.org/en/quizzes/

### Question content

Using Ethereum -> 3. Layer 2
![image](https://github.com/ethereum/ethereum-org-website/assets/754000/3bd78bb3-e325-4df1-93b9-960ee95bdeb9)

Question:
![image](https://github.com/ethereum/ethereum-org-website/assets/754000/d4a151c6-75f0-4442-bd4e-0d9f19703787)

The answer and its explanation are contradictory:
![image](https://github.com/ethereum/ethereum-org-website/assets/754000/be226f4b-60af-49a6-8ceb-f60ecf5aa411)

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by iridiumcao** [comment]
The pics I updated are not as expected, I'm going to edit...

**Comment by wackerow** [comment]
Hey @iridiumcao, thanks for reporting... Just noting that this is the incorrect answer because it's "All of the above", so perhaps we can add a simple note (as we do in other similar questions) that "This is not the only correct answer."

**Will open this up for a community contributor with the scope of adding `"This is not the only correct answer."` to the explanation for answer choices A, B an C here.**

**Comment by raspberri05** [comment]
Hi I can work on this

**Comment by raspberri05** [comment]
I've opened a pull request for this: https://github.com/ethereum/ethereum-org-website/pull/13272
Please let me know if I need to make any changes

**Comment by wackerow** [comment]
Great! I've assigned you @raspberri05.. commented on your PR, any reason this got closed?

**Comment by raspberri05** [comment]
Sorry, was a mistake. Ive reopened it here https://github.com/ethereum/ethereum-org-website/pull/13380

**Comment by corwintines** [comment]
Closing with above PR
