### ISSUE TITLE
Add a quiz for DEFI page

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#13648]
### Page URL

https://ethereum.org/en/defi/

### Question content

This is a call to action for someone to create a fun beginner friendly quiz questions and explanations for our DEFI page. The quiz will be accessible from defi page as well as from the [quiz page](https://ethereum.org/en/quizzes/)

**Format:**
Create 5 questions, each consisting of:

- Question prompt
- 1 correct answer with an explanation for why it is correct
- 3 incorrect answers, each with a unique explanation for why they are incorrect

Be mindful and use concise beginner friendly language. **All questions should be only related to the content that is present on the https://ethereum.org/en/defi/ page**

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by Etimfon007** [comment]
Hi @konopkja, I'll like to work on this issue.

**Comment by Etimfon007** [comment]
Hi @konopkja I've made my draft for the questions of the quiz. What's the best way to submit this. Do I need to create another issue and include a goggle document just like one which I saw?

**Comment by konopkja** [comment]
> Hi @konopkja I've made my draft for the questions of the quiz. What's the best way to submit this. Do I need to create another issue and include a goggle document just like one which I saw?

Hello, you can post it here in this issue as comments or link public google doc or even make PR (if you know how to do that).

**Comment by Etimfon007** [comment]
### For the Quiz section of DeFi:

---


### **Question 1**: Which of the following did DeFi start with?
A. Bitcoin
B. Ethereum
C. Cardano
D. Polkadot

**Correct Answer:** A. Bitcoin
Explanation: Since the main aim of DeFi is to make it possible for users to control they spend way they monetary value, Bitcoin being the first blockchain enables DeFi

**Wrong answers and explanations to it**

B. **Ethereum** - Ethereum builds on the idea of Bitcoin for storing and sending value, making it the second blockchain for the possibilities of DeFi. 

C. **Cardano** - The blockchain Cardano, follows Ethereum virtual machine rules (EVM), hence it is built on the concept of Ethereum. Built following another blockchain concept cannot make it the first chain DeFi started with

D. **Polkadot**: Polkadot is a blockchain that enhances the sending and storing of value on Ethereum and Bitcoin. Without the possibility of DeFi starting on Bitcoin, then Ethereum, the idea of Polkadot would not have been executed. 


---

### Question 2:  You can do the following with DeFi except?
A. Send money around the globe.
B. Ask a friend to be an intermediary while you send money around the globe.
C. Borrow funds with collateral without a middleman. 
D. Trade your tokens. 

**Correct Answer:** B. Ask your friend to be an intermediary while you send money around the globe
Explanation:  One of the possibilities of DeFi was to enable users to send and store value without middlemen but through smart contracts. 


**Wrong answers and explanations to it**

A. **Send money around the globe** - With DeFi you can send value to anybody anywhere in the world, there is no limit.

C. **Borrow your funds with collateral** - With DeFI, applications are created that makes it possible to borrow money same way it works with the traditional banking system. 

D. **Trade your tokens** -  Just like the traditional finance system, you can trade. Through, DeFi you can trade your ETH against USDT or any other currency. 


---

### Question 3: During quadratic funding, who gets more funding from the pool?
A. A project that receives a large number of value in the process of voting
B. A project with a large number of persons voting for it
C. It depends on what the project is building
D. It can vary per voting. 

**Correct Answer:** B. A project with a large number of persons voting for it

Explanation: Since the goal of quadratic funding is to fund/support projects that pose as public goods, the benefit of what the project brings can only be determined by what the community wants, so the greater number of people in the community that votes for a project, the more funding it receives from the pool. 

**Wrong answers and explanations to it**

A. **A project that receives a large number of value in the process of voting** - Quadratic funding was introduced for the fair hearing of the Ethereum community which was to solve the problem of centralization. With its design, it depends on the number of people who vote for a project and not the amount that a project is supported within during the process of voting. 

C. **It depends on what the project is building** - Quadratic funding depends on what the community considers a public good and what can help the Ethereum ecosystem scale. It doesn't matter what the project is building before it can get less or more from the pool. 

D. **It can vary per voting** - The rules of quadratic funding remain and it's carried out and technically designed to fund projects with a large number of persons voting. 



---

### Question 4: "Think of DeFi as in layers", if I make a transaction on Ethereum, where is the data of the transaction history stored? 
A. ETH
B. My Wallet
C. The smart contracts
D. The Blockchain

**Correct Answer:**  D. The Blockchain
Explanation: Ethereum as a blockchain stores all the data made by its users when transactions are made and this makes it possible for validators to store and maintain the same state across the P2P network. 

A. **ETH** - Data is not stored in ETH, ETH is regarded as the ticker of the native token - Ether. 

B. **My wallet** - A wallet is an application created to help store value and keep track of it. It doesn't store the data of the transaction history but details of the transaction history. 

C. **The Smart Contracts** - These are machine-readable codes written into the system to automate and carry out different functions during transactions. They exist as instructions of the blockchain and not data of transaction history. 


---

### Question  5: DeFi on Ethereum work through?

A. Smart Contracts
B. Middlemen
C. Bitcoin
D. Major not minor financial institutions

**Correct Answer:** A. Smart Contracts
Explanation: These are machine-readable codes written into blockchains such as Ethereum. It replaces legal contracts and middlemen and makes it possible that during transactions if pre-conditions are met then execution takes place and vice-versa. 

B. **Middlemen** - Ethereum doesn't need middlemen for transactions to run. Everything runs on the chain through smart contracts.

C. **Bitcoin**- Bitcoin is the first network on which DeFi runs on Ethereum builds on its concept but it doesn't power Ethereum and the DeFi that works on it doesn't depend on the Bitcoin network.  

D. **Major, not minor institutions** - For DeFi to be made possible on Ethereum, both minor and major don't need to be involved.

**Comment by konopkja** [comment]
> Hi @konopkja, here's the work [#13648 (comment)](https://github.com/ethereum/ethereum-org-website/issues/13648#issuecomment-2301862734) I did regarding this open issue. Is there anything you'll love I make changes to?

Hi! at first mostly looks good to me, thank you so much! There are few things I think we could do to make it better. I will share some suggestions soon.

**Comment by konopkja** [comment]
### Updated version:

I noticed that there were some typos and other minor issues so i updated it bellow, also i think the some questions were a bit tricky and perhaps should be rewritten.

 **ready for implementation**

---

### **Question 1**: What does DeFi stand for?
A. Decentralized Finance
B. Digital Finance
C. Distributed Finance
D. Development Finance

**Correct Answer:** A. Decentralized Finance
Explanation: DeFi refers to Decentralized Finance, a financial system built on Ethereum that operates without intermediaries like banks or financial institutions.

**Wrong answers and explanations to it**

B. **Digital Finance** -  Digital Finance refers to financial services that are provided through digital platforms, but it doesn’t specifically imply decentralization.

C. **Distributed Finance** - While “distributed” could imply decentralization, the term used in the industry is “Decentralized Finance,” not Distributed Finance.

D. **Development Finance**: Development Finance typically refers to financial support provided for projects aimed at economic development, often in developing countries, and is unrelated to blockchain or DeFi.


---

### Question 2:  What CAN'T you do with DeFi?

A. Send money around the globe.
B. Ask customer support to revert your mistakes.
C. Borrow funds with collateral.
D. Trade your tokens 24/7.

**Correct Answer:** B. Ask customer support to revert your mistakes.
Explanation: In DeFi, transactions are final and controlled by code rather than a company. So, if a mistake happens, like sending funds to the wrong address, there’s no customer support to help fix it. It’s a system that gives you control, but also asks you to be extra careful.


**Wrong answers and explanations to it**

A. **Send money around the globe** - With DeFi, you can send value to anybody anywhere in the world, there is no limit.

C. **Borrow your funds with collateral** - With DeFi, you can borrow money instantly, avoiding the days-long approval process of traditional banks.

D. **Trade your tokens** -  Just like the traditional finance system, you can trade. Through, DeFi you can trade your ETH against USDT or any other currency 24/7.  The market is always open.


---

### Question 3: Which DeFi platform is known for allowing users to swap tokens directly with one another?

A. Uniswap
B. Aave
C. PoolTogether
D. MakerDao

**Correct Answer:** B. Uniswap
Explanation: Uniswap is a decentralized exchange that allows users to trade (swap) tokens directly with each other using automated market-making mechanisms.

**Wrong answers and explanations to it**

A. **Aave** - Aave is a DeFi protocol focused on lending and borrowing, not token swaps.

C. **PoolTogether** - PoolTogether runs no-loss lotteries which offer a new innovative way to save money. 

D. **MakerDao** -  MakerDAO is a decentralized platform that allows users to issue and manage the DAI stablecoin, but it doesn’t focus on token swaps. 


---

### Question 4: "When you a DeFi app and make a transaction, where is the transaction information kept?

A. ETH
B. My wallet
C. DeFi apps
D. Ethereum blockchain

**Correct Answer:**  D. Ethereum blockchain
Explanation: Ethereum as a blockchain stores all the data made by its users and apps. This makes it possible for validators to maintain the same state across the P2P network. 

A. **ETH** - Data is not stored in Ether (ETH). ETH is the native token of Ethereum blockchain. 

B. **My wallet** - A wallet is an application that manages your Ethereum account by connecting to the Ethereum blockchain. It doesn't store any data about your transaction history. 

C. **DeFi apps** - No, DeFi apps don’t store your transaction history directly. Instead, your transaction details are recorded on the Ethereum blockchain.


---

### Question  5: What makes Decentralized Finance (DeFi) possible on Ethereum?
A. Smart Contracts
B. Middlemen
C. Bitcoin
D. Traditional financial institutions

**Correct Answer:** A. Smart Contracts
Explanation: These are like digital “if-then” statements written into Ethereum. They replace traditional contracts and middlemen. They automatically execute transactions if certain conditions are met, and do nothing if those conditions aren’t met.

B. **Middlemen** - Ethereum doesn't need middlemen for transactions to run. Everything runs on the chain through smart contracts.

C. **Bitcoin**- Bitcoin is simple network for storing value, not for running advanced programs. DeFi needs a more flexible toolbox (like Ethereum) that can run complex programs to handle things like loans and trades automatically.

D. **Traditional financial institutions** -DeFi apps don’t need traditional financial institutions behind them because they use blockchain programs called smart contracts to handle transactions automatically.

**Comment by Etimfon007** [comment]
I'm happy to have contributed to this!
@konopkja, you can check question 4 too, I guess there should be a "use" before "a"

**Comment by Shiva-Sai-ssb** [comment]
Hey @konopkja,

I'm interested in working on this issue! Could you please assign it to me? Also, could you clarify how the quiz should be accessible from both the DeFi and quiz pages—should it be embedded on the DeFi page or linked to the quiz page? Any guidelines or examples would be helpful.

Also, just to confirm, the quiz should be part of the "Using Ethereum" category and be marked as beginner level on the quiz page, correct?

**Comment by Shiva-Sai-ssb** [comment]
> I'm happy to have contributed to this! @konopkja, you can check question 4 too, I guess there should be a "use" before "a"

Yes, adding `use` before `a` would correct the sentence: `When you use a DeFi app and make a transaction, where is the transaction information kept?`

**Comment by konopkja** [comment]
> Also, just to confirm, the quiz should be part of the "Using Ethereum" category and be marked as beginner level on the quiz page, correct?

yes to both, sorry for delay in communication
