### ISSUE TITLE
Vertical alignment of mobile menu is off

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#1605]
**Describe the bug**

"Please, fix the wrong vertical alignment for toggle button in mobile"

**To Reproduce**

1. Go to any page on mobile
2. View the hamburger menu icon

**Expected behavior**

Should be aligned (with ETH glyph?).

**Screenshots**

![image](https://user-images.githubusercontent.com/8097623/95520041-44831200-097b-11eb-97aa-07e1fcbd472e.png)

**Desktop (please complete the following information):**
None

**Smartphone (please complete the following information):**
All

**Additional context**

This was an email received from press@ethereum.org.

**Comment by samajammin** [comment]
@ryancreatescopy any thoughts on:
1) is this an actual issue (is the current alignment suboptimal)?
2) if yes, an idea of what the solution should be (should the hamburger be larger? should it be center aligned w/ the ETH glyph?)?

**Comment by wackerow** [comment]
Hey, new to the repo, but wanted to try and help. Took a look at this and does seem to be awkwardly high, as no vertical alignment is specified, and it is aligning to the top of its slightly oversized container.
https://github.com/ethereum/ethereum-org-website/blob/cfe47996d826161d4efe747e5c206beb701fab1b/src/components/Nav/index.js#L50
Simplest fix without changing any actual sizing seems to be adding `align-items: center;` right after the above line of code. I would be happy to throw this into a PR if you agree.

**Comment by samajammin** [comment]
Thanks for offering @wackerow!

@ryancreatescopy keen to get your thoughts on this.

Current layout:
<img width="345" alt="Image 2020-10-09 at 2 03 40 PM" src="https://user-images.githubusercontent.com/8097623/95631329-5f678c00-0a38-11eb-94f5-e5bb21b5e2f9.png">

Aligning center:
<img width="349" alt="Image 2020-10-09 at 2 03 29 PM" src="https://user-images.githubusercontent.com/8097623/95631309-570f5100-0a38-11eb-9079-1a2850abfebe.png">

I think aligning center looks a bit better but I'm not sure it's ideal either.

Whichever solution we go with, I think we should try to align the close icon so it's in the same location as the hamburger icon.

Here's how the current close icon looks (when mobile menu is open):
<img width="352" alt="Image 2020-10-09 at 2 05 32 PM" src="https://user-images.githubusercontent.com/8097623/95631469-a05fa080-0a38-11eb-884e-8996d8e27f06.png">

**Comment by wackerow** [comment]
Tried a couple adjustments... both the line mentioned above, as well as adjusting this line:
https://github.com/ethereum/ethereum-org-website/blob/41d8fc75e5bd1768e0cc0c54333f7f8bc53c29f2/src/components/Nav/index.js#L25
to `padding: 1rem 1.5rem;` to bring both the hamburger menu and the wire logo a little closer to their edges:

![image](https://user-images.githubusercontent.com/54227730/95642263-496bc280-0a5c-11eb-87ee-cc59f1643a8b.png)
Problem here is the `anchor` tag holding the wire logo is causing ~7px of dead space at the bottom, almost like a `padding-bottom`, but, it's not (on either component), and I can't find where it's actually coming from. 

![image](https://user-images.githubusercontent.com/54227730/95642351-e0387f00-0a5c-11eb-8e28-489a636139e3.png)
![image](https://user-images.githubusercontent.com/54227730/95642364-ef1f3180-0a5c-11eb-8af8-0f23bf31d3a8.png)

It appears to be related to the anchor tag, as enlarging size of `img` causes the surrounding containers to expand, continuing to leave that gap at the bottom. _(What am I missing?)_ If we get rid of that gap, then the logo and the hamburger menu will truly be aligned along the same central horizontal axis, and should look nice. 

On the note of the location of the closing `X`, changing `top` and `right` properties on:
https://github.com/ethereum/ethereum-org-website/blob/41d8fc75e5bd1768e0cc0c54333f7f8bc53c29f2/src/components/Nav/Mobile.js#L65
...from `1rem` each to `1.5rem` each brought the `X` into alignment on a typical cell phone screen... of course tablets, or even the desktop version within a narrow browser window will have this same interface, but the X won't align due to the larger screen size. 

![image](https://user-images.githubusercontent.com/54227730/95643284-21cc2880-0a63-11eb-8613-527f04d1327e.png)
(Overlayed to show alignment)

If you like it so far, and if you can help me understand what's causing that gap below the wire logo I'll wrap it all up into a PR and send it over.
