### ISSUE TITLE
Ease the way to resolve dark and light mode images

### ISSUE THREAD

**Issue by Manik-Jain** [ethereum/ethereum-org-website#1847]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ryancreatescopy** [comment]
Hi @Manik-Jain could you please provide more information?

**Comment by Manik-Jain** [comment]
As of now, the code fetches data for both dark and light theme logos; and filters there after if the dark theme has been selected. I propose to run the filter first and check if darkTheme was selected or not; and accordingly just fetch the data in a single query. 

Please refer the code change : [](https://github.com/Manik-Jain/ethereum-org-website/pull/1/commits/523b0d579d3c4e66949b175424c0cb35ea031868)

Thanks
Manik Jain

**Comment by Manik-Jain** [comment]
`const Logo = () => {
  const themeContext = useContext(ThemeContext)
  const imageName = themeContext.isDark ? "ef-logo.png" : "ef-logo-white.png"
  const data = useStaticQuery(graphql`
    query {
      img : file(relativePath: { eq: imageName }) {
        childImageSharp {
          fixed(height: 100) {
            ...GatsbyImageSharpFixed
          }
        }
      }
    }
  `)

  return (
    <Img fixed={data.img.childImageSharp.fixed} alt="Ethereum Foundation Logo" />
  )
}`

**Comment by samajammin** [comment]
Hey @Manik-Jain - thanks for raising this issue!

We're definitely open to a better way of doing this but there's a few limitations here. Gatsby runs GraphQL queries at build times, so there's no way for it to know or react to changes of dark/light theme (or any React props/state). It essentially doesn't support dynamic queries (except for certain things, like page slug), so I don't believe your example would work. That's why we fetch both images in GraphQL.

More on that limitation here: https://github.com/gatsbyjs/gatsby/issues/2293
