### ISSUE TITLE
Move /eth2/staking under "Use Ethereum"?

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#1858]
**Is your feature request related to a problem? Please describe.**

Now that the site has the "Use Ethereum" list in the global nav. Should we move the staking page to sit under this section.

The purpose of this section is to group the more action-based content on the site. This page includes guidance on how to start staking, where to do it and links to checking the deposit contract. We may eventually have content that helps users run Eth2 nodes, which I imagine would live in the same place.

**Describe alternatives you've considered**

Leave it as a section of ETH2 under "learn".

Wait until we have content on running Eth2 nodes and create a section for Running Ethereum. Perhaps this is even grouped under developers content.

**Additional context**

Wanted to float this idea early to get community feedback.

**Comment by wackerow** [comment]
Personally like the idea. Tried this locally and I felt it made that section read very well "What is ETH?" "Get ETH" "Stake ETH". Also gives even more attention to Eth2.

On the note of making this section about "actionable" items, makes me question if "What is Ethereum?" is appropriate as the first item in "Use Ethereum"... perhaps moving this to the top of "Learn" would be more fitting?

### This is one suggestion:
![image](https://user-images.githubusercontent.com/54227730/99323329-ddcd0000-2826-11eb-8f4d-3234181472f3.png)

Suggestion, expanding on original post: 
"Use Ethereum" focuses on actionable sections, with an intro section of "What is ether (ETH)" which establishes what we're using here, followed by items that flow in the order of "Ethereum Wallets" which is needed before you "Get ETH" which is needed before you "Stake ETH" or before you go on to "Use Ethereum", which broadly encapsulates the whole network. 

"Learn" focuses on education for non-developers, with an intro section of "What is Ethereum?" and followed by "Guide and resources" to get people started. This continues with "Whitepaper" for the origin, "EIPs" for advances since, "Eth 2.0" for the future, and "Glossary" as an "appendix-like" reference. 

"Developers"... self explanatory, but rearranging to "Get started" followed by "Set up local environment" seems more appropriate, then have "Documentation," "Tutorials," and "Learn by coding"

**Comment by samajammin** [comment]
This was solved 👍
