### ISSUE TITLE
Add Prettier Solidity

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#1947]
**Is your feature request related to a problem? Please describe.**

Useful code formatting tool:
https://github.com/prettier-solidity/prettier-plugin-solidity

**Describe the solution you'd like**

Not sure the best place to put this 🤔

**Comment by wackerow** [comment]
@samajammin Are you requesting this be added as a developer tool? At first I thought you meant build it into this repo, but we have no `.sol` files, and given your reference from the above PR, so I'm assuming you're referring to listing this project somewhere.

Would be happy to help, I'll take a look and think about where this makes sense

**Comment by wackerow** [comment]
I am drawn to the Local Environment page for something like this, but 'Prettier Plugin Solidity' doesn't really fit in with the frameworks that dominate that page now.
Reviewing that file I see several commented out projects, including IDE's, testing libraries, local blockchains, contract languages, and js libraries. Just wanted to mention this since it seems like this type of project falls more into the categories that have already been tried and removed from the site.

Options include:
- Adding Prettier somewhere it doesn't quite fit
- Adding it by itself to a new section
- Selectively adding back previously removed projects that match this better (ie VS Code) and adding Prettier to these

**Comment by samajammin** [comment]
Sorry for the delayed reply @wackerow!

My 2 gwei: I think this fits best on the IDE page: https://ethereum.org/en/developers/docs/ides/

Perhaps we add a Plugins section within this page?

**Comment by wackerow** [comment]
@samajammin Yeah, that sounds good, I can take care of that... feel free to drop any other good plugin suggestions
