### ISSUE TITLE
Break out translation json files

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#2047]
**Is your feature request related to a problem? Please describe.**

Our app uses [`gatsby-plugin-intl`](https://github.com/wiziple/gatsby-plugin-intl) for internationalization. This plugin expects a single json file (located at /src/intl/${lang}.json) containing all strings for each language translation.

Here's our current en.json file (~1500 lines):
https://github.com/ethereum/ethereum-org-website/blob/dev/src/intl/en.json

This creates issues with our translation process in [Crowdin](https://crowdin.com/project/ethereumfoundation), where volunteers translate these files. Currently we wait until a file is 100% translated before passing it on to our professional translation review service. Waiting for the entire file to be translated is far from ideal... we want to be able to review & publish translation updates on a page-by-page or even component-by component-basis in order to publish translations ASAP.

**Describe the solution you'd like**

- Split out the monster en.json file into a set of distinct files (per page? per component? plus common strings?)
- Create a node script to merge these individual json files on build, so the app continues to work with the intl plugin

**Describe alternatives you've considered**
Still not sure how to best organize the json files...
- Break out the json files by end-user page?
- Break out the json files by component?
- Should we consolidate duplicate strings when possible (e.g. in a common.json)?

**Comment by wackerow** [comment]
I've been thinking about something like this as I've been working with the translation set up. 

As I've been setting them up, I try to organize them by the `js` file referencing them, which is typically either a page layout , or a reusable component... I think breaking them out by component/page is most natural, that way a new component can have its own language json, and can be translated and approved individually. 

I really like the idea of a "common" json as well. I'm not sure how it would work behind the scenes in terms of approving each change however, given that this list would likely change/grow over time as more phrases collide.

@samajammin Side question regarding translations while we're on it: Should we be proactively preparing for syntax issues between languages?  Many of our sentences are broken into pieces because of things like links being embedded, which I feel could cause difficulties when translating to a language where "subjects" "verbs" and "adjectives", for example, don't go in the same order. 
ie. `The green car` = `El coche verde` in Spanish. If we translated each word as a separate fragment, our translation would yield "El verde coche"

**Comment by ryancreatescopy** [comment]
This is a really good point @wackerow — ideally we shouldn't have links in the middle of sentences if they require a separate string. I've tried to do that as much as possible with links like "More on X" coming at the end of paragraphs rather than in the content itself, but have definitely slipped into bad habits in the last few pages. 

I wonder whether the crowdin software can do anything fancy to prevent this from happening though (as translations have been passing review). Or have we not translated a product page with this problem yet? @sorumfactory can you shed some light on this?

If not, I'm sure we can tweak the content on these pages to make sure we remove in-content links so that they're at the end of sentences on product pages. However this will be really difficult for pages like "glossary" and our "docs" — maybe it's not a problem in markdown files 🤞

**Comment by samajammin** [comment]
Ya great point @wackerow - thanks for weighing in.

> I wonder whether the crowdin software can do anything fancy to prevent this from happening though

I highly doubt it. There's only so much the software can do. At the end of the day, it's volunteers translating string fragments, which I agree is problematic if the main subject/verb/adjective is taken out of context from the sentence.

In terms of providing the actual link, which approach do we think is best?
A) Have the entire sentence be a link
B) Add a phrase after the sentence (e.g. "click here", "read more")
In other situations I would have SEO concerns about option B) - generally the anchor text of links should include relevant keywords to help provide context on what a page is about - but given SEO rankings are not much of a concern I think I'd be fine with that approach. Perhaps there's some additional context we could add as well, e.g. "More on wallets".

**Comment by ryancreatescopy** [comment]
We'll add a phrase at the end of sentences, but will try to avoid generic links like "click here" or "read more".

**Comment by samajammin** [comment]
One more consideration (which I suspect is less important) - do we suspect that capitalization may impact translations in any way? e.g. there's phrases like `"cookie-policy": "Cookie Policy",` - would that be interpreted different from `"cookie-policy": "cookie policy",` (maybe that's a bad example)?

If so, we could roll out a standard here for how the strings are stored in JSON. JavaScript can do the work to change a string into Title case or Sentence case depending on the context.

**Comment by ryancreatescopy** [comment]
I guess that would be up to the translator based on the context. That wouldn't break meaning in the same way as translators can capitalise/un-capitalise if necessary. I'd question whether that JS would be needed. But will defer to @sorumfactory expertise here.

**Comment by sorumfactory** [comment]
@wackerow Thank you for sharing great inputs. I can't agree more on your approach on the monster json file. Considering the UX/UI of Crowdin, it most make sense to breaking it out by page, that way translators can understand where each string they translate belongs to. Especially there are strings that are translated differently in different context. So I believe, grouping strings by page would be the most natural way.

Regarding the "common" json idea, I think the common strings(Home, Get started, etc) should be treated as "Others" as they are reusable components that are often duplicated in other occasions and not hugely impacted by the potential changes of individual pages. By keeping it separate, the approval process may take shorter as the Translation Memory will auto-translate and approve the same strings that were previously translated.

**Comment by sorumfactory** [comment]
Regarding the syntax issue with non-translatable elements, it hasn't caused much trouble by far.  First of all, Crowdin supports the "Syntax error detection" function. It reduces confusion during the translation by automatically identifying potential mistakes in the translation. Also it detects the subtleties of language specific spelling, grammar, and formatting in translations which help to prevent translators to make mistakes. If a syntax error is found, translators will get a syntax error message with a suggestion of what should be fixed. Even if translators miss out errors, our paid reviewers proofread the translations and fix syntax error at the final stage.

Secondly, there were not many syntax complications until the v.1.1 which was written in a basic Markdown form. A few troubles I get reported from translators was hyperlinks. If hyperlinks are embedded throughout the whole sentence or only on the "Subjects", it doesn't cause issue. However, if a hyperlink is **partially embedded** in the middle of the sentence, some languages may have troubles as Paul mentioned. Such as below: 

- Ethereum is programmable, which means that developers can use it to <1>build new kinds of applications</1>. 
- In Korean, for example, it looks just okay as the translator properly put tags in between but it's definitely not a proper way of embedding hyperlinks in official Korean docs.

More complicated problems may happen in Arabic and Hebrew translations. As their script is written from right to left, UI may look broken compared to the other languages. If it's only UX/UI problems, It wouldn't cause much trouble as long as content is delivered properly. 
However, as the new updated website is getting more complicated with more complex syntax, It may also affect the readability of content and interfere with interpretation.

**Comment by sorumfactory** [comment]
> One more consideration (which I suspect is less important) - do we suspect that capitalization may impact translations in any way? e.g. there's phrases in en.json like `"Cookie Policy"` - would that be interpreted different from `"cookie policy"` (maybe that's a bad example... would any actually matter)?

It's really a good point. Technically, capitalization affects on Crowdin. I tested it on Crowdin and found that "Cookie Policy" and "cookie policy" aren't 100% match but 99% match. So apparently they are treated as different words on Crowdin. However, in practice, it doesn't really affect the translation process on translator's side. For example, our Translation Memory would pre-translate and approve "Cookie Policy" based on the previous translation of "cookie policy" regardless of capitalization. Because there is a setting which I can choose to "apply pre-translation on the 99% matched strings". There are other matching options that help us to flexibly exclude/include such variables on the translation workflow.

**Comment by samajammin** [comment]
Solved in #2048

**Comment by samajammin** [comment]
> My thought was it's probably the simplest to make en.json entries naturally cased with capitals only at the beginning of a sentence or proper nouns, but to leave further styling to the CSS. This way the interpreter doesn't need to consider these things, and if we enter "HELLO" in the english file, and someone translates to "Hola", this could be difficult to catch. Standardizing to use CSS to style seems most appropriate in my opinion, and would override the individual translations. That way "Hello/Hola" could be styled to "HELLO/HOLA" as needed without changing the translation file, so these could be reused elsewhere as "Hello/Hola" again easily.

@wackerow sorry for missing this but I completely agree & we'd welcome a PR on this! Probably something worth adding to our documentation as well... 😄
