### ISSUE TITLE
Can't close sidebar on mobile

### ISSUE THREAD

**Issue by Kristiyan96** [ethereum/ethereum-org-website#2071]
**Describe the bug**

On a mobile device, after you open the sidebar there's no way to close it other than restarting the page.

**To Reproduce**

1. Go to https://ethereum.org/en/
2. Open sidebar from top-right hamburger menu
3. Try to close it

**Expected behavior**

There's an X button to close

**Smartphone:**

- Device: Pixel 3
- OS: Android
- Browser Chrome
- Version latest

**Comment by samajammin** [comment]
Thanks for reporting this @Kristiyan96! Will investigate ASAP.

**Comment by samajammin** [comment]
@all-contributors please add @Kristiyan96 for bug reports.

**Comment by wackerow** [comment]
@samajammin Looking at this now... the button got removed when the "mobile search" got added

**Comment by samajammin** [comment]
Solved in #2074 (thanks @wackerow)!

Curious what you folks think of this interaction in the case that
1) user opens mobile menu
2) user opens search
3) user closes search
Should the menu stay open (as it does now?) Or should both close?

Here's a video to demonstrate:
https://share.getcloudapp.com/OAuWq6q7

**Comment by wackerow** [comment]
@samajammin Personally, it makes sense the way it is. With the current animation design, when using search from the mobile menu, they visually layer on top of one another in two separate animations, which I would expect the search panel to unfold independently when closed (especially as the layout of the `X` changes slightly, which indicates it's a new/separate panel to a degree). 
As-is, this only happens when navigating to search from the menu, and it offers a "go back" button that would not otherwise exist. 
If you go straight to Search from the top nav bar however you wouldn't expect it to "go back" to a menu you never opened, and it doesn't.
