### ISSUE TITLE
Security page

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#2077]
**Is your feature request related to a problem? Please describe.**

We want to add a page that lists some security tips for staying safe and keeping your funds secure when:
- using a wallet – e.g. never share your private key ever
- using a dapp – e.g. always check the URL bar, scammers buy up fake domains like `cwrve.fi`
- staking – e.g. double check the contract address before depositing
- interacting with crypto social media/community platforms (e.g. how to avoid scams/ what to look out for) – e.g. Vitalik will never endorse giveaways, no one will ever send you 3 ETH in exchange for 1.

**Describe the solution you'd like**

I think the way we want to structure this is like different checklists – something that provides simple steps to follow or things to check dependent on what you're doing.

I'd like contributions to this issue to be in the form of the content of the specific tips that we should add to the page. **_What are the best security tips you'd tell your friends getting into crypto?_**

Feel free to think outside the categories listed above, maybe we want to talk about general best-practice security like using a 2FA and password manager etc.

**Rough sketch**
![image](https://user-images.githubusercontent.com/40891631/101478261-54ea4580-3948-11eb-8810-26ce1ce61652.png)

**Comment by wackerow** [comment]
Would love to help out with this if you want to assign. Were you thinking about this living in the Learn section as a page-conditional?

**Comment by wackerow** [comment]
...and just read closer again, looks like you're more looking for help with the content, in which case I'll get back to ya.
But lemme know if you want a hand with putting this together, started a draft.

**Comment by wackerow** [comment]
(unstale)

**Comment by qbzzt** [comment]
You may find this list of crypto failure modes (from https://github.com/qbzzt/etherdocs/blob/master/paper_wallet.md) useful for wallet security:

Here is a partial list of failure modes.

* **Lost mnemomic**. Those twelve words are the only way to transfer funds out of the account. If you lose them, you can
still gaze longingly upon the balance in your account, but you will not be able to get the funds.

* **Disclosed mnemonic**. This is the mirror image of the previous failure mode. *Anybody* with the mnemonic can
get your funds. If you think it may have been disclosed, it is best to create a new one and address 
and immediately transfer everything.

* **Forced disclosure**. For example, if you try to use this to avoid paying income taxes, the
tax authorities can prosecute you for tax evasion and throw you in jail until you pay them what they think you owe. Remember
that the people who pay you know your address, and that anybody with that knowledge can go to 
`https://etherscan.io/address/ <address>` and see the balance it holds.

* **Malware disclosure**. It is recommended to reboot the device to clear the RAM after you use the calculators. 
However, if the device has malware, that malware might record your keystrokes or screen to disk and then send it to whoever 
controls it when an Internet connection is available. In theory, it would be better to destroy the device instead of
using it after a reboot. However, in most cases that the cost is too high compared to the risk to justify this wanton
destruction.
  
* **Stealth disclosure**. Even a computer that isn't connected to any network 
[sends off radio frequency signals](https://www.cl.cam.ac.uk/~mgk25/pet2004-fpd.pdf). If somebody receives those signals,
they can decode what you see on your screen when you generate the mnemonic and address. If you are tring to keep a secret
from the NSA, you probably need to [get a special computer](https://en.wikipedia.org/wiki/Tempest_(codename)).

**Comment by wackerow** [comment]
@qbzzt This is great... definitely some stuff worth utilizing. This has taken the back burner recently, but definitely appreciate you dropping this here. Something I am still eager to spread the word on.

**Comment by IliadisVictor** [comment]
Is help still needed for this ?

**Comment by wackerow** [comment]
@Brent-Boyd Thanks for that post. I think this is a nice idea for improving the safety of the Discord community. @GeorgeTrotter thoughts? Another option could be to start "pinning" posts in that channel so they can be referenced quickly, though I feel many people probably don't think to look there. 

Ultimately I agree education around this topic is important. I would love to have more dedicated resources for this, just hard squeezing it in. @ryancreatescopy @samajammin Any thoughts on collecting ideas for security tips that we could maybe include in a sprint down the line?

**Comment by GeorgeTrotter** [comment]
I've been skeptical of recording scams in the past just because it takes work to stay on top of all the time, and because scams tend to spin up & spin down constantly when they grow stale. It's kind of like playing whack-a-mole, once you're aware of the scam the scammers are often already moving on. Plus having a list of scams could give users the impression that if a message isn't on the list, it's safe.

That having been said, I think a resource that's more along the lines of "This is what a scam looks like. They come in different shapes and sizes, but these are the things they always have in common" could definitely be useful.

**Comment by wackerow** [comment]
Absolutely... it's about seeing different flavors of scams at least once or twice, then being able to spot them quickly in the wild and stay safe.

**Comment by wackerow** [comment]
Going to close this with #3872, can expand on the new page with new issues if needed
