### ISSUE TITLE
Confusing statements in ETH 2 launchpad FAQ page

### ISSUE THREAD

**Issue by stanislavkozlovski** [ethereum/ethereum-org-website#2232]
Hey there,

I was reading the FAQ in https://launchpad.ethereum.org/faq and these two particular answers stood out to me:

> **How much ETH does a validator need to stake?**
> Before a validator can start to secure the network, he or she needs to stake 32 ETH. This forms the validator’s initial balance.

> **Is there any advantage to having more than 32 ETH at stake?**
> No. There is no advantage to having more than 32 ETH staked.
> Limiting the maximum stake to 32 ETH encourages decentralization of power as it prevents any single validator from having an excessively large vote on the state of the chain.
> Remember that a validator’s vote is weighted by the amount it has at stake.

I am confused as to how a validator's vote is weighted by the amount it has at stake.

From reading the above, I understand that both the minimum and maximum ETH required to stake is **32**. I assume that is not a correct understanding. I can see a two ways in how this assumption may not be the case:
1. you're allowed to withdraw some amount of your 32 ETH after the initial deposit. Obviously this can only be done until at least Phase 1.5
2. you're allowed to stake a certain percentage of your validator's initial balance

Are any of the above bullet points correct, or is it something else I'm missing? Once I understand the intricacy, I'll be happy to help with a contribution that clears the explanation up.

**Comment by wackerow** [comment]
@stanislavkozlovski Hey! Thanks for your interest... the "Launchpad" portion of the site is actually managed under another repo (https://github.com/ethereum/eth2.0-deposit).

That being said, I'll try to help your understanding... 32 ETH is the minimum in order to be activated as a validator:
 - As you proceed, you may gain ETH in rewards, moving your balance above 32, however, anything additional over 32 does not count towards your "effective balance" which is used to calculate your reward.
 - This also applied if you deposit more than 32 ETH from the beginning... anything above 32 won't increase your reward.
 - If as you proceed, say your node is offline and leaks ETH, your balance may drop below 32 ETH. There are thresholds where this will eventually drop your "effective balance" to less than 32 ETH, meaning your reward will get smaller. You cannot _start_ as a validator with less than 32 ETH, but you can end up there.

Good resource: https://www.attestant.io/posts/understanding-validator-effective-balance/
Also: https://ethereumstudymaster.com/

Hope this helps! Feel free to post a comment on the other repo if you still feel this needs clarification on the launchpad.

**Comment by stanislavkozlovski** [comment]
Thanks, this was my understanding as well after diving deeper into it. Your answer was very useful as well!

Let me open up an issue in that repo so that we make the statement a bit more straightforward.
