### ISSUE TITLE
Migrate content from eth.wiki

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#2325]
## Description

Dependencies: #2324 + #2323

Problems the community has surfaces around eth.wiki:

- Duplicate content
    - [https://eth.wiki/json-rpc/API](https://eth.wiki/json-rpc/API)
    - [https://eth.wiki/en/json-rpc/api](https://eth.wiki/en/json-rpc/api)
- Slow
    - [https://github.com/ethereum/eth-wiki/issues/49](https://github.com/ethereum/eth-wiki/issues/49)
- Lacking basic features
    - [https://github.com/ethereum/eth-wiki/issues/52](https://github.com/ethereum/eth-wiki/issues/52)
- Hard to contribute to
    - [https://github.com/ethereum/eth-wiki/issues/41](https://github.com/ethereum/eth-wiki/issues/41)
- Unclear licensing
    - [https://github.com/ethereum/eth-wiki/issues/53](https://github.com/ethereum/eth-wiki/issues/53)

Pages to consider:
- patricia tree spec?: https://eth.wiki/en/fundamentals/patricia-tree
- https://eth.wiki/en/concepts/standardized-contract-apis
- https://eth.wiki/en/fundamentals/design-rationale 
- https://eth.wiki/en/fundamentals/rlp

## Context

Original issue: https://github.com/ethereum/eth-wiki/issues/55

**Comment by BenM-Mycelium** [comment]
Would be happy to take a look

**Comment by wackerow** [comment]
@BenM-Mycelium Thanks for offering! @samajammin Where did we land with the content migration from eth.wiki again? Curious your take on pulling in help on this. Will be a big project and require a fair amount of organization.

**Comment by cdomashn** [comment]
If there is some do-able/reasonable sub-task I can start with without an organization, I am willing to give it a try.

**Comment by cdomashn** [comment]
After testing the waters with wiki.js and eth-wiki github repo, for a whole host of reasons I am inclined to suggest keeping eth.wiki around for a little longer. Very many eth.wiki links are broken (or rather dead) indeed, however on my local clone/server I was able to identify/fix at least a good half of them I believe, including:
- dead links to external websites,
- internal eth.wiki links,
- links to the the old wiki hosted by github.

If you agree to keep wiki.eth around, my suggestion would be
- labeling dead external links as such,
- fixing the internal links,
- replacing links to the old wiki with internal links. This will involve copying a couple of files from the [old-before-deleting-all-files-go-to-wiki-wiki-instead](https://github.com/ethereum/wiki/tree/old-before-deleting-all-files-go-to-wiki-wiki-instead) branch to eth.wiki.
All of the above is doable before EoY I believe.

I still would have to look at the write Permissions/Privileges (the issue raised in this Ticket), etc but there is some room for cautious optimism here as well:
- GitHub Authentication/Logins simplifies the situation as no local user Administration is really needed;
- wiki.js can sync the hosted site to a designated Git repo/branch. This means Privileges do not have to be super-tight because the old versions are fairly easily recoverable and so on.

Several reasons why I have some reservations against moving Wiki to Ethereum.org: 
- you already may have performance/startup issues with Gatsby Cloud hosting Ethereum.org and wiki will likely make it worse;
- if you migrate Wiki to Ethereum.org, you will likely lose some Wiki content;
- you may need to add new packages to the yarn stack.

My 2 cents. Let me know what you think.

**Comment by samajammin** [comment]
Closing this in favor of https://github.com/ethereum/ethereum-org-website/issues/5690 - please move discussion there 👍
