### ISSUE TITLE
Fix disparity between wallets on "Get ETH" and "Find a Wallet" page

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#2467]
**Is your feature request related to a problem? Please describe.**

Currently we list wallets w/ fiat onramps to buy crypto in 2 places
1) https://ethereum.org/en/wallets/find-wallet/?filters=has_card_deposits
2) https://ethereum.org/en/get-eth/

These don't pull form the same data source.

**Describe the solution you'd like**

Let's refactor the Get ETH page logic to query the wallets.csv & filtering wallets based on if they support fiat onramps (`has_card_deposits`?).

**Additional context**

This begs the question of what is the best way to categorize / define this feature functionalities with wallets. Currently we have `has_card_deposits` & `has_bank_withdrawals`. In terms of buying ETH through a wallet, the best feature consideration might be `has_fiat_onramps` in the sense that a user can buy crypto with fiat currencies, either through a credit card OR an ACH integration with their bank account.

**Comment by samajammin** [comment]
@ryancreatescopy we've discussed this offline in the past, curious to hear your thoughts here. This resurfaced as an issue w/ the recent wallets @wackerow has added & where updates to the codebase are needed whenever we add a new wallet. Right now this adds a bit of a manual process.

**Comment by ryancreatescopy** [comment]
@samajammin The bank withdrawals feature refers to the ability to withdraw your crypto as fiat in your bank account — fiat off ramps not fiat on ramps. 

Yeh ideally if the wallets data source includes `has_card_deposits` we should also include the fiat-on-ramp provider and the associated territories. This way it could be used on the get-eth page too. Don't know how easy it would be to merge these data sources. But in order to use one data source it needs to contain the geographical restrictions info.

Hope that makes sense.

**Comment by samajammin** [comment]
This is still an issue, even though we now us this data file for /find-wallet page:
https://github.com/ethereum/ethereum-org-website/blob/dev/src/pages/wallets/find-wallet.tsx

**Comment by corwintines** [comment]
Fixed with https://github.com/ethereum/ethereum-org-website/pull/7367
