### ISSUE TITLE
The community really could benefit from an ethereum discord

### ISSUE THREAD

**Issue by pr0toshi** [ethereum/ethereum-org-website#260]
There is no ethereum discord for the ecosystem as a whole and many are only made for 1 purpose like dapps or trading. By making a general one the community would be able to grow together and all people would be able to influence others and stop tunnel vision from segregating the community.

## Expected Behavior
We will be focusing on building the space and towards a unified and decentralised future. The intent is to help unify the space and allow for collaborative efforts in growing the cryptocurrency ecosystem in a collaborative environment.
If a project would like a channel they would just ask a mod to put one up. 

Channels are optional to join and you'll be able to to customize what you want to see while part of 1 community.

Moderation is done the same way, mods on higher branches have authority on lower branches to always be accountable and limit power abuse.

## Behaviour
People only join project or purpose base communities like those for making dapps or for dapps themselves. By combining them all we would be able to make the space more collaborative.

## Possible Solution
Multiple optional channels.
Hierarchical Moderation.
Multipurpose communities under 1 large community with all the purpose of growing the ethereum ecosystem.

## Context
Helped make a community for technical people known as cryptodevs. Great community but not large reach because of specialization. Also mod the one for r cryptocurrency but the community has become unhealthy with most only there to make money.

**Comment by pr0toshi** [comment]
Made a proof of concept with the above done. Roles for projects and purpose. Mod roles for only that channel by project leaders. All the other usual bots.

**Comment by samajammin** [comment]
Hey! Thanks for suggesting this. It's certainly a topic I've been having discussions about the past couple weeks. I think it has solid potential. I'm curious to hear any other folks weigh in.

In my mind, "what is the best structure for community-wide online communications?" is an outstanding question. Is there an ideal size of a chat server? Is it necessarily a negative that separate communities have domain-specific or project-specific chats? If the online community increases by 10x, is a single chat server still the best format?

My hunch is that the easiest way to answer these questions & build a successful online community might be to evolve an existing one. For instance, have you considered talking to the other mods at [cryptodevs](https://discord.gg/EDA6M3R)? Maybe they would be open to a "re-brand" to include a more general audience. There's already channels in there for design & marketing... I don't think it's a stretch to add additional focus areas like legal, financial, language translation, or other domains topics organically rather than creating a new server from scratch.

I'm also not convinced that an "Ethereum Discord" is within scope of this website. At least for now, given current resources, I'd lean more towards creating a "Community" resource page similar to [React's community page](https://reactjs.org/community/support.html) and link out to the online communities that exist. That said, I welcome this discussion & would love to see it produce some action items, whether it's folks volunteering to help you create & moderate this new Discord or existing communities incorporating your ideas.

**Comment by pr0toshi** [comment]
I had brought it up in the past but they had only wanted to keep it for devs. I understand the reasoning behind expansion of a community but honestly there are none that are both ethereum base and not only for 1 purpose.

**Comment by samajammin** [comment]
Got it. I totally support the initiative but in my mind, it's out of the scope of this website. I'll keep this issue open for now in case other folks want to weigh in or get involved.

**Comment by pr0toshi** [comment]
It would also help with open and real time discussion about prs and proposals on for this project.

**Comment by jjmstark** [comment]
Hey @pr0toshi - this is an interesting idea, but Sam's right that it's out of scope for ethereum.org. That doesn't mean it's a bad idea, it just means that "should there be a discord that gains wide adoption within the Ethereum community?" isn't something that the website team should decide, or has control over.

Instead, this is something that anyone in the community is welcome to start on their own - you don't ned anyone's permission to start a discord and get people to use it! There are already some online chat groups that might be interesting to you, either to serve this purpose or as a place to try and recruit people to a discord, like the [gitter chats for various ethereum repos](https://gitter.im/ethereum/home).

**Comment by samajammin** [comment]
Closing this out for maintenance purposes. We still support the initiative if anyone is able to take it on! In the meantime, hopefully the upcoming Community page #269 will help solve some of the issues you raised.
