### ISSUE TITLE
Add a "Community" page

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#269]
## Expected Behavior

Create a page that displays community resources (i.e. ethereum.org/community) to provide tangible ways for visitors to connect with others & get involved in the Ethereum community.

## Current Behavior
Page does not exist

## Possible Solution
Something similar to [React's community page](https://reactjs.org/community/support.html)
Possible areas to cover:
- Online communities (forums, chat servers, StackOverflow topics)
- Events
- Meetups
- Media (podcasts, news outlets, social accounts)

## Context

Discussed with https://github.com/ethereum/ethereum-org-website/issues/260

## [UPDATE: 11/25]
Page draft here: https://paper.dropbox.com/doc/Ethereum.org-Community-Subpage--ApSbLBst88Orfx1kqLOJx2IuAg-T7PZSn1jFvEnSVwE4co3h

**Comment by pr0toshi** [comment]
Really hope this gets through. The .org is the reference for anyone new and would be the first place many go to find out about the project. ethereum being about open and collaborative community it's off to not promote that community.

**Comment by jamesconnolly93** [comment]
I can take a crack at putting this together this week if there isn't someone working on it already.

**Comment by pr0toshi** [comment]
Got one that I was thinking of just converting that was going to be for a knowledge base project on eth but could just generalize to the space. Got optional channels and all that up. 

https://invite.gg/branch

**Comment by samajammin** [comment]
I started a basic sheet to organize info on various Ethereum communities, feel free to add to it! https://docs.google.com/spreadsheets/d/1fRpwpbAUYgbIGjC_rqmYR9TYW5sTuRdACTb2RopjLko/edit#gid=0

**Comment by jamesconnolly93** [comment]
Awesome. One thought - just looking at the list of events, should we maybe just point people to Meetup as a place to search for events rather than trying to vet this list? Could be hard to manage over time as people tag new events with 'Ethereum' on Meetup. 

Just on a cursory glance there are EOS events etc. that are on there but not really related to Ethereum. Trying to curate this list seems like a challenging ongoing task.

**Comment by samajammin** [comment]
Completely agree. I suppose I wasn't clear about that 😄  

At least to start, I'm thinking we focus on the "communities" tab, which references [Ethereum Meetups](https://www.meetup.com/topics/ethereum/) as one of them. I scraped that Meetup list mostly out of curiosity. Feel free to add other categories you're interested in, although I can't promise they'll be added.

**Comment by pr0toshi** [comment]
Would we allow for communities that are projects on eth or general crypto communities. Like how open are we going. R cryptocurrency would be another but that's general but saw cryptodevs on there so do we put ones that are eth heavy but not only for eth. Also on the other side do we allow communities for projects that are on eth like moloch where it's not really eth but is.

**Comment by samajammin** [comment]
Good question. What do you think? 

My initial thought is to start narrow (i.e. Ethereum-specific communities), then potentially expand the scope as time goes on. Ethereum certainly doesn't exist in a vacuum... there's overlap across many projects/communities but we also don't want to overwhelm or confuse visitors. One option could be a separate section for "general blockchain communities"? For that spreadsheet, I defaulted to "if in doubt, include it". There will ultimately have to be some form of the curation process, similar to how any other addition to the site is decided (see project readme for details).

**Comment by jamesconnolly93** [comment]
I agree 100% on the general philosophy of starting narrow. In my view, breadth should be added by referring to other sources like EthHub and similar community resources as they develop. 

My concern with adding "general blockchain communities" is that we open up the ethereum.org site to the possibility of linking to projects administered by bad actors and giving the impression that these are endorsed by the Ethereum community at large.

I would advocate for adding some sort of disclaimer about the risks associated with engaging with the projects that do exist in the space, and being extremely selective of those that are featured on ethereum.org. Instead of "general blockchain communities" we could promote content describing "general blockchain technology"?

**Comment by pr0toshi** [comment]
While cryptodevs are general I would probably keep them as they are the best community for dapps. But otherwise would agree. Maybe eth focused rather than only might be a good way to think about it otherwise we get the problem where no other crypto is allowed and honestly eth should look to other projects for improvements it could make.
