### ISSUE TITLE
programmable music dapp

### ISSUE THREAD

**Issue by issanyo** [ethereum/ethereum-org-website#2736]
**Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible**

The dapp is open source, anyone can report issues here: https://github.com/ausync/application

**Is your dapp open source?**

Yes, anyone can contribute here: https://github.com/ausync/application 

**Can a user access the dapp without creating an account?**

Yes, it's enough a web3 client like MetaMask

**Are dapp funds non-custodial?**

Yes, the frontend just interacts with the smart contract 

**Do you offer community support?**

Don't have support chat for now, the supports can be raised on the github repo

**Describe any geographical restrictions on usage of your dapp**

No restrictions

**Dapp title**

Ausync

**Dapp description**

Create NFT programmable music

**Dapp logo**

https://ausync.io/wave.svg

**Brand color**

#343a40

**Comment by ryancreatescopy** [comment]
Hi @issanyo this looks like a really cool project. However at the moment we only list dapps that are pretty well established (full-time teams, large user bases), simply because they've managed to invest time in UX, support, and (hopefully) security. Would be interested to see how this project progresses – feel free to raise this issue again once you're further along in the journey!
