### ISSUE TITLE
"Waffle say hello world..." tutorial duplicating on list

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#2766]
**Describe the bug**
A recent change to lowercase the folder name of `/waffle-hello-world-with-buidler-tutorial/` has caused a duplication where the capitalized version is still being listed/hosted (`/Waffle-hello-world-with-buidler-tutorial/`)

**To Reproduce**

1. Go to https://ethereum.org/en/developers/tutorials/
2. Scroll down to "Waffle say hello world tutorial with hardhat and ethers" (cmd+F/ctrl+f "hello")
3. Notice duplicate

**Expected behavior**
Only one should be listed.

**Screenshots**
![image](https://user-images.githubusercontent.com/54227730/113200946-cf074880-921d-11eb-9ab0-f00233160ea1.png)

**Comment by mic0des** [comment]
Hey @wackerow I found this very curious so I tried it in my local environment. I manually renamed the 'Waffle-hello-world...etc.'  directory with a lower-case 'w'. Right after that change, in my localhost's tutorials page, I found something similar to the production version: there were repeats of that tutorial (one linking to an uppercase slug, and another linking to a lowercase).

I then manually restarted the dev server and went back to my localhost's tutorials page, and found that suddenly the expected behavior was working: only one of that tutorial was present. So one theory is this might not necessarily be a bug, but some sort of caching issue where the ```gatsby-source-filesystem``` plugin (or something else in the build system) added the lowercase 'w' as a new file, but also kept the old one. A 'turning-it-off-and-on-again' seemed to do the trick for me locally, which seemed to make Gatsby forget the old capital 'W' version.

<img width="1160" alt="Screen Shot 2021-04-03 at 4 13 11 PM" src="https://user-images.githubusercontent.com/4992682/113490472-287aac00-9498-11eb-91d2-2548df54c436.png">

**Comment by wackerow** [comment]
@mic0des Yeah, you may be right here... I think Netlify may be holding onto the old folder in its cache, may see if I can fix this with next deploy.

**Comment by wackerow** [comment]
Well the 2.22 deploy went live, and it certainly didn't fix this... This tutorial is now not showing up at all on the list, and if you direct the URL to https://ethereum.org/en/developers/tutorials/waffle-hello-world-with-buidler-tutorial/ it will load with the cached "Live Help" component that got removed in this deploy. Will take a look at Netlify, see if we can't clear the cache.

**Comment by minimalsm** [comment]
@wackerow Don't think this tutorial exists at all anymore? Not sure if it was removed deliberately but it closes this issue.

**Comment by samajammin** [comment]
Looks like we inadvertently deleted these? 

@wackerow here's some old references that we can re-add:
- https://github.com/ethereum/ethereum-org-website/blob/a4af8c97b6294d3995bf5fca9c62cbe252b038a2/src/content/translations/ro/developers/tutorials/Waffle-hello-world-with-buidler-tutorial/index.md
- https://github.com/ethereum/ethereum-org-website/blob/a4af8c97b6294d3995bf5fca9c62cbe252b038a2/src/content/developers/tutorials/Waffle-hello-world-with-buidler-tutorial/index.md

Please make sure the directory/file/slug names are lowercase :)
