### ISSUE TITLE
Mixing Standard British English and Standard American English

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#2786]
Writings on the site mix the use of both American and British spellings (e.g. monetise / monetize).

**To Reproduce**

1. Go to https://ethereum.org/en/developers/docs/web2-vs-web3/
2. See 'decentralized' and 'monetisation' in the first paragraph.

**Additional context**

A quick search in the md files shows that there is a lot of British Standard English throughout. The word 'decentralized' might be used as it's tethered to dApps generally. (An SEO thing?)

(e.g. google search for 'decentralised applications' shows no hits on the first page containing the word decentralised)

![Screenshot 2021-04-05 at 20 50 11](https://user-images.githubusercontent.com/62268199/113619507-f82a3d80-9650-11eb-9753-2a851e732609.png)

**Comment by samajammin** [comment]
Hey @minimalsm - thanks for raising this. I don't see this as a major issue or have a strong preference but I agree we should probably keep uses consistent for the sake of readability & translations.

Looking at Google search volume, American spelling does seem to be dominant worldwide (at least for ["decentralized" vs. "decentralised"](https://trends.google.com/trends/explore?q=decentralized,decentralised)):

![Image 2021-04-06 at 6 44 18 PM](https://user-images.githubusercontent.com/8097623/113798712-92998800-9708-11eb-8ce1-dc8d997f2dcb.jpg)

Ultimately I'll yield to @ryancreatescopy who's blood, sweat & tears we have to thank for the majority of the site copy. I think he's more than earned his say. Don't want to stomp on his heritage 😅.

**Comment by wackerow** [comment]
@ryancreatescopy Agree with Sam... don't see it as a huge issue, but always a fan of keeping things consistent and applicable to the largest audience possible. Totally up to you, but feel free to reassign to me if you want, or gracefully close =)

**Comment by minimalsm** [comment]
Another issue I've just realised after reviewing #2805. Punctuation differences between British and American regarding quotation marks.

Example in suggested changes
```diff
- This is known as a "slot".
+ This is known as a "slot."
```
The latter (american?) version just looks wrong to me but [this grammarly article](https://www.grammarly.com/blog/quotation-marks/#:~:text=Do%20commas%20and%20periods%20go,go%20inside%2C%20sometimes%20stay%20outside.) suggests it is correct.

<img width="727" alt="Screenshot 2021-04-09 at 12 44 18" src="https://user-images.githubusercontent.com/62268199/114175168-98be7d00-9931-11eb-9710-2183b82b8f46.png">

If/when the project's preference is decided it is probably worth putting it somewhere in the contribution guidelines before contributors either side of the pond start playing grammar ping pong 😀. (suggested it on Discord but noting here for discussion purposes)

**Comment by ryancreatescopy** [comment]
We've never actually stated what version of English the site should use due to the open-source, decentralized nature of contributions. To be completely honest, if it doesn't affect readability I'm slightly unfussed about whether we use American English or British English. And the inconsistencies don't bother me too much – I sometimes think this site should sound like a bunch of different voices.

However, if folks are wanting to make things consistent, I'd suggest American English, simply because the ecosystem is larger states-side and "decentralized" is much more famously spelled with a 'Z' in the space! Would happily review a PR but don't have time to comb the site and standardise this right now. 

P.S. This full stop (or period) inside the quotes – `This is known as a "slot."` – makes me feel sick.

**Comment by minimalsm** [comment]
> P.S. This full stop (or period) inside the quotes – `This is known as a "slot."` – makes me feel sick.

makes my brain hurt 🧠

**Comment by wackerow** [comment]
Hah that's great... I didn't realize this punctuation difference out there. I've always been taught to place the punctuation within the quotes, never knew there was regionality to it. 

> Either way the inconsistencies don't bother me too much – I sometimes think this site should sound like a bunch of different voices.
I do like this comment, "like a bunch of different voices"... since that's really what it is and should be. Open to hear thoughts on blending a consistent professional interface with open source, contributor based content. 

@minimalsm Maybe use this as a place to chat over suggestions and form a game plan before further PRs on this topic

**Comment by ryancreatescopy** [comment]
Doing a little pruning and closing this one out. Feel free to reopen if there's more to discuss.
