### ISSUE TITLE
Link directly to wallets, not lists of wallets

### ISSUE THREAD

**Issue by vbuterin** [ethereum/ethereum-org-website#28]
Currently it takes a huge number of clicks to actually get to a wallet:

* Click "use"
* Click or scroll down to  "what is a wallet"
* Decide which of the four linked guides to click on
* Get lucky and click on "get started with Metamask"
* Or click on the ethhub link
* Click on "desktop wallets"
* Click on MyCrypto, get taken to a github page for some reason
* Go back and click to the link that says where MyCrypto is downloadable

IMO this is a huge usability hurdle, we're basically requiring users to go down a pretty complicated educational rabbit hole before they can _just get a wallet and have an ethereum address_.

I would favor replacing this approach with a more opinionated one: we just link to the pages (ideally a tutorial link and a download link each) for some wallets that we select, (eg. Metamask, MyCrypto, the Opera browser, TrustWallet, a few more) that we deem to be high quality enough to expose new users to.

Also, I would favor switching around the order: step 1 should be getting a wallet, step 2 getting some ETH, step 3 using applications. This makes more sense because it's the only logical order in which you can do things: you need a wallet to get ETH, and you need a wallet and ETH to use applications.

**Comment by pcowgill** [comment]
Great points - agreed that there should be fewer clicks to get to a wallet.

> you need a wallet to get ETH, and you need a wallet and ETH to use applications.

Here’s an argument for linking to apps first, though: You don’t need a wallet to “use” apps by browsing in read-only mode. For a new user, it’s important to see the value of a given Ethereum app in a concrete way before experiencing the friction of setting up a wallet.

**Comment by zhangzhongnan928** [comment]
> Great points - agreed that there should be fewer clicks to get to a wallet.
> 
> > you need a wallet to get ETH, and you need a wallet and ETH to use applications.
> 
> Here’s an argument for linking to apps first, though: You don’t need a wallet to “use” apps by browsing in read-only mode. For a new user, it’s important to see the value of a given Ethereum app in a concrete way before experiencing the friction of setting up a wallet.

Users can start using [AlphaWallet](d.alphawallet.com) and experiencing DApps instantly. The wallet doesn’t  require users to do anything before they have some mainnet “asset”.

**Comment by jjmstark** [comment]
I agree with @vbuterin's suggestion of changing the wallet section to be more "opinionated" by prioritizing a small list of trusted wallets.

I disagree with changing the order of the contents of the page:

- "Wallet, ETH, Apps" is a logical order of operations for someone who already knows what they are trying to do. But this page exists to serve people who don't even know what "using Ethereum" means - they aren't going here because they know they need a wallet, they're going here because they want to "use Ethereum".
​​- ​​So the first question this page has to answer for them is “Ok, what can I actually do with Ethereum?”. The answer to that application is "use one of these applications". Getting a wallet is a _how_, not a _what_ or _why_.
- ​​If we hook someone on “Oh wow a prediction market, that seems cool…” it’s not a big barrier for them to scroll down and find a wallet. Hooking them is the important bit. 
​​- It seems a lot better to have users taught how to use a wallet and how to buy ETH by these application's onboarding process than by us on ethereum.org. If a user clicks through to veil, uses their on-boarding process, and never needs to come back to Ethereum.org to get started...that's a win. The apps we link to here are *always* going to be better at on-boarding than ethereum.org
​​- As a few people have pointed out already, some of these apps don't require installing a wallet at all.

**Comment by vbuterin** [comment]
> It seems a lot better to have users taught how to use a wallet and how to buy ETH by these application's onboarding process than by us on ethereum.org

That approach feels like a lot of redundant work: with O(N) applications, we'd have O(N) redundant content in the tutorials instead of O(1) content if we can establish the baseline expectation that it's our/ the community's / the wallets' job to do basic tutorialing.

If why -> how the goal, I would at the very minimum favor renaming "Use an application built on ethereum" to "What are some existing applications that are built on ethereum?". Emphasize the "we're showing you why ethereum is useful" rather than "you can use ethereum already".

**Comment by jjmstark** [comment]
>That approach feels like a lot of redundant work: with O(N) applications, we'd have O(N) redundant content in the tutorials instead of O(1) content if we can establish the baseline expectation that it's our/ the community's / the wallets' job to do basic tutorialing.

I think this might be a case of "good redundancy", or at least inevitable redundancy. Apps like Veil and Cryptokitties aren't going to link to ethereum.org/use to on-board their users to a wallet. They are always going to want to own the on-boarding process themselves, and are highly incentivized to do a very good job of making it easy for their users. There will be redundant wallet on-boarding tutorials regardless of what is on ethereum.org.

That said, I think this page could be a lot better and even restructured. Maybe there's an argument for separating out "What can I do on Ethereum today" - maybe this could be folded into /beginners? - and "Install a wallet". It might be true that many more people actually just clear information about a good wallet, and don't want to be slowed down by information about apps and ETH.

**Comment by jjmstark** [comment]
@bennygiang (Cryptokitties), @pfletcherhill (Veil), @owocki (gitcoin), what do you think about the above?

**Comment by pfletcherhill** [comment]
I agree with the "good redundancy" point from @jjmstark. Apps are going to have their own onboarding flows, and that's a good thing. But @vbuterin is right that this page can do a better job helping users rather than linking to guides that may help.

My suggestion would be to add one sentence at the top of the page that entices the user. Maybe something like:
>This page will show you how to use one of the many apps built on Ethereum—like Cryptokitties, Cent, or Veil. Already have a wallet with some ETH? Jump ahead to step 3 to see a full list of applications.

Then include a three-step guide for (1) getting a wallet, (2) getting ETH, and (3) using an app. As for the wallet section, I also agree the page should first list specific wallets and then second list guides. The guides are helpful if I want to see a bunch of options, but the user should be able to get set up from this page alone.

**Comment by serapath** [comment]
I agree with @vbuterin 

> That approach feels like a lot of redundant work: **with O(N) applications, we'd have O(N) redundant content in the tutorials instead of O(1) content** ...

and @pfletcherhill 

>  Apps are going to have their own onboarding flows, ...

and wonder if @jjmstark 

> I think this might be ... inevitable redundancy. 

is really necessarily true? Can nothing be done about it?

---

Generally the current approach the new website is taking is exactly causing the above, and:
1. The more projects get added, the more serious this problem gets.
2. additionally "awesome lists" teach how long lists can get, which is a different, but related problem.
3. pull request approval might soon become a serious bottleneck problem and some might potentially start perceiving it as censorship too

With the https://play.ethereum.org `"skilltree" of "workshop" pages`, we (@ninabreznik and myself) thought a lot about education in the ethereum realm and it's exactly why we started experimenting with a very different approach in order to
1. make the curation process more decentralised
2. and fight a "pull request approval bottleneck process"
3. and also prevent unnecessary redundancy.

It's a very young project not even yet in beta state, but maybe our ideas could help to solve the issues mentioned in this thread :-)

**Comment by bonusword** [comment]
Haze em
