### ISSUE TITLE
Subheadings under beginners / learn / use / build should be anchor links to sections

### ISSUE THREAD

**Issue by vbuterin** [ethereum/ethereum-org-website#29]
I think the subheadings under the four sections should be anchor links to the specific sections of the page that they refer to. IMO it intuitively feels like they should be links, and feels weird when they are not. It would also help people get to the information they want faster without having to go through so many clicks.

**Comment by jjmstark** [comment]
I think all we need to make this change is to swap out "Non-technical and beginner resources" under *Learn* (since that doesn't correspond to a section with the same title) and replace it with "Ethereum basics". 

All the other ones correspond to an actual subsection on a page (or in the case of beginner, all just link to /beginner).

**Comment by jjmstark** [comment]
Was fixed in #120
