### ISSUE TITLE
Automatically filter out past community events

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#2914]
**Is your feature request related to a problem? Please describe.**

Currently removing [events from the community page](https://ethereum.org/en/community/#upcoming-events) is a manual process e.g. https://github.com/ethereum/ethereum-org-website/pull/2885

**Describe the solution you'd like**

We should use a data file (e.g a [JSON file like this](https://github.com/wackerow/ethereum-org-website/blob/9e8c6214cb2acf001e43005ba5d89ebb8124f956/src/data/community/events.json)) to store event data & build a simple component that can filter out past events based on the `date` field

**Describe alternatives you've considered**
None

**Additional context**
We discussed this in https://github.com/ethereum/ethereum-org-website/pull/1763

Example JSON data file:
https://github.com/wackerow/ethereum-org-website/blob/9e8c6214cb2acf001e43005ba5d89ebb8124f956/src/data/community/events.json

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by Robiquet** [comment]
Looks interesting, I'd like to help out

**Comment by wackerow** [comment]
@Robiquet Can assign to you =) As Sam noted, I have done some work on this in the past as a whole community page revamp that overall has been scraped, but it does contain code that can be used for this.
https://github.com/wackerow/ethereum-org-website/blob/9e8c6214cb2acf001e43005ba5d89ebb8124f956/src/pages-conditional/community.js
This was a new version of the page using JavaScript (instead of markdown), and has some logic that could help here around [Line 377](https://github.com/wackerow/ethereum-org-website/blob/9e8c6214cb2acf001e43005ba5d89ebb8124f956/src/pages-conditional/community.js#L377)... 
Of course our `/community` page now is still markdown (not javascript as in my alternate version)... I would suggest extracting the events data into it's own JSON file in the data folder, then make an `Events` react component that imports this data and displays it, then import that component into the markdown template and add something like `<Events />` in the `community/index.md` file in replace of the current events listing. 

Let us know if you have questions! =)
