### ISSUE TITLE
Nodes and clients sync strategies content

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/ethereum-org-website#3219]
Realised when approving this PR that our documentation doesn't do a good job of explaining the different syncing strategies available with each client. We discuss different types of node: full, light, archive but nowhere do we delve into the different strategies. They're not always intuitively named either... Geth's 'snap' and Trinity's 'Beam' are good examples of confusing nomenclature. 

I propose we add a section that explains each strategy and why you might want to use said strategy...

**Comment by ryancreatescopy** [comment]
@taxmeifyoucan you've been so generous with your contributions to this section already but maybe you can help or recommend someone that can?

**Comment by taxmeifyoucan** [comment]
Thanks for pointing this out @ryancreatescopy! When I wrote the original article on clients, I did not include explanation of all different sync strategies because each implementation uses at least slightly different approach and I found overwhelming to explain all details. 
However I would be glad to look in to that, I could write Sync strategies section during next week or so.

**Comment by minimalsm** [comment]
Hey @taxmeifyoucan 😀

Are you still able to have a look into this? No pressure if you don't have the bandwidth to look into it just now - I can open it back up to the community ✌️

**Comment by taxmeifyoucan** [comment]
Still available, sorry for delay. Thanks for ping @minimalsm

**Comment by minimalsm** [comment]
@taxmeifyoucan woo thanks 😬 I've assigned you.

**Comment by minimalsm** [comment]
Closed in #3885
