### ISSUE TITLE
Site Translation: Update German to v2.32

### ISSUE THREAD

**Issue by redtux** [ethereum/ethereum-org-website#3490]
The German language translations are more than outdated and need to be updated/created.

**Some examples:**

1. https://ethereum.org/de/community/
2. https://ethereum.org/de/developers/docs/
3. https://ethereum.org/de/glossary/
4. https://ethereum.org/de/community/grants/
5. https://ethereum.org/de/history/
6. https://ethereum.org/de/learn/

The last update is over a year old (v1.1; see #822)

I will start contributing in crowdin and propose PRs for the above sites. Coordination with other contributors can happen here or on discord.

**Comment by lukassim** [comment]
Hi @redtux, thanks for reaching out and helping us translate the website.

Please note a lot of the pages you mentioned above are part of version 2.1 in Crowdin. These pages will get reviewed and added to the site once the entire version is translated, since we do not review and implement pages on an individual basis. There is no need to create PRs for individual translated pages.

The website also currently supports German v2.0, which was added with this PR for German 2.0 language support from March this year:
https://github.com/ethereum/ethereum-org-website/pull/2710

If you have any other questions or feedback, please feel free to get in touch here or on Discord.
I will close this issue for now and will create a new issue to add v2.1 once that is completed.
