### ISSUE TITLE
Create "Ethereum governance" page

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#3640]
**Is your feature request related to a problem? Please describe.**

"How does Ethereum governance work?" is a common question from people new to the space.

e.g. this recent question: https://discord.com/channels/714888181740339261/776139785550168084/875295983519563776
Shows the misunderstanding re: token votes on changes.

e.g. another question: https://discord.com/channels/714888181740339261/776139785550168084/866873390588887072

**Describe the solution you'd like**

Putting this into writing is a bit tricky given how arguably messy/unstructured governance on Ethereum is but I think it would still be helpful to create a page that explains how changes to Ethereum happen at a high level & links to resources (e.g. like ethresear.ch, ACD call notes & eips.ethereum.org) so folks understand where the discourse & decisions happen.

**Additional context**

Podcast w/ Tim Beiko covering this topic:
https://open.spotify.com/episode/72NQ6fsLKJA8FC5tqQ16pd?si=C9zxMlYASD2BA3UZJB2gSg

A few community articles that attempt to explain this:
- https://medium.com/coinmonks/how-ethereum-governance-works-71856426b63a
- https://cryptotesters.com/blog/ethereum-governance
- https://docs.ethhub.io/ethereum-basics/governance/

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by minimalsm** [comment]
I'll take a shot at this.

**Comment by timbeiko** [comment]
Agreed this is a good idea! Happy to review a PR to share my thoughts. It is messy and changing, but we can probably do better than "nothing" :-)

**Comment by minimalsm** [comment]
@timbeiko If you have the capacity for it you can feel free to take this one? You definitely would have a better mental model than I do. 

If not, I'll send it your way after 😀👍

**Comment by timbeiko** [comment]
@minimalsm would it be helpful if I write down some thoughts in a simple .md document to help you content-wise? The most time consuming bit for me doing this is probably actually making it "ethereum.org-friendly", and I suspect the inverse is true of you. I can put something together tomorrow as a first pass if that helps :+1:

**Comment by minimalsm** [comment]
That would be very helpful @timbeiko, thanks 😊.

**Comment by timbeiko** [comment]
@minimalsm here's a rough draft: https://hackmd.io/@timbeiko/eth-governance

Please feel free to edit heavily, and LMK if you feel like anything is missing. This feels like more of a starting point than a final work 😅

**Comment by timbeiko** [comment]
Would also be good to get this sanity-checked by @djrtwo, @tvanepps, @poojaranjan and/or @Souptacular 😄

**Comment by tvanepps** [comment]
Looks good! Just added some comments on the doc for typos / clarity

**Comment by poojaranjan** [comment]
The draft https://hackmd.io/@timbeiko/eth-governance looks like a good high-level explainer of how to proceed with a "core proposal", which I think people are generally interested in understanding and often refer to as "Governance in Ethereum". 

My two cents:
I would use "EIP Author(s)" until a proposal is merged as "Draft" and even after that if pursued for a future network upgrade by one of the co-authors. Also, because "EIP Author" is the commonly used term in the EIP-1. IMO, an "EIP Champion" is needed for shepherding the proposal when none of the original author(s) listed on the proposal is available to represent the EIP.   

I do see the role of "EIP Editor(s)" as the stakeholders, as they help a proposal document as a standard for Etherum blockchain. 

(Left some comments on the draft as per my understanding of the process, feel free to ignore/rephrase it.)
