### ISSUE TITLE
Maintenance of the Whitepaper

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#3794]
**Is your feature request related to a problem? Please describe.**

We recently received a PR (#3435) to update a section of the Whitepaper to make it easier to read. [Our initial reaction](https://github.com/ethereum/ethereum-org-website/pull/3435#issuecomment-890262087) was that the Whitepaper should be kept as-is for historical and reference purposes. However, after some digging it seems that we are [not actually hosting the original](https://github.com/ethereum/ethereum-org-website/pull/3435#issuecomment-890269296).

We've since received another PR (#3763) to update the bitcoin block reward from 12.5 BTC to 6.25 BTC. Again, [our hosted version](https://github.com/ethereum/ethereum-org-website/blob/dev/src/content/whitepaper/index.md#mining-mining) has already been updated to account for the 2016 Bitcoin halving (25 BTC to 12.5 BTC).

Another contributor [raised an issue](https://github.com/ethereum/ethereum-org-website/issues/3768) that the Whitepaper is difficult to cite academically noting:

> As new academic attention comes to Ethereum we need to sort this situation out as it will have recursive effects down the years as the citations become more compounded. I think it looks a bit unprofessional and makes life needlessly difficult for those trying to study us.

Their suggested solution:

> an official website version of the Ethereum whitepaper with pagination and available as a PDF.

**Describe the solution you'd like**

- We should merge the two existing PRs (#3435, #3763)
- We should accept sensible PRs in the future (e.g. updating a typo, updating outdated figures) 
- We should create a blurb on the whitepaper page explaining that this version is not the original but is maintained and kept up-to-date by the community 
- We should find the original published version of the whitepaper
- We should link to the original whitepaper in this blurb (to be hosted on ethereum.org)
- The original PDF version should be properly paginated for referencing purposes

**Describe alternatives you've considered**
- Revert the whitepaper to the original and reject all future PRs

**Want to contribute?**

We love contributions from the Ethereum community! We won't be accepting PRs for this but please feel free to weigh in and get involved in the discussion.

**Comment by agorismlabs** [comment]
I believe we should **not** be altering or updating a historical document. I think your original intuition was correct. 

Meddling with a document of potentially significant historical importance seems unwise. 

I propose we instead prioritise finding out which is the original whitepaper and when it was originally published. This should be a question answered directly by Vitalik or someone close enough to verify what actually constitutes the original whitepaper. 

When the correct paper is found it should be hosted as a PDF with pagination. This will allow it to be referenced by interested parties, e.g. academics intending to cite the white paper. There is no need for a webpage version. It offers no benefit over a properly paginated and citable document. 

On the page where the PDF is hosted there should be a short contextual blurb explaining when the whitepaper was published, any versions that have followed, and maybe a little bit of history. 

After that a canonical document like this should **never** change from the original. The same way we would never change Satoshi's whitepaper. Not because it's some otherworldly document, but in order to _preserve history_ for future generations.

**Comment by samajammin** [comment]
Agreed, I think hosting the historical, untampered whitepaper as a PDF makes sense for the reasons outlined above.

We've checked in with @vbuterin on this:
> I would say revert it to the version as it was at the time of the ether sale and keep that permanent

Vitalik's take lines up with the approach you've outlined @minimalsm. I think a fun historical research task for you is to find the version as it was at the time of the ether sale 😄

**Comment by samajammin** [comment]
One separate consideration - what should we do with the existing whitepaper page (https://ethereum.org/en/whitepaper/)?

Options:
1. Remove it & add a redirect from page to where the PDF will live (e.g. https://ethereum.org/en/whitepaper.pdf)
2. Keep it as an editable version so it becomes more of a living document that's also more approachable by a broader audience

I don't have a strong opinion here. Having both might lead to some confusion. Alternatively, it might be nice to have both the original "as-is" in PDF format for posterity & perhaps an updated fork / community version that is more accessible could be goo. The [Beige Paper](https://github.com/chronaeon/beigepaper) was a great effort in this direction for the [Yellow Paper](https://ethereum.github.io/yellowpaper/paper.pdf). So maybe something similar :thinking:?

I welcome input from folks on this!

**Comment by jjmstark** [comment]
For the sections of the whitepaper that have been "updated" by edits over the years - to what extent is that content already reproduced elsewhere, e.g. in the [docs?](https://ethereum.org/en/developers/docs/).

I agree that having "two whitepapers" would be confusing to readers. I do think that most people's expectation when reading the "Ethereum whitepaper" is that it will be a version of a document that existed in a specific point of time, rather than a living set of documentation about the Ethereum protocol. If something changes, and there needs to be up-to-date documentation about some technical concept or feature, isn't it better for people to update the docs, rather than the docs *and* the whitepaper?

**Comment by agorismlabs** [comment]
'I would say revert it to the version as it was at the time of the ether sale and keep that permanent.'

This is quite clear from Buterin to my mind. No meddling with the document or any living document approach. This is not really what you do with a historical document like this. It is really important we realise we need a single source document that does not change and reflects the whitepaper as it was at launch. 

Regarding the old page just remove it. We don't want two versions. Like a blockchain we should be aiming for a single source of truth. 

This mindset of playing around with the whitepaper by editing it and updating is something I would strongly discourage. It will have unintended consequences throughout the future as people try to figure out what was the case at different points in time depending on edits (whose origins may be lost to time themselves). 

Single whitepaper, PDF, pagination, blurb explaining the context. No competing or complicated alternatives to confuse newcomers, academics, future historians.

**Comment by minimalsm** [comment]
> Remove it & add a redirect from page to where the PDF will live (e.g. https://ethereum.org/en/whitepaper.pdf)

> Regarding the old page just remove it. We don't want two versions. Like a blockchain we should be aiming for a single source of truth.

I'd strongly oppose **only** linking to a PDF version as it would be bad accessibility, inclusivity and general UX. If we choose to revert to the ether sale version (which is a fine solution) I think we should mirror the PDF content on the [whitepaper page](https://ethereum.org/en/whitepaper/) itself.


@samajammin we also currently translate the Whitepaper which is something we need to think about if we do choose to revert it.

**Comment by agorismlabs** [comment]
@minimalsm Oh yes, I definitely would mean a mirrored version and not just a PDF, for the reasons you state.

**Comment by minimalsm** [comment]
Seems the options are: 

- Continue to accept sensible contributions to the Whitepaper and maintain a separate PDF version of the original
- Revert to the original and reject all future changes to the whitepaper.
 
Either way, given that the Whitepaper we're hosting is **not the original** I don't see any harm in merging #3435 and #3763 until we have a definitive answer.

**Comment by jpitts** [comment]
Two things: 1. the White Paper needs to have a version and 2. there needs to be a decision about whether to keep this as a historical piece or as a living document.

Unless the WP is clearly positioned as history, users (particularly new people to the community) would expect to see the current white paper of Ethereum protocol. Beyond the technical proposals it contains, the WP is actually a very important vision document. It can continue to be that, even if kept in a "glass case". 

I would want it to be kept alive and current, but like the Yellow Paper it needs to be maintained, in sync with the actual evolving protocol. Changes include EIP-1559, the emergence of the Beacon Chain (formerly known as Eth2), and the very big changes ahead involved with The Merge.

Either way, I would suggest versioning the white paper, hosting the most recent version on the convenient URL used, but also having a list of important older versions. PDFs would be great too, especially if ones can be found for the early format.

**Comment by agorismlabs** [comment]
I think the whitepaper **is** history and needs to be recognised as such. We don't change Satoshi's whitepaper, so we are we changing Vitalik's?

I actually suspect new users will be confused to discover there are many versions of the whitepaper and that information is updated. In fact, we are denying them knowledge that things were different in the past by subtly changing parameters to current standards. 

I think it is actually more confusing to be presented with multiple, evolving whitepapers than just 'this is the original whitepaper' (like in Bitcoin). 

We already have plenty of resources on the changes to Ethereum since its creation: https://ethereum.org/en/learn/ Let users discover the whitepaper and then build their knowledge from there, like they would in any other similar protocol.

**Comment by minimalsm** [comment]
After much consideration we have decided two outcomes here.

1. We will revert the whitepaper to the original (post-ether sale)
2. We will provide a PDF version of the original as an academic reference and single source of truth.

Thank you all for your input on this 😬👍

**Comment by minimalsm** [comment]
Closing this out as per #5372 

Thanks @polarpunklabs ❤️❤️❤️
