### ISSUE TITLE
Update/remove Eth2 banners

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#3806]
**Is your feature request related to a problem? Please describe.**

This banner content feels a bit strange:
![The Eth2 upgrades ethereum org 2021-09-02 at 11 40 43 PM](https://user-images.githubusercontent.com/8097623/131961707-0d6e26b0-94e5-4a17-9ced-cbfc05b9c9da.jpg)

"It will probably happen earlier than expected" feels weird & confusing. When is "expected"?

**Describe the solution you'd like**

Now that it's been months since the roadmap has solidified around the merge taking place before sharding, I think we can remove this banner entirely. We explain the timing of events on each of the specific upgrade pages.

Should we also include callouts to Danny & Ben's updates on those specific upgrade pages (like we do with the banner link)? These are likely the most reliable ways to get up to date info. 
e.g. we could add the same section as the Eth2 homepage:
![The Eth2 upgrades ethereum org 2021-09-02 at 11 45 01 PM](https://user-images.githubusercontent.com/8097623/131962285-a6e4243e-4aa6-4203-ab21-a1acaa52f591.jpg)

**Describe alternatives you've considered**

We could update the banner copy to something more straightforward.

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by minimalsm** [comment]
Agreed. Pretty sure this was updated in April when everyone got excited about the possibility of the merge happening in 2021 but in reality it is likely to happen either when we expected or later than we expected (if delayed) - both relative to general expectations at the beginning of 2021...

**Comment by notrixbe** [comment]
maybe some idea's, in my experience this kind of informing is working well for the users. Because there can decide ignore it or click on it for more info.
- put the banner above the navigation ( so you don't have the issue with the dropdowns ) 
- it can be fixed
- 100% width ?
- make the banner more like coinmarketcap on the top, lot smaller. 
- then we can add small optimizations ( animations, ticker, ....)

Let me know what your thoughts are.
Maybe i can help with it.
