### ISSUE TITLE
i cant suggest one thing not one 

### ISSUE THREAD

**Issue by hastings8** [ethereum/ethereum-org-website#3840]
im sick of yall bending me over , its  rape no lube nothing , ive lost 1000s  due to the gas and eth fees, its bullshit! sell bep20 coin they charge .13 cents sell some eth alt coin and your paying double the value of the cion in fees its  a gd joke! and why are yall so liked???? please explain that one to me ??? becausae yall are a  bunch of crooks if you ask me stealing honest peoples money , hell have a transaction error guess what they keep your moiney for therefuck up   fuck ETHEREUM!

**Comment by jley81** [comment]
> im sick of yall bending me over , its rape no lube nothing , ive lost 1000s due to the gas and eth fees, its bullshit! sell bep20 coin they charge .13 cents sell some eth alt coin and your paying double the value of the cion in fees its a gd joke! and why are yall so liked???? please explain that one to me ??? becausae yall are a bunch of crooks if you ask me stealing honest peoples money , hell have a transaction error guess what they keep your moiney for therefuck up fuck ETHEREUM!

Hello hasting8.  I'm jerry Louis. I do apologize for the ???? And therefuck ups.  To be honest, I have no idea what I am doing. Hell no one can help me because I'm the one who created it and don't remember how or why. That fucking sucks. But I can tell you everything that is of this world.  The sooner I can find someone who can actually understand what I know, the sooner heaven will be here on earth. Want to talk but no one will listen.  Ethereum was created for endless energy. Knowledge. Free as God intended.  But all are so brained washed that it's literally me waiting.
