### ISSUE TITLE
Rethink Learn section of Navbar

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#3984]
**Is your feature request related to a problem? Please describe.**

The number of links in the 'Learn' section of the main navigation is outgrowing the initial design. 

<img width="1505" alt="Screenshot 2021-09-22 at 14 17 06" src="https://user-images.githubusercontent.com/62268199/134351050-59ba5f14-1d74-4cb9-a0b5-66681044c0ef.png">

This looks fine for now but very soon we'll be adding 3-4 new pages. Aesthetically this doesn't look great but also runs into [Hick's Law problems](https://lawsofux.com/hicks-law/) - reducing the likelihood users will find the information they are looking for and reducing the user experience.

<img width="1500" alt="Screenshot 2021-09-22 at 14 19 25" src="https://user-images.githubusercontent.com/62268199/134351262-de03b647-247f-48b7-8203-4dcbd09cbc2d.png">

**Describe the solution you'd like**

Open to suggestions. Just wanted to highlight this issue.

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by MrBrain295** [comment]
Maybe a more button that could show the rest?

**Comment by vj-codes** [comment]
@minimalsm hey can this be a hacktoberfest issue?

**Comment by Courtney266** [comment]
hello

**Comment by Vishnurr2k01** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> The number of links in the 'Learn' section of the main navigation is outgrowing the initial design.
> 
> <img alt="Screenshot 2021-09-22 at 14 17 06" width="1505" src="https://user-images.githubusercontent.com/62268199/134351050-59ba5f14-1d74-4cb9-a0b5-66681044c0ef.png">
> 
> This looks fine for now but very soon we'll be adding 3-4 new pages. Aesthetically this doesn't look great but also runs into [Hick's Law problems](https://lawsofux.com/hicks-law/) - reducing the likelihood users will find the information they are looking for and reducing the user experience.
> 
> <img alt="Screenshot 2021-09-22 at 14 19 25" width="1500" src="https://user-images.githubusercontent.com/62268199/134351262-de03b647-247f-48b7-8203-4dcbd09cbc2d.png">
> 
> **Describe the solution you'd like**
> 
> Open to suggestions. Just wanted to highlight this issue.
> 
> **Want to contribute?**
> 
> We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

adding a scroll ?

**Comment by minimalsm** [comment]
Hey everyone. This issue requires design before being worked on (i.e. if you have a proposal feel free to comment here). Some sort of re-organization of the navbars is probably required for this.

**Comment by SNikhill** [comment]
@minimalsm 

I shall like to propose a design inspired by this Nav from Revolut.
![image](https://user-images.githubusercontent.com/51415616/135893727-18e5ba14-259d-4aff-aa77-b4054aad25e0.png)

Especially, those curved borders.

**Comment by samajammin** [comment]
Marking this as blocked - I think we should re-think this as part of an overhaul of the learn page more broadly:
https://ethereum.org/en/learn/

My gut take as of now is we can build out a landing page for the Learn section of the site that acts as a hub & provides a hierarchy of topics & subpages, similar to how we have the "[Developers' Home](https://ethereum.org/en/developers/)" within the "Developers" dropdown menu.

**Comment by samajammin** [comment]
Noting this is also a bug on smaller browsers - the dropdown nav is cut off with no ability to scroll:

https://user-images.githubusercontent.com/8097623/141985359-f73ebbc0-7a9f-4711-b519-407e7d965eeb.mp4

@minimalsm perhaps a short term fix would be to remove some of these pages from the dropdown? e.g. I think at least these could be removed - they're less important pages & are linked to from the footer & elsewhere:
- Ethereum Glossary
- Community guides and resources
- Ethereum Improvement Proposals

**Comment by aguscruiz** [comment]
I have a proposal for the design. Here are my thoughts:

- The dropdown could be divided into sections, I divided here in the mock but I may not be correct on the division criteria (that's open to discussion obviously).
- We could only list the "most useful" learn articles at the dropdown, and have a "browse all topics" at the bottom to link to a Learn landing page with every article listed.
- I added a bit more whitespace to the dropdown items, specially with regards to the dropdown border, it felt too cramped.
- Also added a subtle drop shadow to elevate the dropdown a bit.

### Learn section

![image](https://user-images.githubusercontent.com/15734630/145264038-e2b339a9-9bfc-4110-b242-5db7a58c135c.png)

### Another nav dropdown

![image](https://user-images.githubusercontent.com/15734630/145264683-0f96c035-cdd4-44db-95bd-3ece1034bdde.png)

**Comment by aguscruiz** [comment]
@minimalsm thoughts?

**Comment by samajammin** [comment]
Thanks for the suggestion @aguscruiz! I like your proposal 😄

**Comment by samajammin** [comment]
Multiple folks have also reported this in Discord:
- https://discord.com/channels/714888181740339261/727898649006309377/949382094029717524
- https://discord.com/channels/714888181740339261/727898649006309377/949698900384677898

**Comment by maxgeor** [comment]
Quick win would be properly grouping and nesting different ideas. Since this tab is about _learning_, it makes snes eto group ideas into Basic and Advanced (people shouldn't read "Blockchain Bridges" before "What's ETH?"). Here's one grouping:

Learn
- **Basics**
  - What’s Ethereum?
    - Ether (ETH)
    - Smart contracts
    - History of Ethereum
    - Ethereum upgrades
    - Ethereum Whitepaper
  - DeFI (Decentralized finance)
  - DAOs (Decentralized autonomous organisations)
  - NFTs (Non-fungible tokens)
  - Web3 
- **Advanced**
  - Ethereum governance
  - Blockchain bridges
  - Ethereum energy consumption
  - Ethereum Improvement Proposals 
  - Ethereum security and scam prevention
- **More** (this one doesn't need a label)
  - Ethereum glossary
  - Community guides and resources

Then you can lay out the nav horizontally, which each section next to eachother to save on vertical space:

**Learn**
    `Basics`  `Advanced`  `More`

# Mobile
The site has a pretty hefty nav overall. For mobile, it makes sense to ditch the typical pop-out list and for a mega nav overlay. it would have 2 columns to save vertical space.

**Comment by samajammin** [comment]
Assigning to @konopkja 😄

**Comment by DaveyD233** [comment]
The problem is NOT the Hysterium of ETHERIUM being #blocked, more than the #number#s of "POSSIBLE Ethereum 1&2.0 tokens", according to CoinBase, RISING 100k (IN BOTH ETH1&2.0) tokens since the BEGINNING of this year(ie. 120million ETH 1&2.0 tokens available, ON January 2022, to 120.1 ETH1&2.0 tokens IN February 2022, to NOW; Where CoinBase is showing there ARE 120.8Million ETH1&2.0 tokens PRESENTLY, May 2022, EQUALLING "121.6 TOTAL ETH1&2.0 tokens" Today, Though Eth 2.0 is STILL Not even available to use!? 
     Appearing as if ETHERIUM 2.0 is EQUALLY being "staked" is a Major Mining&Proof-Of-Stake RIP-OFF! Not only that, the increase of NOW 1.8MILLION MORE of Both ETHERIUMS 1&2.0, is MAKING MY Current ETHERIUM 1 tokens DEPRECIATE in value ALSO!! 
     ADDING TWICE AS MANY tokens to "Balance out"_"APPEAR" as if ETH1&2.0 ARE Equal, while the "staked" ETH2.0 CAN'T Even be Touched, is the BIGGEST RIP OFF I HAVE EVER SEEN IN MY ENTIRE LIFE(lol next to Blu-ray, merely ENHANCING the Color MORE, to "appear" better than HD 🙂)! 
     WHO KEEPS ADDING THESE "NEW TOKENS" that @CoinBase is reporting, FOR BOTH ETHERIUM 1&2.0?! Because whomever is the "Extra Tokens Adder," is Not Only DEPRECIATING the VALUE of BOTH ETHERIUMS 1&2.0, but putting these "Mysteriously Added $1.6MILLION New Eth 1&2.0 tokens" in their OWN pockets(ie. Vitalik Buterin's "Custom Oil Painting" of Himself, for his Twitter Photo), while the REST OF US Have to just WATCH, as the #Number#s of ETHERIUMS 1&2.0 tokens KEEP going UP(while also watching the prices keep going DOWN) in the process! 
     Dehumanizing others because of COLA(Cost Of Living Adjustment) going UP 5.9%(the Highest since 1981, when the World Wide Web came out), just to Maintain their Rich Living Lifestyle (#Greedily) was NOT what Ethereum was Originally invented For, nor originally "All About"! It's a Community Currency, which iss now seeming to become the greedy bank-like/centralized architecture the Whole Idea of Ethereum was AGAINST to start with! Ethereum Cant survive without BitCoin, and Vise Versa too!
   Let's ALSO please Keep in mind that Public Service Providers, HERE IN the USA(&Other countries), HAVE been starting 2B Paid for by BitCoin &transfered through ETHERIUM, to $$$$! iSalute Ethereum for the Main Mission Statement's ideal of "promoting the general welfare,to ENSURE Domestic Tranquility"!,but ADDING MORE TOKENS to Both ETHERIUMS 1&2.0 Diviates THAT ENTIRE MO(Modus Operandi) of said "Mission Statement" while Also doing the SAME "for" the Communities, that CryptoCurrency was designed for to begin with!

Thank you for your time, 
CAPT David Simonton-Valento, O-3_USAF, AAS, BT-BAS, Sap-Certification

**Comment by corwintines** [comment]
@minimalsm @konopkja I imagine this can be closed now.

**Comment by samajammin** [comment]
Solved in https://github.com/ethereum/ethereum-org-website/pull/6778 - thanks @konopkja & @pettinarip!
