### ISSUE TITLE
Alternatives to current headline

### ISSUE THREAD

**Issue by vbuterin** [ethereum/ethereum-org-website#40]
**Current:** "Ethereum is a global, decentralized platform for money and new kinds of applications. On Ethereum, you can write code that controls money, and build applications accessible anywhere in the world."

**Problems with current**:

* Fails to mention what's different about these applications compared to web apps
* Over-emphasizes money

**Alternative proposals**

* Ethereum is a global, decentralized platform for building applications that are secure, can operate without a central administrator and are highly robust against third-party interference.
* Ethereum is an open-source, decentralized platform for building applications that run exactly as programmed and are highly resilient against faults and third-party interference. 
* Ethereum is a global open-source platform for building decentralized applications and economic mechanisms. Applications on Ethereum are executed in a massively replicated public ledger that allows anyone to verify that computations are being executed correctly, and ensures a high level of fault tolerance and robustness.
* Ethereum is a permissionless open-source platform for building decentralized applications and economic mechanisms. Applications on Ethereum are executed in a massively replicated public ledger that guarantees that code is being executed exactly as written, without relying on a central administrator to remain online or honest, and can be accessed from anywhere in the world.
* Ethereum is a global, decentralized platform specially designed for building applications that need strong guarantees of liveness and protection against tampering or interference. Once an application on Ethereum is launched, it will continue running without requiring any central administrator, and the application can be accessed or verified from anywhere in the world.
* Ethereum is an open-source, public blockchain-based platform for running distributed applications that demand high guarantees of security and robustness against tampering or faults. On Ethereum you can build applications that handle digital assets, implement economic mechanisms and markets, and timestamp and create tamper-proof logs of critical data, along with many other use cases being developed each month.

Not meant to be the end-all, just some starting points. IMO if we want to mention money, we need to mention at least one thing that is not money too; and for a two-sentence intro that may not be appropriate.

Some ideas above have been partially plagiarized from:

* The previous Ethereum website
* EthHub: https://docs.ethhub.io/ethereum-basics/what-is-ethereum/
* Wikipedia

**Comment by jjmstark** [comment]
One important goal of the "headline" text is that it is comprehensible and useful to a wide variety of users. The landing page is the "top of the funnel" where a user arrives before opening a sub-page on a specific topic area. We might even assume that the landing page will **mostly** be used by "beginners", because a knowledgeable user is more likely to go directly to a sub-page than to the landing page itself. 

For that reason, I think many of the examples above are not appropriate for the landing page (though they are good explanations that could go somewhere else). Phrases like "resilient against faults", "massively replicated ledger", "guarantees of strong liveness", "tamper proof logs" etc. might be accurate descriptions of Ethereum's technical characteristics, but they are not helpful for the majority of people who encounter this page for the first time. 

Another consideration is that the headline text must be concise, two short sentences at most.

**Alternative proposals**:

First sentence:
- Ethereum is a global, open-source platform for decentralized applications. 
- Ethereum is a global, open-source platform for money and decentralized applications.
- Ethereum is a global, open-source platform for digital value and decentralized applications. 

Second sentence:
- On Ethereum you can write code that controls money and ship unstoppable software. 
- On Ethereum, your code always runs as programmed, and can control new kinds of money and digital value.
- On Ethereum, your code can do more. Build unstoppable applications, control money, and change the world.
- On Ethereum, your code has superpowers: it can control and create money, always runs as programmed, and can't be interfered with.

**Comment by vbuterin** [comment]
That's a good point! This is definitely a hard balancing game. So far my favorite would be:

Ethereum is a global, open-source platform for decentralized applications. Ethereum, you can build applications that control digital value, run exactly as programmed, and are accessible anywhere in the world.

**Comment by HansF** [comment]
Here's my remix : 

Ethereum is a global, open-source platform for decentralized applications. Build unstoppable apps that run exactly as programmed. Exchange value and track transactions around the world without the need for a trusted third party.

**Comment by jarradh** [comment]
Whether or not this impacts the headline, perhaps this is an opportunity to get clarity on the (EF's) mission/ideal, separate from what Ethereum implementation actually is?

Being a 'close outsider' to the EF I get the sense the current approach towards the mission of a decentralized application platform is to be more horizontally integrated, while EF focuses on the blockchain, rather than a focus on being vertically integrated/all-in one platform (providing decentralized storage and messaging), which seemed to be the case in the past.

In this case the EF's mission is provide a platform for decentralised application, and Ethereum is analogous to the Linux _kernel_,  the separation might be a moot point as far as communication to a general audience goes (GNU/Linux is referred to as just Linux).

What I like about clarifying this distinction is that it would allow the EF to reduce their scope while at the same time supporting a more heterogeneous ecosystem, Ethereum is the 'cpu' in different architectures, whether compositions use IPFS/Swarm/SSB/Matrix/Whisper/Yin/etc.

**Comment by jjmstark** [comment]
Hey Jarrad - there are plans to update https://ethereum.foundation/ in the near future with this information. The idea is that there will be a clean distinction between ethereum.org (about Ethereum) and ethereum.foundation (about the EF).

**Comment by goldfarbas** [comment]
Piggybacking off @jjmstark's points, it's important that a headline explain why your subject matters because it's easier for people to relate to your reason for doing something than whatever thing you may be doing or showing off. Take "I'm biking" versus "I'm biking for charity" as an example - even if you don't bike, you probably like the idea of wanting to help others and will be inclined to feel something for the person biking for charity.

Regarding the "money" problem, I lean against mentioning it but I see just as much potential around #DeIP as #DeFi so if we talk about money then it's also necessary to talk about intellectual capital.

**Alternative Proposals**
- Ethereum is a global, open-source platform for launching unstoppable software.
- Ethereum is a global, open-source platform for launching decentralized applications that run exactly as programmed and remain accessible from anywhere in the world.
- Ethereum is a global, open-source platform for launching decentralized applications that create and control financial and intellectual capital.
- Ethereum is a global, open-source platform for launching decentralized applications that manage financial and intellectual capital.

**Comment by EvanVanNessEth** [comment]
I've been thinking about this and I think the strength (and occasionally the weakness) of Ethereum is that decentralization means that Ethereum is many things to different people.   Trying to put a blanket definition on that is relatively futile.  

I'd propose instead copy that is something like:

As a decentralized open-source project, Ethereum is whatever its community makes it.  Here are a few different definitions from people in the Ethereum community:

1.  the blockchain securing the "Ether" cryptocurrency and the Ethereum Virtual Machine (EVM)
2.  the backbone of web3
3.  the native value transfer layer of the Internet
4.  programmable money
5.  a platform for decentralized software applications

**Comment by EvanVanNessEth** [comment]
If we value pithy, I suggest an alternate version of one of @vbuterin's proffered taglines. 

"Ethereum is an open-source platform for decentralized applications. 

Using Ethereum, you can build [censorship-resistant] applications with a native value transfer that run exactly as programmed and can be accessed from anywhere in the world"

**Comment by HansF** [comment]
So... how do we proceed? I see several good headlines here... how do we make the change? 
Do we create pull requests for different proposals? Will we encourage the use of reactions to implement rudimentary voting? 

 cc: @jjmstark ?

**Comment by jjmstark** [comment]
@HansF for now we'll go with a slight variation on @vbuterin's last suggestion:

>Ethereum is a global, open-source platform for decentralized applications. On Ethereum, you can write code that controls digital value, runs exactly as programmed, and is accessible anywhere in the world.

I'll add a PR to make the change, and close this issue for now. Obviously can still be tweaked in the future, but we're going to push some changes tomorrow so let's take this iteration for now.
