### ISSUE TITLE
Images to break up the text on etherem.org/beginners

### ISSUE THREAD

**Issue by jjmstark** [ethereum/ethereum-org-website#43]
Right now the [Beginners](https://ethereum.org/beginners/) page is very sparse and text-heavy. This page is targeted at people who are entirely new to Ethereum, but it's an intimidating wall of text.

One way to improve this would be to add images to break up sections of text. Examples that could be useful:
- Photos from Ethereum events showing our large community
- Images that show or represent the Ethereum network (e.g. distribution of nodes around the world?)
- Graphics or infographics displaying information about Ethereum
- Simple graphical explanations of concepts in this text (e.g. "decentralized")
- Live graphical "widgets" showing network statistics?

**Comment by samajammin** [comment]
I'm on board with these ideas. We're in the midst of some user persona research which may impact the site content structure, so we'll circle back to this once that's complete.

**Comment by samajammin** [comment]
Coming out of the user persona research, it seems this page will stay as-is... just renamed from /beginners to /what-is-ethereum, so I believe this issue is still relevant.

@jjmstark perhaps this issue is a cause for an overall re-think of this page content? Might be worth evaluating the page holistically vs. merely deciding what images to add & how to add them. For instance, all 3 YouTube videos at the bottom of the page are TechCrunch videos. Is that really the way we should be introducing the world such a diverse & multifaceted platform, ecosystem & community?

Perhaps we circle back on this once the community page (#269) is out the door. As always, we welcome ideas on this!

**Comment by samajammin** [comment]
Reopening.

**Comment by samajammin** [comment]
Solved (at last!) in #1181
