### ISSUE TITLE
Missing Avatar and Invalid DateTime in Docs

### ISSUE THREAD

**Issue by prakhar1144** [ethereum/ethereum-org-website#4784]
**Describe the bug**

1. We have a missing avatar 
2. Last Edit date also shows **Invalid Datetime**

**To Reproduce**

1. Go to https://ethereum.org/en/developers/docs/dapps/
2. Just after the title **INTRODUCTION TO DAPPS**

**Screenshots**

![Screenshot from 2021-12-15 14-16-51](https://user-images.githubusercontent.com/56781761/146157973-66065bec-0552-41b4-8957-68172dab7148.png)

**Desktop:**

- OS: [Ubuntu 20.04.3 LTS]
- Browser: [Firefox]
- Version: [95.0 (64-bit)]

**Comment by prakhar1144** [comment]
I would like to work on this issue.
Please Assign.

**Comment by minimalsm** [comment]
Hey @prakhar1144 thanks for the report. Unfortunately, this is something that can only be debugged using our production servers. We think we have a solid fix for this and should be pushing it out later today 🥰

**Comment by wackerow** [comment]
Note this issue was filed under #4710 and patched in #4763. 

Unfortunately in the meantime, something is causing a bug on the homepage now, but the core issue of why the contributor data was not being fetched has been solved (`relativePath` was including `__dirname` at the beginning which included a second `src` folder).

**Comment by prakhar1144** [comment]
As mentioned earlier by [minimalsm](https://github.com/ethereum/ethereum-org-website/issues/4784#issuecomment-994688881), this issue is now fixed.
