### ISSUE TITLE
Bug: H3 ::before pseudo-element is preventing click interation with the elements above.

### ISSUE THREAD

**Issue by evertonfraga** [ethereum/ethereum-org-website#4793]
Hello! 

H3 element has a pseudo-element (::before) with negative margin top, which prevents clicking on links within that range of 120px.

A quick fix would be to use `pointer-events: none` on that pseudo-element, but I'd chase a cleaner solution.

**To Reproduce**

1. Go to https://ethereum.org/en/dao/
1. Try to click on a link right before a H3 element. 

**Expected behavior**

**Screenshots**

<img width="1017" alt="Screen Shot 2021-12-15 at 11 30 46 PM" src="https://user-images.githubusercontent.com/47108/146303725-582e8641-b866-416e-8686-daacf700758a.png">

**Desktop (please complete the following information):**

- OS: MacOS

**Comment by minimalsm** [comment]
Thanks for raising this @evertonfraga :-) would you like to tackle this issue?

**Comment by corwintines** [comment]
@evertonfraga I believe its for scrolling purposes for links

**Comment by samajammin** [comment]
Thanks for offering to help out @evertonfraga! Good to see you again 😄 

Yup, expand on @corwintines's comments, the reason for the negative margin is so that if you open a URL w/ an anchor tag (e.g. https://ethereum.org/en/developers/docs/nodes-and-clients/#full-node), the browser & nav doesn't overlap the header.

Curious to hear what you come up with , I'm sure there's better approaches than the negative margin.

**Comment by evertonfraga** [comment]
sure, thanks @samajammin! there's `scroll-padding` for that particular problem. >90% support, afaict. 

OK expect a PR from me :)

**Comment by TonyGaski** [comment]
hey anyone here able to help me familiarize myself with this stuff?

**Comment by corwintines** [comment]
@TonyGaski let me know if there is something else you are interested in looking into. If you want to see how this got solved I just opened a PR for this.

**Comment by evertonfraga** [comment]
thanks for fixing that before me, @corwintines :)
