### ISSUE TITLE
Improve Website's Image Formats

### ISSUE THREAD

**Issue by byoriolserra** [ethereum/ethereum-org-website#4969]
**Is your feature request related to a problem? Please describe.**

With this Issue I would like to suggest changing the website's image file types to more modern, smaller ones.

**Describe the solution you'd like**

It would require for the files to switch from PNG to WebP.

**Describe alternatives you've considered**

We could also use AVIF, but I believe it is supported by less browsers. I believe WebP is the optimal middle ground.

**Additional context**

I have thought about this suggestion after reading Andrea Perera's article titled ['Best Image Formats for Web Applications in 2021'](https://blog.bitsrc.io/best-image-formats-for-web-applications-in-2021-39d0c91c7013). There's clear info on the pros and cons of each modern file type, and it even includes a decision tree at the end.

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by ForbidTANNEN** [comment]
Great suggestion! I am happy to pick this up. I will submit a PR shortly.

**Comment by minimalsm** [comment]
Hey @byoriolserra, thanks for raising this. 

I believe our Image component created by [gatsby-plugin-image](https://www.gatsbyjs.com/plugins/gatsby-plugin-image) already handles this for us. If I go to ethereum.org and copy the link to the hero image I get [this WebP image](https://ethereum.org/static/28214bb68eb5445dcb063a72535bc90c/9019e/hero.webp). Not 100% how this works under the hood but I believe image formats are served on a browser by browser basis. Can you confirm you see the same?

Some initial research on my end seems to show that although lossy WebP is more performant over lossy JPEGs [the same isn't true of lossless WebP over lossless PNG](https://havecamerawilltravel.com/webp-website/). (We mostly use PNGs)

> The WebP lossless setting is specifically designed as a replacement for PNG files, but in my tests in taking existing optimized PNGs and converting them to lossless WebP I ended up with files that were significantly larger than the originals.

A definite improvement we could make here and one we discussed internally was converting some PNGs (e.g. the logos we use on [the find wallets page](https://ethereum.org/en/wallets/find-wallet/)) to SVGs. Maybe this is the best way to proceed? Curious to hear your thoughts.

---
@corwintines @samajammin @wackerow 

Perhaps worth noting when we upgraded to Gatsby V4 (which forced just to use `gatsby-plugin-image` instead of `gatsby-image`) we saw a noticeable decrease in image quality in some cases. Maybe we have been serving lossy WebP images since then without realising it?

**Comment by minimalsm** [comment]
@wackerow is going to check out if this is being handled for us by `gatsby-plugin-image` and close this issue if it is. We don't want to update source files to WEBP (_it is still obscure and therefore harder for contributors to work with_) if we can avoid it by allowing Gatsby to do all the heavy lifting here.

**Comment by minimalsm** [comment]
Confirmed that `gatsby-plugin-image` is handling this for us already. Thanks again @byoriolserra

**Comment by minimalsm** [comment]
@all-contributors please add @byoriolserra @ForbidTANNEN for ideas

**Comment by byoriolserra** [comment]
Thank you very much!! @minimalsm
