### ISSUE TITLE
Add video on Smart Contracts on /learn page

### ISSUE THREAD

**Issue by evabeylin** [ethereum/ethereum-org-website#52]
Add video: Ameer Rosic - What is a Smart Contract? A Beginner’s Guide https://www.youtube.com/watch?v=qdoUpGg_DpQ

**Comment by texture** [comment]
There should be a way for people to submit content that doesn't require opening an issue on github.

**Comment by ethjoe** [comment]
I do like the video -- the real world language is helpful and I explain contracts to people using the same IFTT terms. Most of it is great, but maybe not a great fit for Ethereum.org.

As a less-technical video, it can be easier to make small mistakes, like the note that nodes execute contracts. And as a service, there are too many referral links attached to the video (10$ in FREE BTC when you sign up HERE) to be directly on ethereum.org, imho. 

Now, if teams running subpages were active to the point that rotating content had material changing more frequently, say weekly, then I'd likely flip on this. But since content is currently featured for a longer period of time, I'm a nea for now.

**Comment by ethjoe** [comment]
@texture -- Ideas? I'm actually not a regular GH user, but the on-ramp has been pretty nice and it's easy for those making changes to push from here. Something that is more welcoming to the average user though could be helpful too. 

And apologies for the long-delayed reply; I'm a proud 0-inboxer but was just assigned this one.
