### ISSUE TITLE
Reduce repo size

### ISSUE THREAD

**Issue by wd021** [ethereum/ethereum-org-website#5708]
Are there efforts to reduce the size of the repo? It's currently 500mb+..

**Comment by wackerow** [comment]
So a fresh clone of this repo is showing ~554 MB total, 372 MB of which is in the `.git` folder, while the `src` folder is 173 MB. Translations are just strings and don't really add much to the repo itself, only to the build size. 

We should probably take a look at our packages at some point to see which potentially aren't being used anymore. Otherwise perhaps a look at our images to see if any are just way bigger than needed.

**Comment by pettinarip** [comment]
- `src` ~ yeah probably we need to clean up the assets folder. Also, I like having some remote service for the assets. However, I think that will make the contribution process a bit more complex, not sure.
- `.git` ~ I think it is a good opportunity to discuss whether we want to analyze/reduce the size of our git history. Maybe we could make a backup of it and squash the history at some point. I doubt we want to have the whole history. Or perhaps there are ways of optimizing the .git folder without losing any history.

**Comment by wackerow** [comment]
Circling back on this... team is currently pursuing refactoring the tech stack from Gatsby to Next.js. With this there will be significant changes to the overall structure and size of the repo, and the packages used. I agree a smaller repo size would be helpful, and I see this as a DX improvement that we should readdress after the transition to the new stack. Going to close this out for now though =)
