### ISSUE TITLE
Wrong information?

### ISSUE THREAD

**Issue by 0fatih** [ethereum/ethereum-org-website#5714]
Hey, I just re-reading the Ethereum whitepaper and I saw something interesting. In [this](https://ethereum.org/en/whitepaper/#ethereum-state-transition-function) link you can see that paragraph under the State Transition Function (5):

> If the value transfer failed because the sender did not have enough money, or the code execution ran out of gas, revert all state changes except the payment of the fees, and add the fees to the miner's account.

But AFAIK also the sender's nonce changes if there is an out of gas situation. I tested it, and I am right. Am I missing something or there is misinformation?

**Comment by minimalsm** [comment]
Hey @0fatih, the whitepaper has been frozen to preserve its historical context. Even if there was/is a mistake here, we wouldn't be changing it. (See #3794 for more context on this)

That being said, unsure if this has changed since the Whitepaper was published (many things have). Perhaps ask in the [ETH R&D server](https://discord.gg/2BEKHUqHSA) if you're simply curious?

Going to close this out as there is nothing to action on our end. Thanks again for raising ❤️
