### ISSUE TITLE
Suggestion adding as a key management option: abyss.finance/eth2depositor

### ISSUE THREAD

**Issue by jdgsb** [ethereum/ethereum-org-website#6234]
Before suggesting a staking product or service, make sure you've read [our listing policy](/contributing/adding-staking-product/).

Only continue with the issue if the staking product meets the criteria listed there.

If it does, complete the following information which we need to accurately list the product/service.

**Product type**

- [ ] Node/client tooling
- [ x ] Key management
- [ ] Staking as a service
- [ ] Staking pool
- [ ] Other: (describe)

Abyss Eth2 Depositor

(https://abyss.finance/eth2depositor)

**Description**

**Website**

**If software is involved, is everything open source?**

- [ ] Yes, everything is open source: _provide link(s) to project repo(s)_
- [ ] Portions of code are open source: _provide link(s) to project repo(s)_
- [ ] No, code is closed source
- [ ] N/A, no custom software is involved

**Is the project a fork? If yes, which project was forked?**

**Is the product out of _beta_ development?**

**What wallets support the product or service?**

**If the product or service enables staking with <32 ETH, what is the minimum ETH required to stake?**

**If a service, what are the fees associated with using the service?**

**If the product or service involved a liquidity token, what are the tokens involved?**

**What date did the project or service go live?**

**Has the project undergone an external security audit?**

**Has the project undergone any security bug bounties?**

**Is the project being actively maintained?**

**Is the product or service free of trusted/human intermediaries?**

**If a pooled staking service, can users participate as a node operator without permission?**

**If listing a staking-as-a-service, are users required to sign-up for an account?**

**If listing a staking-as-a-service, who holds the signing keys, and withdrawal keys?**

**If a pooled staking service, what percent of node operators are running a supermajority CL client?**

**If listing node or client tooling, which CL clients (Lighthouse, Teku, Nimbus or Prysm) are supported?**

**What platforms are supported?**

**What user interfaces are supported?**

**Social media links**

**Comment by minimalsm** [comment]
Thanks @jdgsb, could you fill out the rest of the relevant questions in the template, please?

**Comment by DaveyD233** [comment]
The problem is NOT the Hysterium of ETHERIUM being #blocked, more than the #number#s of "POSSIBLE Ethereum 1&2.0 tokens", according to CoinBase, RISING 100k (IN BOTH ETH1&2.0) tokens since the BEGINNING of this year(ie. 120million ETH 1&2.0 tokens available, ON January 2022, to 120.1 ETH1&2.0 tokens IN February 2022, to NOW; Where CoinBase is showing there ARE 120.8Million ETH1&2.0 tokens PRESENTLY, May 2022, EQUALLING "121.6 TOTAL ETH1&2.0 tokens" Today, Though Eth 2.0 is STILL Not even available to use!? 
     Appearing as if ETHERIUM 2.0 is EQUALLY being "staked" is a Major Mining&Proof-Of-Stake RIP-OFF! Not only that, the increase of NOW 1.8MILLION MORE of Both ETHERIUMS 1&2.0, is MAKING MY Current ETHERIUM 1 tokens DEPRECIATE in value ALSO!! 
     ADDING TWICE AS MANY tokens to "Balance out"_"APPEAR" as if ETH1&2.0 ARE Equal, while the "staked" ETH2.0 CAN'T Even be Touched, is the BIGGEST RIP OFF I HAVE EVER SEEN IN MY ENTIRE LIFE(lol next to Blu-ray, merely ENHANCING the Color MORE, to "appear" better than HD 🙂)! 
     WHO KEEPS ADDING THESE "NEW TOKENS" that @CoinBase is reporting, FOR BOTH ETHERIUM 1&2.0?! Because whomever is the "Extra Tokens Adder," is Not Only DEPRECIATING the VALUE of BOTH ETHERIUMS 1&2.0, but putting these "Mysteriously Added $1.6MILLION New Eth 1&2.0 tokens" in their OWN pockets(ie. Vitalik Buterin's "Custom Oil Painting" of Himself, for his Twitter Photo), while the REST OF US Have to just WATCH, as the #Number#s of ETHERIUMS 1&2.0 tokens KEEP going UP(while also watching the prices keep going DOWN) in the process! 
     Dehumanizing others because of COLA(Cost Of Living Adjustment) going UP 5.9%(the Highest since 1981, when the World Wide Web came out), just to Maintain their Rich Living Lifestyle (#Greedily) was NOT what Ethereum was Originally invented For, nor originally "All About"! It's a Community Currency, which iss now seeming to become the greedy bank-like/centralized architecture the Whole Idea of Ethereum was AGAINST to start with! Ethereum Cant survive without BitCoin, and Vise Versa too!
   Let's ALSO please Keep in mind that Public Service Providers, HERE IN the USA(&Other countries), HAVE been starting 2B Paid for by BitCoin &transfered through ETHERIUM, to $$$$! iSalute Ethereum for the Main Mission Statement's ideal of "promoting the general welfare,to ENSURE Domestic Tranquility"!,but ADDING MORE TOKENS to Both ETHERIUMS 1&2.0 Diviates THAT ENTIRE MO(Modus Operandi) of said "Mission Statement" while Also doing the SAME "for" the Communities, that CryptoCurrency was designed for to begin with!

Thank you for your time, 
CAPT David Simonton-Valento, O-3_USAF, AAS, BT-BAS, Sap-Certification
