### ISSUE TITLE
Epic: Public goods use case page

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#6330]
_This is an epic that makes up part of [the ethereum.org Q2 roadmap](https://github.com/ethereum/ethereum-org-website/issues/6161)_

### Description

[Web3](https://ethereum.org/en/web3/) brought about a revolution in how we think about public goods funding. Continued experiments in quadratic and retroactive public goods funding could be the key to meaningful world changes and the betterment of humanity. But the ways to learn about these ideas and their current terminology are poorly explained and full of jargon. Our public goods funding page aims to solve this, making the content on this Ethereum use case accessible to anyone and—hopefully—have them saying: public goods are good.

### Structure draft

Update 26/5/22 - [Here is a proposal for the structure of the page headings](https://bit.ly/3Gl93Wg). Please feel free to comment on the Google Doc.

**Comment by wackerow** [comment]
Being worked on in #7732

**Comment by corwintines** [comment]
As discussed in https://github.com/ethereum/ethereum-org-website/pull/7732, we are going to shift the perspective of this page from `Public goods page` use case to `Funding page` use case. Since one of the main use cases for Ethereum is funding, public goods is a subset of this and should be captured in that instead. We will create an issue in the future around a general funding page.
