### ISSUE TITLE
Fix spelling on the Language resources page

### ISSUE THREAD

**Issue by lukassim** [ethereum/ethereum-org-website#6363]
**Describe the bug**

On the Language resources page, the first sentence in the 'ethereum.org resources' section contains additional words that should be removed.

**To Reproduce**

1. Go to https://ethereum.org/en/community/language-resources/#ethereum-org
2. Read the first sentence
3. See error

**Expected behavior**

'is translated' should be removed so the sentence would be _Ethereum.org is natively translated into over 40 languages which you can find on our languages page_.

**Screenshots**

<img width="748" alt="Screenshot 2022-05-17 at 13 28 18" src="https://user-images.githubusercontent.com/37338979/168801172-bf9800a9-cedc-4d8e-b05b-6da53fef4122.png">

**Desktop (please complete the following information):**

All

**Smartphone (please complete the following information):**

All

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by joeurassa** [comment]
I can correct that

**Comment by DaveyD233** [comment]
The problem is NOT the Hysterium of ETHERIUM being #blocked, more than the #number#s of "POSSIBLE Ethereum 1&2 tokens", according to CoinBase, keeps rising 100k ETH1(&2.0) tokens since the BEGINNING of this year(ie. 120million ETH 1&2 tokens available, ON January 2022, to 120.1 ETH1&2 tokens IN February 2022, to NOW; Where there ARE 120.8Million ETH1(&2.0) tokens NOW, May 2022, EQUALLING "121.6 TOTAL ETH1&2.0 tokens" Today, but Eth 2.0 is STILL Not even available to use yet!? 
     Appearing as if ETHERIUM 2.0 is EQUALLY being "staked" is a RIP-OFF! Not only that, the increase of NOW 1.8MILLION MORE of Both ETHERIUMS 1&2, is making MY Current ETHERIUM 1 tokens depreciate in value!! 
     ADDING TWICE AS MANY tokens to "Balance out"_"APPEAR" as if ETH1&2 ARE Equal, while the "staked" ETH2.0 CAN'T Even be Touched, is the BIGGEST RIP OFF I HAVE EVER SEEN IN MY LIFE! WHO KEEPS ADDING THESE "NEW TOKENS" CoinBase is reporting, FOR BOTH ETHERIUM 1&2.0?! 

Thank you for your time, 
CAPT David Simonton-Valento, O-3_USAF, AAS, BT-BAS, Sap-Certification

**Comment by d0ra-1h3-3xpl0ra** [comment]
Can I fix it?
