### ISSUE TITLE
Remove OpenEthereum from node page

### ISSUE THREAD

**Issue by tvanepps** [ethereum/ethereum-org-website#6389]
https://ethereum.org/en/developers/docs/nodes-and-clients/#projects

OpenEthereum is deprecated and should be removed

**Comment by DaveyD233** [comment]
The problem is not the Hysterium is being being blocked, comma more than the numbers of possible ethereum tokens, according to CoinBase, keeps rising 100,000k+ETH1&2 tokens since the beginning of this year(ie. 120million ETH 1&2 tokens available, from January 2022, to 120.1 ETH1&2 tokens 8n February 2022, to 120.8million ETH1&2 tokens NOW, May 2022, EQUALLY, where there are 121.6 TOTAL ETH1&2 tokens Today, and Eth 2.0 isnt even available to use!?)! Appearing as if ETHERIUM 2.0 is EQUALLY being "staked" is a BS RIP-OFF, making MY Current ETHERIUM 1 tokens depreciate in value, adding TWICE AS MANY tokens to "Balance out"/Appearing as if ETH1&2 ARE Equal, while the "staked" ETH2.0 CAN'T Even be Touched, is the biggest RIP OFF I have EVER SEEN! WHO KEEPS ADDING THESE "NEW TOKENS" CoinBase is reporting BOTH ETHERIUM 1&2 has?!

**Comment by minimalsm** [comment]
@tvanepps I take it the hopes of OE being taken over by someone else are dead?

**Comment by hursittarcan** [comment]
@minimalsm can I remove it from the page?
