### ISSUE TITLE
Can't deposit stake through ETH Launchpad

### ISSUE THREAD

**Issue by pmantica3** [ethereum/ethereum-org-website#6478]
**Describe the bug**

After clicking "Confirming Deposit" in the launchpad website, we get a "Transaction Failed" error message. We have 38 eth in our wallet and our only trying to deposit enough eth for one validator. We are using the metamask wallet.

**To Reproduce**

1. Go to https://launchpad.ethereum.org/en/
2. Go through the staking wizard
3. Click "Confirming Deposit" at the very end

**Expected behavior**

Expected the transaction to succeed.

**Desktop (please complete the following information):**

- OS: Windows 
- Browser: Chrome

**Comment by CarlBeek** [comment]
Sorry to hear the transaction failed. We're going to need a little more information in order to debug this.

Where exactly is the error message being displayed (in your wallet/on the launchpad/ both)? Is there more information in the error message as to why the TX failed (out of gas etc)? Does the failed tx show up on a block explorer or in your wallet?

**Comment by pmantica3** [comment]
Hi apparently this was an issue from our side. We had to approve our transaction and were failing to do so. Thanks for the rapid response though.
