### ISSUE TITLE
Deep URLs not forwarding to default language

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#6488]
**Describe the bug**
When going to a URL with one directory in the path, the language locale does not need to be included, allowing a link to be language agnostic when sharing and it will redirect accordingly. If the directory is deeper than one level, this results in a 404.

**To Reproduce**

Compare the following:
- https://ethereum.org/upgrades/ (forwards to https://ethereum.org/en/upgrades/ for me at least)
- https://ethereum.org/upgrades/merge (results in 404)
or
- https://ethereum.org/developers/ ✅
- https://ethereum.org/developers/docs/ ❌

**Expected behavior**
Ideally all pages undergo the same default language redirect as a fallback, not just pages in the top path directory.

**Comment by hursittarcan** [comment]
I'm not sure if this will help but: 
I had a quick look, I couldn't find the exact location of the bug. But I believe I might have found the code to look at (not 100% sure). I included a screenshot. 

- https://github.com/ethereum/ethereum-org-website/blob/f73abdab628fbad734225c30f38e9ba3d758e3bb/gatsby-config.ts#L48-L50

**Comment by hursittarcan** [comment]
I'm not sure if this will help but: 
I had a quick look at this and I believe I found the problem. I'm not sure if we can fix this bug programmatically.

- Almost all redirects happen in [redirects.json](https://github.com/ethereum/ethereum-org-website/blob/dev/redirects.json)
- Example given in issue: https://github.com/ethereum/ethereum-org-website/blob/f73abdab628fbad734225c30f38e9ba3d758e3bb/redirects.json#L95-L96
- There is no `"fromPath": "/developers/docs/"` in this file. That's why it gives an error. 
- Adding: `"fromPath": "/developers/", "toPath": "/en/developers/"` will solve the example given in the issue. 

I'm not sure if this is a good way to fix this, since there are many more cases. But I don't see a different approach.
