### ISSUE TITLE
Update all wallet data with new issue form questions

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#6536]
**Is your feature request related to a problem? Please describe.**
As part of the find-wallet page revamp (https://github.com/ethereum/ethereum-org-website/issues/6274) we have updated the issue template form for wallets (https://github.com/ethereum/ethereum-org-website/issues/new?assignees=&labels=wallet+%3Apurse%3A&template=suggest_wallet.yaml&title=Suggest+a+wallet). This new issue template expands the data we gather on features that wallets provide. With the release of this, our wallet data is now out of date for wallets.

**Describe the solution you'd like**

Fill out the issue template (i.e. [create an issue](https://github.com/ethereum/ethereum-org-website/issues/new?assignees=&labels=wallet+%3Apurse%3A&template=suggest_wallet.yaml&title=Suggest+a+wallet)) for each of the wallets we currently list on ethereum.org to make sure we have up to date data for the release of the new find-wallets page.

**Additional context**

We plan to ship the updated wallet features by end of Q2, whether or not we have all the wallet data, so please help us collect this information ASAP if you'd like a wallet to remain listed! If we don't have the data for a given wallet, it will be filtered out from any new feature filters.

**Wallets that need to be filled out:**
- [ ] [Trust](https://trustwallet.com/)
- [x] [Argent](https://trustwallet.com/)
- [x] [imToken](https://token.im/)
- [x] [Portis](https://www.portis.io/)
- [x] [MetaMask](https://metamask.io/)
- [x] [Gnosis Safe](https://gnosis-safe.io/)
- [x] [Torus](https://toruswallet.io/)
- [x] [Coinbase Wallet](https://wallet.coinbase.com/) - #6613
- [ ] [Ledger](https://www.ledger.com) - #6598
- [ ] [Trezor](https://trezor.io/)
- [ ] [Monolith](https://monolith.xyz/)
- [x] [MyCrypto](https://www.mycrypto.com/)
- [x] [Rainbow](https://rainbow.me/)
- [x] [MyEtherWallet](https://www.myetherwallet.com/)
- [x] [AlphaWallet](https://alphawallet.com/)
- [ ] [Enjin](https://enjin.io/wallet/)
- [x] [Status](http://status.im/)
- [x] [ZenGo](https://zengo.com/)
- [x] [Pillar](https://pillarproject.io/)
- [x] [TokenPocket](https://www.tokenpocket.pro/en/)
- [ ] [Multis](https://multis.co/)
- [ ] [MathWallet](https://mathwallet.org/en-us/)
- [ ] [HyperPay](https://hyperpay.tech/download/)
- [ ] [D'CENT](https://dcentwallet.com/)
- [x] [Unstoppable](https://unstoppable.money/)
- [x] [Guarda Wallet](https://guarda.com/)
- [ ] [Fortmatic](https://fortmatic.com/)
- [x] [Linen](https://linen.app/)
- [ ] [Coinomi](https://www.coinomi.com/en/)
- [ ] [WallETH](https://walleth.org/)
- [ ] [Samsung Blockchain Wallet](https://www.samsung.com/global/galaxy/apps/samsung-blockchain/)
- [ ] [Bitcoin.com Wallet](https://wallet.bitcoin.com)
- [ ] [SafePal](https://safepal.io)
- [x] [Opera Browser](https://www.opera.com/crypto/)
- [x] [Coin98 Wallet](https://coin98.com/wallet/)
- [ ] [BitKeep Wallet](https://bitkeep.com/)
- [x] [Keystone](https://keyst.one/)
- [x] [Loopring Wallet](https://loopring.io/)
- [x] [Numio](https://numio.one/)
- [x] [AirGap Wallet](https://airgap.it/)

**Want to contribute?**
We would love and appreciate any support in gathering this information. If you would like to contribute, please claim a wallet to fill out and link back to this issue so we can track progress :)

**Comment by sambacha** [comment]
Fortmatic is now Magic

**Comment by sambacha** [comment]
Metamask has Metamask mobile, which is not the same as Metamask (desktop) they do not have the same features. As does Argent wallet with Android and iOS: they do not have feature parity (yet?)

**Comment by chlolands** [comment]
Can you please add Tally Ho?

[https://tally.cash/]
[https://github.com/tallycash/extension]

**Comment by floating** [comment]
Please add Frame: #6601 

Thank you! 🙏

**Comment by Ivshti** [comment]
Please add Ambire: https://github.com/ethereum/ethereum-org-website/issues/6612 :pray: 

Ambire is a human-friendly smart wallet for Web3, supporting many next-gen features such as advanced transaction visualization and batching, paying gas in stablecoins, non-custodial email/password authentication and others.

**Comment by Mousticke** [comment]
Ledger Nano X : #6598 Finished

**Comment by rolodexter** [comment]
where is the criteria for how you decide on whether or not to include a wallet on the list

**Comment by rolodexter** [comment]
![image](https://user-images.githubusercontent.com/977925/173524486-6a83e7b7-ae37-4728-8914-ed5b6d1dee40.png)
for onboarding purposes would it be useful to list some stats on the profile square like userbasesizecategory 

for friends that i try to onboard i think they'd like to be able to filter wallets by mass market platform compatibility like coinbase opensea

**Comment by Dadybayo** [comment]
Unstoppable Wallet #6796 
https://github.com/ethereum/ethereum-org-website/issues/6796

**Comment by arielman87** [comment]
🙏🏼Please review and add [Sequence](https://sequence.xyz/) Issue: https://github.com/ethereum/ethereum-org-website/issues/7056 💜
Sequence Wallet Contact: @phabc

**Comment by jack-cryptocom** [comment]
Please review and consider to add #6155 (Crypto.com Defi Wallet), thanks!

**Comment by corwintines** [comment]
Update: continuing to review incoming issues. Will close this out soon as we have most of these wallets added now. Part of doing this was to filter out wallets, and ones that havent submitted will not be featured anymore.

**Comment by Dadybayo** [comment]
> Update: continuing to review incoming issues. Will close this out soon as we have most of these wallets added now. Part of doing this was to filter out wallets, and ones that havent submitted will not be featured anymore.

https://github.com/ethereum/ethereum-org-website/issues/6796#issuecomment-1172192485

**Comment by Thomas772-nyben** [comment]
Getting to find this team was a blessing to me during my divorce process. My ex took nearly everything from me including my kids, however with the help of this professional Investigators who got into his phone and provided me with conversations and deleted pictures, I was able to prove that he was toxic and abusive. I won the children custody.
WWW. HACKMART.ORG

**Comment by samajammin** [comment]
@corwintines think we should close this out? I think if anyone wants to add any remaining wallets, they can create a dedicated issue with the wallet info:
https://github.com/ethereum/ethereum-org-website/issues/new?assignees=&labels=wallet+%3Apurse%3A&template=suggest_wallet.yaml&title=Suggest+a+wallet

**Comment by corwintines** [comment]
Yes this is ready to close.

**Comment by Euronumero231** [comment]
10/10 Amazing!!!
This is by far one of the more enjoyable service I have received from this website recommended, their customer service is outstanding, you can simply contact them their website WWW. NITROCRACKHUB . COM), they gave me a very detailed and simple instruction on how possible it was for me to see all activities of my spouse right from my phone, highly recommended, their customer service is outstanding, you can simply contact them their website WWW. NITROCRACKHUB . COM) as well ( that’s where I got the most sense of security was being able to talk to them on discord to confirm everything ) thank you very much for a smooth transaction!! Have a wonderful day!!!  - (NITROCRACKHUB@GMAIL.COM)

**Comment by ElizabethGibson994** [comment]
How I Got My Scammed Cryptocurrency Back

Do not, under any circumstances, entrust your cryptocurrency to these online investing firms. When I requested a withdrawal during the epidemic, they wanted me to make a larger investment despite the fact that I had deposited over $100,000 with them. Why, for instance, would I add additional funds while they blocked me from withdrawing any? When I told them I needed my money returned, they kept making excuses, but eventually stopped returning my calls or answering my emails. I told a colleague about everything, and he suggested WIZARD LARRY HACKER, so I messaged him. I must admit, I was impressed by the speed of his response. I received my money back because of how expertly they handled my case. WIZARD LARRY comes highly recommended.
wizardlarry@mail.com
WhatsApp +1 (205) 319-6886
Website : https://wizardlarry.wixsite.com/wizardlarry

**Comment by ElizabethGibson994** [comment]
How I Got My Scammed Cryptocurrency Back

Do not, under any circumstances, entrust your cryptocurrency to these online investing firms. When I requested a withdrawal during the epidemic, they wanted me to make a larger investment despite the fact that I had deposited over $100,000 with them. Why, for instance, would I add additional funds while they blocked me from withdrawing any? When I told them I needed my money returned, they kept making excuses, but eventually stopped returning my calls or answering my emails. I told a colleague about everything, and he suggested WIZARD LARRY HACKER, so I messaged him. I must admit, I was impressed by the speed of his response. I received my money back because of how expertly they handled my case. WIZARD LARRY comes highly recommended.
wizardlarry@mail.com
WhatsApp +1 (205) 319-6886
Website : https://wizardlarry.wixsite.com/wizardlarry 
![WhatsApp Image 2023-07-28 at 03 14 33](https://github.com/ethereum/ethereum-org-website/assets/144096802/a49f4e62-eb6a-49a7-8dd8-5670ccb758f2)
