### ISSUE TITLE
Northstake

### ISSUE THREAD

**Issue by Olivia-Northstake** [ethereum/ethereum-org-website#6652]
Before suggesting a staking product or service, make sure you've read [our listing policy](/contributing/adding-staking-product/).

Only continue with the issue if the staking product meets the criteria listed there.

If it does, complete the following information which we need to accurately list the product/service.

**Product type**

- [ ] Node/client tooling
- [ ] Key management
- [ ] Staking as a service
- [ ] Staking pool
- [ x] Other: (We are pioneering our proprietary technology platform that allow our clients to safely and securely deploy capital or crypto on multichain staking without the hassle of using many fragmented services)

**Northstake**

![Northstake_Transparent_Avatar_800x800_positive](https://user-images.githubusercontent.com/106385629/173351360-a1295afb-0a9a-4b02-83c4-2de8ee31ced4.png)
**

**We are pioneering our proprietary technology platform that allow our clients to safely and securely deploy capital or crypto on multichain staking without the hassle of using many fragmented services**

**www.northstake.dk**

**If software is involved, is everything open source?**

- [ ] Yes, everything is open source: _provide link(s) to project repo(s)_
- [ ] Portions of code are open source: _provide link(s) to project repo(s)_
- [ x] No, code is closed source
- [ ] N/A, no custom software is involved

**Is the project a fork? If yes, which project was forked?**

**Is the product out of _beta_ development?**
In production

**What wallets support the product or service?**
Any wallet with ETH 

**If the product or service enables staking with <32 ETH, what is the minimum ETH required to stake?**
min. 32 ETH

**If a service, what are the fees associated with using the service?**

25% of staking rewards at 4-6% APY, 15% of staking rewards at +9% APY

**If the product or service involved a liquidity token, what are the tokens involved?**

**What date did the project or service go live?**
6th of November 2021

**Has the project undergone an external security audit?**
Yes, ISAE 3402 (SOC1)

**Has the project undergone any security bug bounties?**

No, not at present

**Is the project being actively maintained?**
Yes, Northstake team

**Is the product or service free of trusted/human intermediaries?**
Yes, the staker will open an account with Northstake and deposit ETH in our ETH staking deposit account, afterwhich it will be distributed to Northstake custodial staking nodes, which is set up as 'solo home staking'. This is done without human intervention.

**If a pooled staking service, can users participate as a node operator without permission?**
We do not offer pooled staking service

**If listing a staking-as-a-service, are users required to sign-up for an account?**
We do not offer staking as a service

**If listing a staking-as-a-service, who holds the signing keys, and withdrawal keys?**

**If a pooled staking service, what percent of node operators are running a supermajority CL client?**

**If listing node or client tooling, which CL clients (Lighthouse, Teku, Nimbus or Prysm) are supported?**
Not listing client tooling

**What platforms are supported?**

macOS, Windows, iOS, Android

**What user interfaces are supported?**
Browser app

**Social media links**

https://www.linkedin.com/company/77111941/admin/
https://twitter.com/Northstake_dk
https://northstake.prowly.com/
https://t.me/northstake
https://discord.gg/pw8peBTYp5

**Comment by minimalsm** [comment]
Thanks @Olivia-Northstake :-) we'll try to look at this as soon as we can.

cc: @wackerow

**Comment by Olivia-Northstake** [comment]
> Thanks @Olivia-Northstake :-) we'll try to look at this as soon as we can.
> 
> cc: @wackerow

Hi, 

Do we have any update on the status of our application? 

Thanks in advance :)

**Comment by Olivia-Northstake** [comment]
@wackerow @minimalsm - do we have any update on the process of our application so far? :)

**Comment by corwintines** [comment]
Apologize for letting this sit @Olivia-Northstake. Adding this to grooming

**Comment by wackerow** [comment]
@Olivia-Northstake First off, I sincerely apologize for allowing this to sit for as long as it has. I'll be prioritizing bandwidth to address these requests this quarter. I've had a chance to review this request and have some questions for you:

> capital or crypto on multichain staking without the hassle of using many fragmented services

Could you help me understand this? Listing on ethereum.org are reserved for Ethereum staking. I see a 32 ETH requirement, just want to clarify how the "multichain" aspect comes into play.

> 25% of staking rewards at 4-6% APY, 15% of staking rewards at +9% APY

Could you clarify the gap from 6 to 9%? Also, does this include execution rewards (tips/MEV) or only base consensus rewards?

> ISAE 3402 (SOC1)

Could you please provide a link to a publicly available audit report?

_Is the product or service free of trusted/human intermediaries?_

> Yes, the staker will open an account with Northstake and deposit ETH in our ETH staking deposit account, afterwhich it will be distributed to Northstake custodial staking nodes, which is set up as 'solo home staking'. This is done without human intervention.

It's important to note here that "solo" or "home" staking in the context of the ethereum.org/staking pages refers to users running their own hardware for their own funds. Unless I'm missing something, what is being described here fits exactly with "staking-as-a-service" where you are accepting funds from users, and providing the service of running the node infrastructure for them for a fee. Otherwise, why would the user give you their ETH?

_If listing a staking-as-a-service, are users required to sign-up for an account?_

> We do not offer staking as a service

> the staker will open an account with Northstake

<img width="602" alt="image" src="https://user-images.githubusercontent.com/54227730/226728475-fefb3160-fda3-43e1-93ec-d19624f90329.png">

Continuation from above, this appears to be a staking-as-a-service solution, which requires an account to set up. Typically any requirement to open an account means that the user requires permission in order to use the service. Alternatively, services that do not require any centralized account setup, where anyone can deposit funds without asking, would be considered "permissionless" (as an example, see [Abyss Finance](https://abyss.finance/host) which allows a user to log in with their wallet and user free market tokens to start without requiring additional account signup or KYC).

> If listing a staking-as-a-service, who holds the signing keys, and withdrawal keys?

Please clarify who holds the keys to the validator being instantiated through these deposits. From what I see I'd assume Northstake holds all keys, but please confirm.

I would classify this as the following, for the aforementioned reasons:
- SaaS
- ❌ Open source
- ✅ Audited (pending publicly available link)
- ❌ Bug bounty (let us know if this has changed)
- ✅ Battle tested
- ❌ Permissionless
- ？ Diverse clients\*
- ？ Self custody (Need info requested above)

\* Diverse clients: Realizing we may be missing this question, but could you provide some information on the breakdown of the clients being used through the Northstake infrastructure (in particular, percentage of validators utilizing Prysm, and percentage using Lighthouse)?

**Comment by wackerow** [comment]
Hey @Olivia-Northstake! Just circling back, any update on the info requested above?

**Comment by wackerow** [comment]
Hey @Olivia-Northstake, haven't heard back in some time so going to close this out, but feel free to reopen with the additional info at your convenience.
