### ISSUE TITLE
No table of contents on EVM opcodes page

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#7072]
**Describe the bug**

I'm not seeing the table of contents dispayed on EVM opcodes page:
https://ethereum.org/en/developers/docs/evm/opcodes

But the `sidebar: true` frontmatter appears to be there... 🧐 
https://github.com/ethereum/ethereum-org-website/blob/dev/src/content/developers/docs/evm/opcodes/index.md

**To Reproduce**

1. Go to https://ethereum.org/en/developers/docs/evm/opcodes
2. See error (no table of contents)

**Expected behavior**

It should be there??

**Screenshots**

![Image 2022-07-14 at 1 53 06 PM](https://user-images.githubusercontent.com/8097623/179084070-0448d2ed-ad3b-4b50-a9ff-9d6425147fcd.jpg)

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Brave
- Version: 1.39.120

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by vdusart** [comment]
Can you assign me this one please @samajammin :smile: 
I already took at it and the problem is not from the `sidebar`.
I think it's from the  `tocItems` (Table of contents) that is undefined because there are no headers in the file to fill the table of contents.

So I see two solutions to fix that:
First one will be to add a single header like `## Content`. It will just create the ToC on the side as you can see bellow: 
![image](https://user-images.githubusercontent.com/43795504/181469445-c132e01d-e62d-4e2a-bda4-67f2f7cefc65.png)

Or we can add real content like:
```
## Description {#description}
...
## OPCODES {#opcodes}
...
```
And then have a result like that:
![image](https://user-images.githubusercontent.com/43795504/181470088-c664ea67-2b45-496c-a9ef-2fda06a1f8ad.png)

Please tell me what you think about that :smile:

**Comment by samajammin** [comment]
Hey @vdusart - thank you for looking into this! 🤩 

You're totally right - it's because the opcodes markdown file doesn't have any headers 😅 

I like your idea to add headers to the content. I'd suggest:

```
## Overview {#description}
...
## Opcodes {#opcodes}
...
```
