### ISSUE TITLE
Standardize uses of zk-rollup/ZK-rollup

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#7123]
**Describe the bug**
- On the layer 2 and zero-knowledge rollup pages there are conflicting uses of zk-rollup and ZK-rollup. 

**Expected behavior**
- Consistent use of either zk-rollup or ZK-rollup (depending on the decision for which to use moving forward).

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by corwintines** [comment]
https://docs.aztec.network/ - Uses ZK-rollup
https://docs.dydx.exchange/#general - Uses ZK-Rollup
https://loopring.org/#/ - Uses zkRollup
https://zksync.io/ - Uses ZK Rollup
https://zks.org/ - Uses ZK-Rollup

Some context about how the projects we list are using it. Leaning towards changing the layer-2 page to use ZK-rollup instead of zk-rollup. Curious what others think.

**Comment by emmanuel-awosika** [comment]
Like I explained previously, I prefer "**ZK-rollup**" since other terms related to zero-knowledge, e.g., ZK-SNARK/ZK-STARK, use the "ZK" acronym in uppercase. Also, I don't think "**ZK-Rollup**" works since "rollup" is usually lowercase (e.g., "optimistic rollup", not "Optimistic Rollup"). As for adding hyphens between "ZK" and "rollup', that's a matter of personal of preference--but I prefer hyphenated terms in this case to avoid confusion (e.g., "**ZK-rollup**").
