### ISSUE TITLE
Restructure documentation

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#7425]
**Is your feature request related to a problem? Please describe.**

With the help of our wonderful community of technical content contributors, our developer documentation resources have exploded to nearly 100 pages. These resources live within a site structure that was originally targeted at web3 dapp developers yet over time, we’ve received feedback that many resources are useful to a broad range of visitors - hobbyists, designers, node operators, end-users, economists, entrepreneurs, and more user types beyond pure “developers”. Even within the "developer" persona, there's multiple user types with different informational needs (e.g. frontend dapp devs vs. smart contract devs vs. protocol/client devs vs. tooling devs).

**Describe the solution you'd like**

As part of our Q3 roadmap (#7166) we're planning to rethink the overall information architecture of our documentation to best support a broader base of users and to ensure we surface key information that is often buried deep within technical topics.

Some of the questions we're considering (& would appreciate input on):
- Which docs are truly for “developers” vs. technical users?
  - For instance if we were to build out documentation for solo stakers where should that live? Should we create tailored sections like `ethereum.org/staking/docs/`? How do we draw the line on where content should live if we create site sections for different topics of documentation? 
  - Should we move most/all of our more intro-level documentation outside of the `/developers/` section into a generic `ethereum.org/docs/` section?
- Within our developer docs, how should we separate content for different types of devs?
  -  What are the various developer personas we should consider & create content for? 
    - e.g. frontend dapp devs, smart contract devs devs, protocol/client devs, researchers, tooling devs, more?
  - How might we better structure the existing dev documentation (currently bucketed within `Foundational topics`, `Ethereum stack` & `Advanced`)?

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by tuanggolt** [comment]
open

**Comment by emmanuel-awosika** [comment]
Hey, @samajammin: I did a general review of the Ethereum.org website and came up with a few suggestions that might help with efforts to restructure the documentation. Since this is a lengthy comment, I've tried to create a graphic to highlight the proposed structure first before going into details:

#### Suggested structure for Ethereum.org documentation

**`Overview`**

**`Fundamentals`**

 ⤷ `Intro to Ethereum`
 ⤷ `Intro to Ether`
 ⤷ `Intro to dapps`
 ⤷ `Web2 vs Web3`
 
**`Protocol`**

 ⤷ `Accounts`
 ⤷ `Transactions`
 ⤷ `Blocks`
 ⤷ `Ethereum virtual machine (EVM)`
     ↠ `Opcodes`
 ⤷ `Gas`
 ⤷ `Nodes and clients`
     ↠ `Run a node`
     ↠ `Client diversity`
     ↠ `Nodes as a service`
 ⤷ `Networks`
 ⤷ `Consensus mechanisms`
     ↠ `Proof-of-work`
     ↠ `Proof-of-stake`
          ⇢ `Gasper`
          ⇢ `Weak subjectivity`
          
**`Validator`**

 ⤷ `Run a validator`
 ⤷ `Attestations`
 ⤷ `PoS rewards and penalties`
 ⤷ `Key management`
 ⤷ `Distributed validator technology (DVT)`
 ⤷ `Maintaining validators`
 ⤷ `Validator FAQ`
 
**`Staking`**

 ⤷ `Staking on Ethereum`
 
**`Developers`**

 ⤷ `Ethereum development overview`
     ↠ `Intro to the stack`
 ⤷ `Smart contracts`
     ↠ `Smart contract languages`
     ↠ `Smart contract anatomy` 
     ↠ `Smart contracts libraries`
     ↠ `Testing smart contracts`
     ↠ `Compiling smart contracts`
     ↠ `Deploying smart contracts`
     ↠ `Verifying smart contracts`
     ↠ `Upgrading smart contracts`
     ↠ `Smart contract security`
     ↠ `Smart contract formal verification`
     ↠ `Composability`
 ⤷ `Development networks`
 ⤷ `Development frameworks`
 ⤷ `Ethereum client APIs`
     ↠ `JavaScript APIs`
     ↠ `Backend APIs`
     ↠ JSON-RPC
 ⤷ `Data and analytics` 
     ↠ `Block explorers`
 ⤷ `Storage`
 ⤷ `Integrated Development Environments (IDEs)`
 ⤷ `Programming languages`
     ↠ `Dart`
     ↠ `Delphi`
     ↠ `.NET`
     ↠ `Golang`
     ↠ `Java`
     ↠ `JavaScript`
     ↠ `Python`
     ↠ `Ruby`
     ↠ `Rust`
     
**`Advanced`**

 ⤷ `Bridges`
 ⤷ `Standards`
     ↠ `Token standards`   
 ⤷ `Economics`
     ↠ `Maximal extractable value (MEV)`
 ⤷ `Oracles`
 ⤷ `Scaling`
     ↠ `Optimistic rollups`
     ↠ `Zero-knowledge rollups`
     ↠ `State channels`
     ↠ `Sidechains`
     ↠ `Plasma`
     ↠ `Validium`
 ⤷ `Data availability`

**`Protocol Specification`**

 ⤷ `Standards`
     ↠ `Token standards`
           ⇢ `ERC-20: Fungible Tokens`
           ⇢ `ERC-721: Non-Fungible Tokens`
           ⇢ `ERC-1155: Multi-Token Standard`
           ⇢ `ERC-4626: Tokenized Vault Standard`
 ⤷ `Consensus layer specification`
 ⤷ `Networking layer`
     ↠ `Network addresses`
 ⤷ `Data structures and encoding`
     ↠ `Patricia Merkle Trie`
     ↠ `Recursive-length prefix (RLP)`
     ↠ `Simple serialize (SSZ)`
     ↠ `Web3 secret storage`
 ⤷ `Whitepapers`

**Key** 
- `⤷` points to a subsection of a section (e.g., `Intro to Ethereum` is a subsection of `Fundamentals`) 
- `↠` points a subpage under a subsection (e.g., `Run a node` is a subpage under the `Nodes and clients` subsection`) 
- `⤑` points to an item under a subpage (e.g., `Gasper` is an item under the `Proof-of-stake` subpage) 

#### Suggestions + rationale 

1. Rename `Foundational Topics` to `Ethereum Fundamentals` or simply `Fundamentals`. Because the fundamentals section only cover basic topics, it should be limited to [Intro to Ethereum](https://ethereum.org/en/developers/docs/intro-to-ethereum/), [Intro to Ether](https://ethereum.org/en/developers/docs/intro-to-ether/), [Intro to dapps](https://ethereum.org/en/developers/docs/dapps/), and [Web2 vs Web3](https://ethereum.org/en/developers/docs/web2-vs-web3/). Other topics should be moved to the section described below. 

2. Create an `Ethereum Protocol` (or simply `Protocol`) section that explains the key parts of Ethereum’s infrastructure. [Accounts](https://ethereum.org/en/developers/docs/accounts/), [transactions](https://ethereum.org/en/developers/docs/transactions/), [blocks](https://ethereum.org/en/developers/docs/blocks/), [Ethereum Virtual Machine](https://ethereum.org/en/developers/docs/evm/), [gas and fees](https://ethereum.org/en/developers/docs/evm/), [networks](https://ethereum.org/en/developers/docs/networks/), and [consensus mechanisms](https://ethereum.org/en/developers/docs/consensus-mechanisms/) should go under this section.

3. Add a `Validator` section that covers validator-related content, e.g., rewards and penalties, key management, hardware requirements, running a validator node, etc. 

3a. Add a `Staking` section as a standalone section with its contents either arranged in drop-down format or a subsection under the `Validator` section. 

**Notes about validator/stakers section**

- We can import content from the [Staking Launchpad]([https://launchpad.ethereum.org/) for the `Validator` and `Staking` sections. 

- We could survey validators/stakers to understand their pain points and ask what content they'd like to see in the docs. 

4. Rename `Ethereum stack` to something more descriptive, e.g., `Building on Ethereum` or `Ethereum development`. Another suggestion would be to simply rename it to `Developers` (more on this later).

5. Add an `Economics` section to the `Advanced` section to explain technical details about Ethereum’s economic design and incentives (e.g., deflationary mechanisms, token issuance, etc.). I've linked some examples from other blockchains  [here](https://docs.solana.com/economics_overview) and [here](https://near.org/blog/near-protocol-economics/). Perhaps an expert from the [Robust Incentives Group](https://ethereum.github.io/rig/) can assist with creating this page. 

5a. Add [Maximal Extractable Value (MEV)](https://ethereum.org/en/developers/docs/mev/) as a subsection under the `Economics` section. This will make the `Economics` section a valuable resource for researchers interested in Ethereum's economic aspect. Other subsections can be added later as deemed fit. 

6. The `Advanced` section should be limited to [Bridges](https://ethereum.org/en/developers/docs/bridges/), [oracles](https://ethereum.org/en/developers/docs/oracles/), [scaling](https://ethereum.org/en/developers/docs/scaling/), [data availability](https://ethereum.org/en/developers/docs/data-availability/), and `Economics`. Other topics should be moved to the section described below. 

7. Create a `Protocol Specification` (or simply `Protocol Specs`) section to cover topics that delve deeper into technical details about the Ethereum protocol. [Standards](https://ethereum.org/en/developers/docs/standards/), [networking layer](https://ethereum.org/en/developers/docs/networking-layer/), [data structures and encoding](https://ethereum.org/en/developers/docs/data-structures-and-encoding/) should (ideally) go under this section. 

7a. Create a `Whitepapers` subsection under the `Protocol Specification` section. This page will provide concise summaries of papers that have influenced Ethereum’s design philosophy and invite readers to gain a deeper understanding of Ethereum. We’d include the following papers: 
- [Ethereum: A Next-Generation Smart Contract and Decentralized Application Platform](https://ethereum.org/669c9e2e2027310b6b3cdce6e1c52962/Ethereum_Whitepaper_-_Buterin_2014.pdf)
- [Combining GHOST and Casper](https://arxiv.org/pdf/2003.03052.pdf)
- [Capser the Friendly Finality Gadget](https://arxiv.org/pdf/1710.09437.pdf)

**Notes about protocol specification section**

- I think it's better to separate content targeted at protocol/client developers than lump them under the `Advanced` section. 
- Another suggestion is to create pages with additional protocol-related information (e.g., [consensus layer specifications](https://github.com/ethereum/consensus-specs)). 

8. Revamp the documentation to target other technical users, not just developers. @samajammin suggested moving beginner-level content (i.e., `Foundational Topics`) to a generic `ethereum.org/docs/` domain, but renaming the entire developer documentation as `ethereum.org/docs/` may be a better alternative. Here are some reasons:

i. Creating a separate `ethereum.org/docs/` section for beginner-level topics may cause confusion or affect reader experience. For example, if I'm a developer new to Ethereum, having all educational content in one place makes progress easier. 

A plausible user journey would be: **reads content on Learn Hub** → **reads the `Fundamentals` section to understand blockchain/Web3 basics** → **reads the `Protocol` section to understand how Ethereum works under the hood** → **reads the `Developers` section once a basic understanding of Ethereum has been established.**

 ii. Having an all-encompassing `ethereum.org/docs/` section provides for the case where a website visitor wants a more technical explanation of how Ethereum works (possibly after visiting the Learn Hub), but is not interested in developer-only content. Here, I might want to read stuff in the `Fundamentals` and `Protocol` sections without reading the `Developers` section. 

iii. The `ethereum.org/docs/` option ensures we don’t pigeonhole Ethereum.org's technical content. As @samajammin  mentioned, many topics currently living in the developer docs appeal to other personas—node operators, R&D researchers, economists, hobbyists, academics, etc. 

Putting all of Ethereum.org's documentation in one place gives website visitors flexibility to choose what type of technical content they want to consume. It also reduces the overhead associated with trying to create different site sections for different technical users. For example, instead of having a separate site section for stakers/ (e.g., etherum.org/staking/docs/), staking-related content could be added to the existing documentation as `ethereum.org/docs/staking`. 

**Notes about renaming developer documentation**

i. We can point the [read the docs](https://ethereum.org/en/developers/) CTA on the [developer resources page](https://ethereum.org/en/developers/) to a new link (e.g., `ethereum.org/docs/developers`) that has the section targeted at smart contract developers. A plausible approach is described below:

> Create an `Ethereum development overview` page under the `Developers` section (prev. `Ethereum stack`) and rewrite the page so that it’s similar to the current [introductory page for developers](https://ethereum.org/en/developers/docs/). The overview page (`ethereum.org/docs/development-overview` or `ethereum.org/docs/developers/overview/`) will introduce new devs to the idea of building on Ethereum and include an index of pages to read (i.e., all topics currently listed under `Ethereum stack`).

ii. 1. Revamping the developer docs to target different personas may require new link styles for pages. Here are some examples: 

- `ethereum.org/docs/fundamentals/intro-to-ethereum/` (prev. `ethereum.org/developers/docs/intro-to-ethereum/`)
- `ethereum.org/docs/protocol/accounts/`(prev. `ethereum.org/developers/docs/accounts/`
- `ethereum.org/docs/developers/ethereum-stack` (prev. ethereum.org/developers/docs/ethereum-stack/)
- `ethereum.org/docs/advanced/bridges/` (prev. `ethereum.org/developers/docs/bridges/`)
- `ethereum.org/docs/validators/rewards-and-penalties`
- `ethereum.org/docs/protocol-specification/networking-layer` (prev. `ethereum.org/developers/docs/networking-layer/`)

I'm not aware if doing this would affect the original links (which might cause dead links to the site), or if the original links will redirect. That may determine if revamping the developer docs to target other user types is feasible or not. If adopted, though, the new link style is more readable and clearly shows how content in the documentation is structured. 

8. Rewrite the [introductory page](https://ethereum.org/en/developers/docs/) on the documentation using language that suggests it’s a place for anyone—not just developers—who wants to learn how Ethereum works. 

9. Address the issue of structuring content targeted at non-technical readers. The [Learn Hub](https://ethereum.org/en/learn/) serves well as a great resource for anyone new to Ethereum, but additional Learn-related content cannot possibly fit the section of the (or else, we’d be overloading readers). 

The Learn Hub currently works well as a landing page of sorts, with quick facts about Ethereum, but those who need a more structured learning experience may find it difficult to navigate and find topics. For example, the [zero-knowledge proofs](https://ethereum.org/en/zero-knowledge-proofs/) page is listed only on the site’s footer. But having to search the footer for pages to read can be tasking. 

One solution is to have a wiki- or knowledge-base-style section with general information about the Ethereum protocol, usage, infrastructure, etc., mostly targeted at onboarding new users. This wiki/knowledge base will complement the Learn Hub and can host the following pages: 

- `Glossary`
- `What is Web3?`
- `Smart contracts`
- `Wallets`
- `Ethereum Improvement Proposals (EIPs)`
- `Ethereum History`
- `Ethereum Governance`
- `Zero-knowledge proofs`
- Other beginner-level topics covered in the future

**Notes about creating a wiki/knowledge base**

- Several Learn-style pages are planned for creation as part of Q3’s [content strategy epic](https://github.com/ethereum/ethereum-org-website/issues/7240). A wiki or knowledge base ensures that we give non-technical readers the same opportunity for structured learning that we give technical users/developers on the developer docs page. 

- Creating another site section for beginner-level topics ensures the Learn Hub only has to include the most basic pages. Instead of links pointing to other pages underneath each section, a single `Learn more` CTA at the bottom of the page takes a would-be reader to the wiki/knowledge base. 

#### Miscellaneous
1. Add a link to the [Ethereum repository](https://github.com/ethereum) under the `developers` index at the site's footer. I have a feeling developers (perhaps protocol/client devs) will find it useful.
2. Should we still have an `Enterprise` section in the top nav bar? Maybe adding it to the site’s footer would be better.

**Comment by therevealer** [comment]
Wow this really cool

**Comment by jmcook1186** [comment]
Hi @emmanuel-awosika this is great work, thanks a lot. I like a lot of the ideas here. Some things we might want to think on some more are:

1) the definition of "protocol" - to me protocol means the rules encoded in client software that keeps the network live and secure. That wouldn't include things like token standards that are features of the application layer.
2) the distinction between `protocol` and `protocol specifications`: the `protocol specification` directory does not just contain specs - also pages that would just as easily fit into `protocol`. It's not clear where something like the JSONRPC API fits in this structure.
3) I'm not sure about having `validator` separate from `protocol` as validators are very much part of the protocol.
4) Maybe subdivide developers into `protocol developers` or `client developers` and `dapp developers`?
5) Maybe also consider whether there is space for content aimed at designers, web developers etc.
6) We also have a staking section one level higher (`content/staking`) that might satisfy the same purpose as your `staking` dir?

Not expecting you to address these points necessarily - just things that came to mind that we should discuss with others in the team. Certainly a lot of what is currently in `developers/docs` is neither documentation nor aimed at developers!

**Comment by emmanuel-awosika** [comment]
Hi @jmcook1186. Thanks for the feedback. I've left some replies to your comments:

> `Protocol` vs `Protocol Specifications`

I was thinking about "Protocol" in terms of the overall blockchain network along with its key components. The idea is that anyone who reads the "Protocol" section should have at least a high-level understanding of Ethereum's inner workings, especially the building blocks involved (consensus, EVM execution, etc.).

The idea of “protocol” as “rules encoded in client software that keeps the network live and secure” feels more like “protocol specifications” to me. I’m thinking `protocol specs` are requirements that client software, which is necessary for interacting with components of `Protocol`, must meet. 

In this case, something like the JSON-RPC API would fit within the `Protocol Specs` section. I do agree that token standards should be left out (changed the structure to the previous arrangement where `Token standards` are in the `Advanced` section).

> Separating `validator `from `protocol`

Fair point. That said, I was hoping to do something similar to what @samjammin suggested: create sections explicitly targeted at different user personas. So the `Validator` section is more about creating helpful content that the average validator finds helpful (example topics include,  `Maintaining validators`, `Key management`, etc.). 

The `Protocol` section will cover validators under consensus mechanisms, but the info there would be high-level and accessible to just about anyone (e.g., someone who wants to know what validators in Ethereum do). The `Validator` section is for those who actually want to start validating on Ethereum and need more low-level details about validating in general. 

> Subdividing developers into `protocol developers` or `client developers` and `dapp developers`

This fits with @samjammin's suggestion. However, the concern is: How large would the documentation get if we explicitly created different sections for different types of developers? Currently, most of the content in the `Developers` section pretty much targets dapp developers (and it's already sizable). I wonder if adding separate sections for protocol and client devs (instead of just adding the relevant pages elsewhere) would significantly affect the documentation structure. 

> Creating content aimed at designers, web developers, etc.

"Space" is really the key term here. I think it helps to understand that Ethereum.org probably won't be the one-stop resource for all development-related content. If we wanted something like this, it may require entirely new documentation sections in other places on the site (e.g.,  `Ethereum for web developers`, `Ethereum for UX designers`, etc.). Fitting all of that content in the same structure doesn't appear feasible to me. 

> `Staking` section vs `content/staking`

This is similar to what I highlighted in the comment about creating a new section for validator-specific content. The current `content/staking` page provides a high-level overview of staking, but I think we could have more detailed content in the documentation. 

As an example, the `Layer 2` page has a high-level overview of rollups, but developers/users who need more information will have to check the docs. @samjammin suggested created a new docs section for `staking`, so I guess there must be some plan to create more staking-related content that won’t fit into one page (possible suggestion is to survey stakers and use the feedback to guide content creation).

**Comment by samajammin** [comment]
@emmanuel-awosika thank you for all the great ideas! I'm sorry I never reviewed them in depth or replied. Obviously this slipped as a priority...

@jmcook1186 I'd love to see this prioritized as a Q2 epic 😄

**Comment by samajammin** [comment]
I wonder what resources exist out there that may be worth taking inspiration from? e.g.
- https://wiki.polygon.technology/
- https://community.optimism.io/
- https://developer.arbitrum.io/

**Comment by emmanuel-awosika** [comment]
> I wonder what resources exist out there that may be worth taking inspiration from? e.g.
> 
> * https://wiki.polygon.technology/
> * https://community.optimism.io/
> * https://developer.arbitrum.io/

I reviewed a lot of project resources while brainstorming ideas for the original suggestion, too. And some of the best examples I found were from [Polkadot](https://wiki.polkadot.network/), [Solana](https://docs.solana.com/), and [NEAR](https://docs.near.org/). Lots of great design and structure.

**Comment by corwintines** [comment]
Thanks for all the conversations and suggestions here. 

Although this is important, this is not something we foresee us working on in the near future. There are some great proposals here that we want to use in the future when we have the bandwidth to come back to this. I have added a revisit tag so that we can come back to this in the future and build on the ideas given here.
