### ISSUE TITLE
Establishing a process to add more wallets

### ISSUE THREAD

**Issue by p0s** [ethereum/ethereum-org-website#743]
Disclaimer & context: I'm working for imToken, the probably most used non-custodial Ethereum wallet in China and probably world-wide. We also helped translate ethereum.org into Chinese.

**Is your feature request related to a problem? Please describe.**
From looking at recent related PRs like #683 #342 #316 I found that we stopped adding wallets to https://ethereum.org/wallets/ .

I can understand that you stopped adding wallets. Probably because processes are hard to do, maintain in a way to satisfy everybody. Right?

I guess you already know why wallets ask to be added. For completeness let me add anyways:
1. First, listing on ethereum.org improves search ranking for listed wallets. 
2. Second, listing increases organic traffic to the wallet's site. 
That's why everybody wants to get in. It's literally worth $ to us. On the other hand, I guess that's also why it's a tough decision.

**Describe the solution you'd like**
Establishing a process to add more wallets. I can offer help.

Now solutions I thought about
1. Adding a `nofollow` tag will take away the advantage of improved page rank. But I don't like that,  because why shouldn't EF endorse wallets. Not zero-sum. Listing helps Ethereum wallets to be higher than non-Ethereum and listing good wallets helps good wallet vs. bad wallets.
2. Adding all wallets according to criteria adds more questions: Who sets and changes criteria? who deletes dead sites/wallets? who has time to add wallets?
3. other solutions? Maybe link to only one comparison site; Make super sophisticated list of wallets. None of those that seem fair and/or good or possible to me right now.

If we chose 2), then how do we solve mentioned issues:

Who sets criteria? https://github.com/Swader/wallets-review seems pretty good start to find criteria and be able to copy them. I can help.
Who changes criteria? Can be done via PR if people are unhappy.
Who deletes dead links/wallets? Wallets will add PRs to delete dead links, because it is in their interest. I can help.
Who has time to add wallets? Wallets will do it themselves.  

**Describe alternatives you've considered**
See above.

**Additional context**
Maybe the same problem exists for other links to businesses on this site (dApps might be easy because some of them are pubic infrastructure). So a solution of this might help those as well.

**Comment by samajammin** [comment]
Thanks for the thoughtful issue @p0s. I agree this is worth discussing & establishing a process. We welcome additional input from the community on this.

Another consideration for this solution (in addition to the ones you listed) is user experience. There's plenty of research out there on the adverse effects of choice, so it's a delicate balance to provide users with options but not so many that overwhelm them or lead to analysis paralysis. We do have a [RandomList](https://github.com/ethereum/ethereum-org-website/blob/dev/docs/.vuepress/components/RandomList.vue) component (which we use to shuffle the dapps we display) which may be an option to present an unbiased list. This, however, doesn't solve the core issue of curating a master list of wallets to display.

I think generally we do face similar issues for other resource sections of the site, so this could be a good way to set a precedent in terms of process. Inevitably there's some subjectivity in picking "winners" & "losers" of what is displayed on the site but to the best of our ability, I'd like to see ethereum.org maintain neutrality. Identifying quantitative metrics that answer [considerations we outline in our README](https://github.com/ethereum/ethereum-org-website#i-want-to-add-a-developer-tool-or-project) (Is it widely used? Is it well documented? Is it of sufficient quality?), whether those are self-reported in PRs or pulled from some 3rd party, might help remove the subjectivity of the process.

**Comment by NevermoreAK** [comment]
"Second, listing increases organic traffic to the wallet's site.
That's why everybody wants to get in. It's literally worth $ to us. On the other hand, I guess that's also why it's a tough decision."

I think this is a very good point. Why doesnt the EF create a voting system similar to that of https://dap.ps/

It would be an avenue for EF to obtain more funding, as well as give a fair method to curate the wallet listing. Since its EF's site, submissions are subject to auditing (can be paid for by votes) for approval to prevent malicious wallets and let users vote on which wallets get listed first.

**Comment by akatsuAK** [comment]
> Thanks for the thoughtful issue @p0s. I agree this is worth discussing & establishing a process. We welcome additional input from the community on this.
> 
> Another consideration for this solution (in addition to the ones you listed) is user experience. There's plenty of research out there on the adverse effects of choice, so it's a delicate balance to provide users with options but not so many that overwhelm them or lead to analysis paralysis. We do have a [RandomList](https://github.com/ethereum/ethereum-org-website/blob/dev/docs/.vuepress/components/RandomList.vue) component (which we use to shuffle the dapps we display) which may be an option to present an unbiased list. This, however, doesn't solve the core issue of curating a master list of wallets to display.
> 
> I think generally we do face similar issues for other resource sections of the site, so this could be a good way to set a precedent in terms of process. Inevitably there's some subjectivity in picking "winners" & "losers" of what is displayed on the site but to the best of our ability, I'd like to see ethereum.org maintain neutrality. Identifying quantitative metrics that answer [considerations we outline in our README](https://github.com/ethereum/ethereum-org-website#i-want-to-add-a-developer-tool-or-project) (Is it widely used? Is it well documented? Is it of sufficient quality?), whether those are self-reported in PRs or pulled from some 3rd party, might help remove the subjectivity of the process.

Is there any updates to the this?

**Comment by samajammin** [comment]
Reopening

**Comment by dannyexodus** [comment]
Hi all, I was directed to this issue from #1110 

Perhaps for curating wallets while not overloading the user with choices, EF could look at App Store/Play Store reviews? Or some other neutral indicator that shows that the wallet in question is popular and liked by users?

**Comment by ryancreatescopy** [comment]
**We've worked on a clearer framework for this process, we welcome your thoughts.**:

This is a draft of a policy for [ethereum.org](http://ethereum.org) about how we decide what wallets or dapps should be listed on the website. For instance, this policy would be used for:

- Deciding what wallets to list on ethereum.org/wallets
- Deciding which dapps should be listed on a page designed to on-board beginners
- Guiding our decisions (and responses) about PRs which add a wallet or dapp

This policy will be published in the github readme for ethereum.org, and be open for public comment. We'll expect anyone submitting a PR that adds a wallet or dapp to review this beforehand, and we'll refer to it when we have to reject a PR and explain why we did so.

## **Draft:**

Anyone is free to suggest new wallets and dapps to the content on ethereum.org, where it's appropriate to do so. **No, we won't list your dapp on our homepage** 😜

We currently list wallets and dapps on:

- ethereum.org/wallets
- ethereum.org/dapps

**Please only suggest new additions on these pages.**

Although we welcome new additions, we chose the current wallets and dapps based on an experience we're trying to create for our users. These are based on some of our design principles:

- Inspirational: we want what we list to offer something new to users
- A good story: we want what we list to provide an "aha" moment
- Credible: we want what we list to be legitimate businesses/projects to minimise risk to users

Overall **we want to provide a "seamless onboarding experience" for new users**. So for that reason, we add wallets/dapps based on their:

- ease of use
- interoperability with other products
- security
- longevity

Here's our decision framework in more detail. Please feel free to provide feedback or suggest changes.

# How we decide

### Criteria for inclusion: the must-haves

- [ ]  **An audited product** – this shows us that you take your code and your user's security seriously and reduces the risk to our users
- [ ]  **A product** **that has been "live" for over 6 months** (live might mean on main net for smart contract wallets) – this is another indication of security. We believe 6 months is a good timeframe for critical bugs and exploitations to have been found.
- [ ]  **Worked on by an active, funded team** – this helps ensure quality and that a user will get support with their queries.

### Criteria for ranking: the nice-to-haves

If we add your dapp or wallet it may not be listed as prominently as others. This is because we also consider the following criteria when designing our pages.

**Wallets**

---

- [ ]  **Fiat onramps** – this prevents a lot of potential friction in a new user's experience with a wallet. If we send users to a wallet that they need to fund via an exchange, it can be days before they can try the wallet, based on KYC times.
- [ ]  **Supported by majority of dapps** – our content aims to get users up and running with a wallet and eth before showing them dapps. If dapps don't support connecting with your wallet, it could ruin their experience.

**Dapps**

---

- [ ]  **You can access it via the majority of wallets we list** – this means the wallets we suggest to users will work for dapps we suggest too
- [ ]  **Users can try it out themselves –** we're not going to list your supply chain b2b app because users can't just try it out. An individual user should be able to use your dapp and achieve something tangible.

**Both**

---

- [ ]  **Onboarding** – you product should have a well-designed onboarding experience to help and educate users or evidence of how-to content (articles/youtube etc.)
- [ ]  **Open source** – your code should be accessible and you should accept PRs from the wider community
- [ ]  **Community** – you have a dedicated community, maybe a discord where users can interact with your team to get help, suggest new features etc.

# Criteria in practice

The more of the criteria you fill, the more likely we'll list your product. 

A product we list that only meets the must-haves may be removed if a new product is suggested that meets the must-haves and several of the nice-to-haves. 

Other things that will factor into this decision:

- Will adding rather than replacing break the UX of the page?
    - our site is primarily educational and the main purpose is to explain Ethereum and its relevant concepts. By adding too many options for users to click on we'll end up making our pages less readable and thus less useful.
- Does this page now paralyse the user with choices?
    - like when you sit browsing netflix for hours because you can't decide something to watch. We don't want to bamboozle users that are new to Ethereum by giving them too much choice.

This is a design decision that we alone are responsible for.

But rest assured, even if we don't list your product, **we'll provide prominent links to other websites in the ecosystem that rank all dapps/wallets for users that want to see more choices.**

# Maintenance

As is the fluid nature of Ethereum, teams and products come and go and innovation happens daily, so we'll undertake routine checks of our content to: 

- ensure that all wallets and dapps we list still fulfil our criteria.
- there aren't products that have been suggested that meet more of our criteria than the ones currently listed

You can help with this by checking and letting us know if we should update.

We're also investigating options for voting so the community can indicate their preferences and highlight the best products out there for us to recommend.

**Comment by p0s** [comment]
looks good to me! appreciate the thought you put into it!
