### ISSUE TITLE
Quiz content: Web3 page

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#7554]
This is a sub-task of: https://github.com/ethereum/ethereum-org-website/issues/7461

Prepare content for quiz on page:
https://ethereum.org/en/web3/

Each question should be related to the most important aspects of the page. There can be a unique explanation for each correct/incorrect answer.

**Comment by qbzzt** [comment]
What additional action do web3 sites allow that web2 sites typically do not?

A. Read
B. Write
**C. Own**
D. Search

**Explanations**

A. No, web1 sites were mostly static, but you could read them easily.
B. No. Web2 platforms, such as Wikipedia and Facebook, allow users to write content (which is then owned and managed by the platforms).
D. No, search is also supported on web1 and web2.

**Comment by qbzzt** [comment]
Can you control monetization of your content on web3? If so, how?

A. Put advertising on your site
B. Put all your content on the blockchain
**C. Use the blockchain to sell access to your content, which is stored elsewhere**
D. It is impossible to monetize web3 content

**Explanations:**

A. Advertising has existed since web1 days, and is the major source of revenue for web2.
B. Anybody can read anything on the blockchain.
D. You can sell access on web3.

**Comment by minimalsm** [comment]
Closing this out as part of #8094. I've migrated question suggestions here [to this Notion doc](https://www.notion.so/efdn/Review-Ori-s-learning-quizzes-suggestions-on-issue-79027459ef9f4f0a9b5ef384f3faf941) and will be updating decisions here.
