### ISSUE TITLE
Quiz content: Ethereum security and scam prevention

### ISSUE THREAD

**Issue by konopkja** [ethereum/ethereum-org-website#7557]
This is a sub-task of: https://github.com/ethereum/ethereum-org-website/issues/7461

Prepare content for quiz on page:
https://ethereum.org/en/security/

Each question should be related to the most important aspects of the page. There can be a unique explanation for each correct/incorrect answer.

**Comment by qbzzt** [comment]
Which of these is a good password?

A. MyVeryGoodPassword!!!
B. MyV3ryG00dP@ssw0rd!!!
C. QWERTYUIOP123!!!
**D.  8bv8&k6H7Z&m**

**Explanations:**

A. This password is primarily dictionary words
B. This password is primarily dictionary words. Hackers are very familiar with the trick of replacing letters with other characters. (E->3, A->@, etc.).
C. Keyboard patterns are the same as words, well known and as such subject to dictionary attacks.

**Comment by qbzzt** [comment]
If you send me 0.01 ether I'll send you back 100 ETH!!! Here, see these transaction (you can look them up), I've really done this. Which is *not* a way this could be a scam?

**A. The transactions are fake.**
B. The scammer sent 0.01 ether from another account he controls, and then sent 100 ETH back. Since he controls both accounts, he only really spent the transactions' gas cost.
C. The scammer created a fungible token following the ERC-20 standard, and set the symbol for it to `ETH`. One hundred of those worthless tokens put together are still worthless.

Explanation:

The answer is A. The transactions can't be fake, because the blockchain is an immutable ledger. If they give you a transaction hash and you look it up and it is there, it must have really happened.

**Comment by qbzzt** [comment]
You just got a message from Ethereum Support telling you your account is locked until you authenticate with them by signing a transaction. What shouldn't you do?

**A. Sign the transaction, you want to continue using Ethereum.**
B. Google for "Ethereum Support", see there is no such organization, and report them as spam / block them
C. Run a small transaction to verify that your account is not really locked
D. Lead them on, asking for additional details, to waste their time.

**Explanation:**

Whatever scammers want you to do is probably a bad idea.

**Comment by minimalsm** [comment]
Closing this out as part of #8094. I've migrated question suggestions here [to this Notion doc](https://www.notion.so/efdn/Review-Ori-s-learning-quizzes-suggestions-on-issue-79027459ef9f4f0a9b5ef384f3faf941) and will be updating decisions here.
