### ISSUE TITLE
Adding a Tutorial - Certified Blockchain Professional (C|BP)

### ISSUE THREAD

**Issue by Jfox32199** [ethereum/ethereum-org-website#7570]
Hi there,

Hope this finds everyone well and this is the right way to submit this request!

I'm getting in touch as I thought that the following course might make for a suitable tutorial. It's an online learning course that offers beginners an overview of what blockchain is, and the many ways in which it can be applied. One of the course modules specifically focuses on Ethereum as well, hence why I thought I should get in touch.

The course can be found at the URL below so please take a look and let me know if you can find a place for it.

https://www.coursesonline.co.uk/course-listing/certified-blockchain-professional-cbp-learning-people/?

Best,

Justin

**Comment by minimalsm** [comment]
Hey @Jfox32199, thanks for the recommendation.

I personally would be strongly against including this resource. There is no way to audit the quality of the material, and as far as I can tell **coursesonline** just churns out courses based on what they think people will buy (read: I doubt this is particularly high quality compared to other resources that we list) instead of carving out a niche where they are actually specialists. 

Also, they have fake 'someone just bought this course' social proof pop-ups, the pricing isn't transparent, and it seems to rely on a 'buy before you try' business model, which I don't think we should propagate on our website. The whole thing seems ethically dubious to me. 

Closing this out because I don't think anyone will be able to convince me this is worthwhile to add to ethereum.org, but happy to continue the conversation.
