### ISSUE TITLE
The landing page is poorly designed

### ISSUE THREAD

**Issue by texture** [ethereum/ethereum-org-website#76]
The top links are randomly placed, and it is unclear what the site is about. Attached is a slightly less poorly designed version of the landing page. 
![site1](https://user-images.githubusercontent.com/1937194/57737241-c4f6f380-765f-11e9-9844-bcd7fa40dcab.jpg)

**Comment by sneg55** [comment]
Why don't we create a gitcoin bounty for better landing page design?

**Comment by AlexBlokh** [comment]
current landing page design is brilliant and very professional

**Comment by texture** [comment]
> current landing page design is brilliant and very professional

Not on this planet it isn't.

**Comment by rossbulat** [comment]
Doesn't need a major overhaul, just revised placements:

1. Split the headline text into a title and then a longer subtitle akin to what is there already, and place it at the top, not below the logo.

2. The 4 links surrounding the logo can then be moved below the logo and aligned in a row with equal spacing.

Then the logo graphic could be expanded into various artwork transitions, or professionally designed explainer graphics, or what have you...

**Comment by rossbulat** [comment]
As an additional note, I like the style of the graphic, with the particle network effects subtly referencing the nature of a blockchain network.

Both effects can be easily re-created in Illustrator, and think a high resolution logo could be redesigned in the same way as the below graphic of a light bulb, albeit with more colour:

![vectorstock_20209188](https://user-images.githubusercontent.com/13929023/57971295-5a72ea00-79b6-11e9-8c30-1298306ee7ba.png)

**Comment by samajammin** [comment]
Hey folks - thank you all for your ideas here! I'm going to close this out given that the landing page has been updated since most of this discussion took place. There's a specific issue on cleaning up header styling (https://github.com/ethereum/ethereum-org-website/issues/203) that might address the headline issue mentioned. I also broke out the XL screen layout as a separate issue (https://github.com/ethereum/ethereum-org-website/issues/207). Feel free to re-open (or open new issues) if we've missed something that still applies to the current homepage. There's always room for improvement!
