### ISSUE TITLE
Unable to fetch number of transactions from etherscan api

### ISSUE THREAD

**Issue by SavPhill** [ethereum/ethereum-org-website#7677]
**Describe the bug**

On https://ethereum.org/en/what-is-ethereum/ under the title Ethereum in numbers, there is an 'error, please refresh' message where the number of transactions value should be displayed.

I believe this to be an issue with the api url which is presented as `apiUrl: "https://etherscan.io/",` on line 667 at https://github.com/ethereum/ethereum-org-website/blob/dev/src/pages-conditional/what-is-ethereum.tsx

This affects all translations and is presented on a high value page, therefore I believe it is important to be fixed. I can issue the PR if anyone can provide the correct API url.

**To Reproduce**

1. Go to 'https://ethereum.org/en/what-is-ethereum/'
2. Scroll down to the 'Ethereum in numbers' section

**Expected behavior**

It should pull the value from the etherscan.io api. 

**Screenshots**

![etherscan api issue ethereum](https://user-images.githubusercontent.com/38789408/188365978-f84362c9-bf9d-466a-8395-073d88d0a586.png)

**Desktop (please complete the following information):**

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]

**Smartphone (please complete the following information):**

- Browser: [e.g. stock browser, safari]
- Version: [e.g. 22]

**Additional context**

**Want to contribute?**

We love contributions from the Ethereum community! Please comment on an issue if you're interested in helping out with a PR.

**Comment by masaya-sasaki** [comment]
Great catch! This is my first contribution so please let me know if this is a good way of contributing!

I believe the "Error, please refresh" is shown because there is an error in the `GATSBY_FUNCTIONS_PATH` coming from [https://github.com/ethereum/ethereum-org-website/blob/dev/src/constants.ts](url) 

The message "Error, please refresh" is shown when the props txCount.hasError in <Stat stat={txCount} /> results to true. And since the txCount comes from the useFetchStat hook, seems like there is an error when fetching from the url using getData() in [https://github.com/ethereum/ethereum-org-website/blob/dev/src/hooks/useFetchStat.ts](url) I assume this is probably an error from the url rather than getData() because it's a new error. And this url input is GATSBY_FUNCTIONS_PATH coming from https://github.com/ethereum/ethereum-org-website/blob/dev/src/constants.ts 
I can't check the environment variables of Gatsby but my guess is there is some new changes with the endpoint that was initially set as GATSBY_FUNCTIONS_PATH maybe due to the merge?

**Comment by 0xkeivin** [comment]
after some checks, it seems the API call itself is fine as I can see the browser stored values for the transactions. 
![image](https://user-images.githubusercontent.com/65915812/190449017-5dc3110a-7bd5-4c11-86ee-068fee7381a8.png)

**Comment by 0xkeivin** [comment]
fix PR has been created here https://github.com/ethereum/ethereum-org-website/pull/7892 by another contributor 😃
