### ISSUE TITLE
Ethereum is a product

### ISSUE THREAD

**Issue by texture** [ethereum/ethereum-org-website#77]
This line should be removed from the guidelines: 
"Ethereum.org should not be a traditional product website like every other blockchain. There is no sales pitch."

Ethereum is as much a product as any other blockchain or open source project, see `apache.org`, `linux.org`, `python.org`, `angular.io`, etc... for preexisting projects which have. 

Rejecting everything currently known about the utility of websites and branding and pretending ethereum is immune to the need makes little sense. 

There are people right now who would love to pitch ethereum as a technology to their company and can't, because the website looks so bad, and they'd never be able to sell it to their boss. 

I've had C level executives reach out to me about this, it's not minor.

**Comment by sneg55** [comment]
I think that comes from "Ethereeum don't need marketing" narrative, while de facto Ethereum is a product and have to be marketed and represented as a product.

**Comment by dteiml** [comment]
Doesn't it say [Ethereum.org is not a traditional product _website_]?

**Comment by texture** [comment]
The distinction doesn't matter. The desired effect of the language is that the website continue to be designed poorly, which I would like to remedy.

**Comment by RockmanR** [comment]
I also felt embarrassed when I saw the site at the beginning. But when I understood the philosophy behind it, it provided a very strong message and vision. We might need to highlight that massage at the front page, educating people that this is driven by a thriving community.

Ethereum, if it continue to succeed, it's because of its community. And that will stay true as long as Ethereum is alive. Ethereum is not a product in the same way that, we, are not a product.

Some people will still not like the unprofessional/non-product look of Ethereum, but that will change when they see the outcomes.

**Comment by texture** [comment]
There is no reason the site needs to look bad to be in line with the philosophy.

**Comment by Anish-Agnihotri** [comment]
I'm going to take a stand with @texture on this one.

I understand that the basic philosophy of the website is to be a representation of a decentralized community, and that the website is not a "traditional product website", but that doesn't mean the website has to look like it's out of a Notion page.

The website can be aesthetically pleasing, simple, and keep the non-product look at the same time. We have to understand that this landing page is one of the first landing points for an outsider looking into Ethereum, and personally, it doesn't look like something I'd like an outsider to see. It really is not representative of the community.

**Comment by RockmanR** [comment]
I do agree that it's not representative, since the community is already much matured than that. I hope someone contributes and enhance it soon.

**Comment by Anish-Agnihotri** [comment]
I'm a web developer myself and posted on the [Gitter](https://gitter.im/ethereum/ethereum-org-website) a couple of days ago on whether the team would be open to a complete design overhaul (potentially a Gitcoin bounty, or something of the sort). With the new 2019-2020 funding guidelines published by the Ethereum Foundation, we should have funds to contribute towards that.

Personally, I'd be up to volunteer to completely overhaul the website. It's something I've been wanting to do for a couple of months and have been trying to get involved. If everyone is open to a complete design overhaul, I'll open up a couple of issues and a project board and get the process on the road.

Just want to make sure that we're open to ditching everything we have right now, since I was thinking of a complete overhaul from scratch.

**Comment by faraggi** [comment]
@Anish-Agnihotri I'd like to help you out with this and speak about some other specific ethereum.org website issues. I'll message you on gitter about that.

**Comment by jjmstark** [comment]
Hey all! We've revised the "core principles" in the readme.md for the site (#259), partly to address the good points raised in this issue. We've removed the "there is no sales pitch" language, and acknowledged that Ethereum is, among other things, a product.

The 3rd one now reads:

>3. Ethereum.org is not a typical product website
> - Ethereum is multifaceted. It's a project, a platform, a product, a vision of the future, a set of ideologies, a community, and much more.
> - The site won't look like every other product site, because Ethereum isn't like every other product.
