### ISSUE TITLE
add Balancer on dapp list

### ISSUE THREAD

**Issue by biancabuzea200** [ethereum/ethereum-org-website#7739]
Before suggesting a dapp, make sure you've read [our listing policy](https://www.ethereum.org/en/contributing/adding-products/).

Only continue with the issue if your dapp meets the criteria listed there.

If it does complete the following information which we need to accurately list the wallet.

**Please describe the measures taken to ensure the dapp's security and provide documentation wherever possible**
Balancer has completed full audits with Certora, OpenZeppelin, and Trail of Bits. 
Links to the audits can be found [here](https://docs.balancer.fi/security/audits).

**Is your dapp open source?**
Yes, the code has been open sourced under GPL3.0 license. The GitHub repo can be found [here](https://github.com/balancer-labs). 

**Can a user access the dapp without creating an account?**
Yes, users can simply connect with their Ethereum address.

**Are dapp funds non-custodial?**
Yes, users have full ownership of their funds. 

**Do you offer community support?**
Yes. Users can ask questions on [Discord](https://discord.com/invite/dctRMrn).

**Describe any geographical restrictions on usage of your dapp**
Jurisdictions on the Cayman/BVI sanctions block lists.

**Dapp title**
Balancer

**Dapp description**
Balancer is an automated portfolio manager and trading platform. Balancer turns the concept of an index fund on its head: instead of paying fees to portfolio managers to rebalance your portfolio, you collect fees from traders who rebalance your portfolio by following arbitrage opportunities.

**Dapp logo**
[Logo](https://drive.google.com/drive/folders/1o0F2RJuL--8H47odTnlLfgp4hq73kiRp?usp=sharing)

**Brand color**

Dark blue  #011F3B

Red  #ED2F58

Yellow  #FDD446

Blue  #3E73FB

Pink  #FF00FF

**Comment by minimalsm** [comment]
Hey @biancabuzea200 

Sorry for the delay here. Please check out the preview of #8523 to ensure you're happy with the change. 

Primarily: we had to shorten the description from: "_Balancer is an automated portfolio manager and trading platform. Balancer turns the concept of an index fund on its head: instead of paying fees to portfolio managers to rebalance your portfolio, you collect fees from traders who rebalance your portfolio by following arbitrage opportunities._" to simply "_Balancer is an automated portfolio manager and trading platform._" to fit [our current design.](https://ethereum.org/en/dapps/)

**Comment by biancabuzea200** [comment]
Hello all,

Thank you very much for assisting with this. Could you please change the
description to "Your DeFi liquidity infrastructure" instead, please?

Kind regards,
Bianca
