### ISSUE TITLE
Visual regression in markdown tables

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#8030]
### Describe the bug

The markdown table has visually regressed and is no longer displaying as intended. 

- Lines that divide rows are missing
- Content isn't aligned correctly

You can [see how it displayed before in this preview](https://ethereumorgwebsitedev01-networkupgradescomponent.gtsb.io/en/nft) versus [how the markdown table displays now.](https://ethereum.org/en/nft/)

### To reproduce

1. Go to https://ethereum.org/en/nft/
2. Scroll down to [the NFT comparison table](https://ethereum.org/en/nft/#nft-comparison)
3. See visual regression

### Expected behavior

The table should be correctly formatted ([as per the previous visual style](https://ethereumorgwebsitedev01-networkupgradescomponent.gtsb.io/en/nft)) dividers between rows and left aligned.

### Screenshots

Current:

<img width="1124" alt="Screenshot 2022-09-26 at 11 37 24" src="https://user-images.githubusercontent.com/62268199/192256208-d076888d-8362-4037-b8a5-e9c5b9afa985.png">

Before (expected):

<img width="1057" alt="Screenshot 2022-09-26 at 11 37 33" src="https://user-images.githubusercontent.com/62268199/192256211-2d22e1ec-5167-41ed-b720-2cf9ff0bbf7c.png">

### Additional context

I suspect this happened as part of [the migration to Chakra.](https://github.com/ethereum/ethereum-org-website/issues/6374)

**Comment by pettinarip** [comment]
Good catch.

[These](https://github.com/ethereum/ethereum-org-website/blob/v4.11.1/src/styles/layout.css#L573) were the global styles that we had that weren't migrated to the chakra theme.

We should place them in the new place for global styles: https://github.com/ethereum/ethereum-org-website/blob/dev/src/%40chakra-ui/gatsby-plugin/styles.ts

----
However, these global styles should be only temporary since what we really should do is to implement the native Chakra table component and apply those styles to it. This should also deprecate the usage of the `MarkdownTable` component.

**Comment by heeckhau** [comment]
@pettinarip This issue can be closed. It looks OK now
