### ISSUE TITLE
Wrong formating in run a node page

### ISSUE THREAD

**Issue by BenedettiLucca** [ethereum/ethereum-org-website#8168]
### Describe the bug

The subtitles in the [requirements section](https://ethereum.org/en/developers/docs/nodes-and-clients/run-a-node/#requirements) are in a weird format.

### To reproduce

1. Go to 'https://ethereum.org/en/developers/docs/nodes-and-clients/run-a-node/'
2. Scroll down to 'Requirements'
3. See error

### Expected behavior

Subtitles should appear in correct format.

### Screenshots

![image](https://user-images.githubusercontent.com/108427035/193879815-9bafa1a4-9260-4d60-be73-4bebdc8fa6d2.png)

### Desktop (please complete the following information)

- OS: Linux
- Browser: Brave

**Comment by Giorgionocera** [comment]
The same thing happens also on 'https://ethereum.org/en/developers/docs/oracles' and other pages.
I gave a look at the code and it seems to happen since it is not possible to convert the title of "h5" (5 hashes, `#####`)
`##### Minimum requirements {#minimum-requirements}` to link. 
It seems that the acceptable value of heading for such a link type is up to "h4" (from 1 to 4 hashes).

What do you think is the best solution:
1. To remove the link? 
2. or move these links from h5 to h4? 

Obviously, the second solution will modify the hierarchy of the posts.

**Comment by BenedettiLucca** [comment]
> What do you think is the best solution: 1. To remove the link? 2. or move these links from h5 to h4?
> 
> Obviously, the second solution will modify the hierarchy of the posts.

Removing the link won't hurt, messing with the hierarchy seems like a bad course of action.

**Comment by corwintines** [comment]
Hey @giorgionocera! Sorry for late reply here, but your intuition is right, we want to remove the h5 tag formatting for now (ex: {#} after the heading, this is what generates the link).

Will review your PR and push up any missed ones I can find. Thanks!
