### ISSUE TITLE
Chakra - incorrect disabled button styles when hovered

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#8295]
### Describe the bug

[Related comment](https://github.com/ethereum/ethereum-org-website/issues/6374#issuecomment-1283076384)

Our disabled button styles are not working as expected when hovered. This seems to be a [known Chakra issue](https://github.com/chakra-ui/chakra-ui/discussions/5211).

### To reproduce

1. Hover over a disabled button
2. See that the hover styles are applied

### Expected behavior

We don't want to apply the hover styles when the user hovers on a disabled button. We want to keep the disabled styles.

### Screenshots

![image](https://user-images.githubusercontent.com/468158/196728935-75200156-5f42-44b6-9eb8-e58d0564dc0e.png)

### Additional context

Apply the solution described in [this issue](https://github.com/chakra-ui/chakra-ui/discussions/5211).

**Comment by amit-ksh** [comment]
I'd like to work on this issue.

**Comment by pettinarip** [comment]
Assigned @amit-ksh thanks!

**Comment by TylerAPfledderer** [comment]
Hey @pettinarip and @wackerow !

The PR is warranted here, but would like to share some thoughts about this topic, should this styling need to be addressed in the future. I had discussion with other Chakra collaborators on this to get other thoughts at this time.

The behavior with the `_hover` styling still being applied with the `_disabled` styling is expected in general CSS and not specific to Charka. Pseudos like these do not inherently have conditional internal logic (outside of `:not()`). The approach given in the shared discussion and what @amit-ksh provides in his PR are inline with the default theming config of the [Chakra `Button` component](https://github.com/chakra-ui/chakra-ui/blob/main/packages/components/theme/src/components/button.ts). Note that the nested `_disabled` is applied in `baseStyles` and the variants, which renders `&:hover[disabled]` chaining and similar.

The logic of course being that if you "hover" over the element, then if the element is "disabled" apply these styles instead! 👍🏼 Unfortunately it means duplicating styles here

Chakra currently does not have a mechanism or logic globally or otherwise to have `_hover` styles be ignored if the element is disabled. Nor are there any pseudo props that use the `:not()` selector.

I can not speak for Sage or Lazar whom are the maintainers in the best approach for Chakra in addressing this, as we have not heard any thoughts directly from them. Just wanted to share current observations! 😄

**Comment by pettinarip** [comment]
Cool, thanks for the context @TylerAPfledderer. I think the logic makes sense now that you've explained it. Hopefully, there is an easier/cleaner way of dealing with it in the future but for now, this is fine as well.
