### ISSUE TITLE
Bug report - Uninformative link

### ISSUE THREAD

**Issue by JoshDavisLight** [ethereum/ethereum-org-website#8323]
### Describe the bug

"Correlation penalty" linked text on [Consensus Mechanisms](https://ethereum.org/en/developers/docs/consensus-mechanisms/pos/) directs to the Gasper paper, which doesn't have any immediately relevant information regarding correlation penalties. A search of the pdf for the string "correlation penalty" turns up 0 results.

### To reproduce

1. Go to [Consensus Mechanisms](https://ethereum.org/en/developers/docs/consensus-mechanisms/pos/)

3. Scroll down to Crypto-Economic Security'
4. Click on 'correlation penalty'

### Expected behavior

Clicking on the link should bring a user to a page with more information about what a correlation penalty is

### Additional context

Consider removing the link or finding another resource with more concise information regarding correlation penalties.

**Comment by emmanuel-awosika** [comment]
Hi @JoshDavisLight. Thanks for pointing this out. I just replaced the link with a new one pointing to [this resource on correlation penalties](https://eth2book.info/bellatrix/part2/incentives/slashing#the-correlation-penalty). Turns out the inactivity leak links to points to the same paper, but it has new link pointing to a [more descriptive resource](https://eth2book.info/bellatrix/part2/incentives/inactivity). 

Let me know if this solves the issue.

**Comment by corwintines** [comment]
Closed with above PR
