### ISSUE TITLE
Inconsistent padding/margin on docs pages

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#8364]
### Describe the bug

The padding of the opcodes page looks off:
https://ethereum.org/en/developers/docs/evm/opcodes

### To reproduce

1. Go to https://ethereum.org/en/developers/docs/evm/opcodes
2. See margin/padding of main content

### Expected behavior

Should look same as other docs pages.

### Screenshots

Opcodes page:
![Image 2022-10-25 at 10 29 18 AM](https://user-images.githubusercontent.com/8097623/197817103-7ffd31ec-15f1-4a8f-a13d-3aa1638efaa5.jpg)

Normal page:
![Image 2022-10-25 at 10 29 35 AM](https://user-images.githubusercontent.com/8097623/197817128-bee6c3b8-2bfd-4c91-ab03-63582060394f.jpg)

### Desktop (please complete the following information)

Brave MacOS

### Additional context

Perhaps a result of https://github.com/ethereum/ethereum-org-website/pull/8332 ?

**Comment by samajammin** [comment]
Now that I compare multiple pages, it seems to be inconsistent across doc pages:

https://user-images.githubusercontent.com/8097623/197817622-3d71ef87-0a8c-4d07-9137-56a7599544eb.mp4

I wonder if we're doing some sort of centering of the main content? I believe the layout should be consistent on every page (i.e. the same padding/margin between the left menu & the main page content).

**Comment by TylerAPfledderer** [comment]
Hey @samajammin!

I reverted the code for that table to pre Chakra migration, and it does not appear to be a part of the issue.

Along with that `margin: 0 auto` on the main content, there is the change in width of the right-side sticky TOC due to change in length of the longest text string for each page header.

A possible solution is to remove the `margin: 0 auto` from the [`Content` component](https://github.com/TylerAPfledderer/ethereum-org-website/blob/53c34ed3d8b6025128011cd9f6a8166206a4048a/src/templates/docs.tsx#L74) and add 100% width to the TOC.

Though maybe it will look weird for the opcode page because the content width could look too short without that TOC rendered? 🤔

**Comment by amit-ksh** [comment]
Can I work on this issue??

**Comment by pettinarip** [comment]
I agree with @TylerAPfledderer that the issue seems to be on TOC component by not having a fixed width. The other components (Sidebar & Content) do have a fixed width.

IMO the solution is to set a width to the TOC and let the `margin: 0 auto` fills the remaining content.

=====
Assigning it to you @amit-ksh ty

**Comment by samajammin** [comment]
Thanks for the input @TylerAPfledderer & offer to help @amit-ksh!

> IMO the solution is to set a width to the TOC and let the margin: 0 auto fills the remaining content.

So @pettinarip do you think the TOC component should have a horizontal scroll if the text is long? The text length often varies across pages/translations.

**Comment by amit-ksh** [comment]
https://user-images.githubusercontent.com/91947037/198305776-a0bd5ecf-ff1f-4f64-b39d-fbe908a6ca8c.mp4

Why all the pages are not responsive except the `Intro to Ethereum` page? 
And also I tried setting the width of the TOC component but the pages are behaving still the same way.

**Comment by amit-ksh** [comment]
Hey @pettinarip and @samajammin! I tried your solution but it's not working, instead giving a small width (like  `100px`) to the `Content` component is fixing this issue.

https://user-images.githubusercontent.com/91947037/198863468-f1e92d00-73a3-4899-a76e-937c06524b1c.mp4

**Comment by nloureiro** [comment]
My take on this is that the solution is to have a fixed width on the table of contents. That's the component that swings width depending on the length of the content.

On the Design system, I propose a fix:
1)  Keep the content left aligned to be close to the left navigation
2) give a max-width to the table of content: let's try 16rem/256px 

screencast of the fixed tables of content width using devtools

https://user-images.githubusercontent.com/1120748/202168523-547ac4f3-9a4b-46b1-a169-c0c3f1121dc6.mov




Screenshot of my idea on Figma:
![Screen Shot 2022-11-16 11 12 42 AM](https://user-images.githubusercontent.com/1120748/202167073-6d45909b-acb1-4a31-b401-12a2ee739fb1.png)

Link to the figma board:
https://www.figma.com/file/NrNxGjBL0Yl1PrNrOT8G2B/ethereum.org-Design-System?node-id=1585%3A28670&t=guK4RourloAwzhDQ-1

@pettinarip do you think this can be fixed now? or we close the issue and wait for the EPIC to implement the design system?

**Comment by Aathirajan** [comment]
guys anyone working on this issue? @amit-ksh are you?

**Comment by amit-ksh** [comment]
@Aathirajan, I already linked a PR for this issue.

**Comment by Aathirajan** [comment]
Yeah thanks!

**Comment by DebabrataHalder** [comment]
Has this issue been resolved ?
