### ISSUE TITLE
Rethink "ETH is valuable because:" learning quiz question

### ISSUE THREAD

**Issue by minimalsm** [ethereum/ethereum-org-website#8456]
![unkno21312wn](https://user-images.githubusercontent.com/62268199/199565191-18115e6e-6ef2-43a3-97b7-b0fbaaf3f61f.png)

Received some feedback regarding this question:

> I was voting "A" - which was deemed wrong. Bit of a weird question IMHO. "C" should maybe be "ETH is used as a collateral for some crypto loans" (think PWN) - but tbh I would drop this question completely - also for "B"

Worth noting that each answer should be backed entirely by the content of the page (see the [Why does ETH have value? section](https://ethereum.org/en/eth/)). We should not introduce new information into **the answers** that is not contained on page (within the explanations is fine).

Some things to consider when evaluating critiques of the learning quiz answers we have:

1. The answers do not accurately reflect the content 
2. The content is inaccurate or misleading
3. The criticism is invalid

I'm leaning towards number one (answers do not accurately reflect the content) in this case.

**Comment by ligi** [comment]
As the author of the feedback quoted I also lean to 1 and completely removing the question

**Comment by wackerow** [comment]
@minimalsm To your comments about how these should reference/enforce content from the page:

> ETH is needed to do anything on Ethereum

↳ "For users of Ethereum, ETH is valuable because it lets you pay transaction fees."

> ETH is an un-censorable peer-to-peer money

↳ <img width="439" alt="image" src="https://github.com/ethereum/ethereum-org-website/assets/54227730/a3b3c081-29ab-4698-8984-b9b97625b677">

> ETH is used as collateral for crypto loans

↳ "You can use ETH as collateral to generate entirely different cryptocurrency tokens on Ethereum. Plus you can borrow, lend and earn interest on ETH and other ETH-backed tokens."

From my view, these answer choices are all supported by the [content](https://ethereum.org/eth). Given that, I'd suggest we either adjust the wording of the question, or answer choices to make it more explicitly aligned with the copy, or if we disagree with the copy then we should change that. 

@minimalsm going to assign you for now... If you think this needs updating, please feel free to re-assign to me or whomever, but otherwise I'd request it be closed. 🙏
