### ISSUE TITLE
Quiz: Which iteration of the web does not rely on third-party payment providers?

### ISSUE THREAD

**Issue by ligi** [ethereum/ethereum-org-website#8458]
### Describe the bug

![image](https://user-images.githubusercontent.com/111600/199570399-0c55d23d-dfa1-47cc-aabf-2ac5eae94133.png)

IMHO here "D" is most correct - also web1 and even web2 does not really really rely on third-party payment providers. Maybe if you think about how to buy the hardware - but this is also still true for web3 mostly. But I would just remove the question completely ..

### To reproduce

Go to: https://ethereum.org/en/web3/#quiz

### Expected behavior

don't see this question

**Comment by wackerow** [comment]
> web1 and even web2 does not really really rely on third-party payment providers

Agree they don't "rely" in the strictest sense of the word, as they don't require support for payments... but in order to support payments, web3 is the only that supports them without third-party payment providers, which to much understanding here is the point of the question.

Going to close this out for now, but can re-open if further discussion unfolds.
