### ISSUE TITLE
Quiz: From the options presented, which is the most secure way to store your seed phrase?

### ISSUE THREAD

**Issue by ligi** [ethereum/ethereum-org-website#8461]
![image](https://user-images.githubusercontent.com/111600/199575363-74163c0c-e887-4fcf-ac49-1864547cf48a.png)

IMHO this really depends (e.g. who can get access to that paper) and I would completely remove that question.
We should get people to do shamir backups (when really encouraging seeds) instead of writing down the seed somewhere.

**Comment by wackerow** [comment]
The quiz here is targeting a less-advanced audience; wouldn't recommend we go down the shamir backup path for that reason... I do agree this is somewhat dependent on the individuals setup, but the overall point trying to be made with this question is that storing in a digital form opens yourself up to a lot of possible long-range attacks via the internet, as opposed to only attacks that require in-person access. 

Perhaps an adjustment to "Of the options shown, which method of backup is least vulnerable to attacks over the internet?"

cc: @konopkja This is targeted to beginners; assigning you to this. If you feel this is overkill we can close out, but otherwise please feel free to drop your thoughts and we can adjust as needed.

**Comment by konopkja** [comment]
Yeah this is a stale mate situation as we have many times discussed, there are very few to none **"safe"** options for storing recovery phrase for beginners when we consider possibilities for **human error** as part of the **basic security model**. Many times that outweighs the risk of being attacked.

I would recommend updating the answers and question based on simulator on this page:

What is the safest way for beginner with limited funds to store recovery phrase

✅ Consider saving in a password manager
❌Texting it to a friend (or anyone!)
❌Taking a picture of the phrase
❌Saving it in a file on your computer
