### ISSUE TITLE
Header permalinks do not always work

### ISSUE THREAD

**Issue by carlfairclough** [ethereum/ethereum-org-website#858]
It appears that some permalinks are not working.

**To Reproduce**
1. Visit https://ethereum.org/wallets/
2. Click the `What is an Ethereum wallet, and which one should I use?` permalink icon
3. See that nothing happens — the url is followed by `%3F` which is not in the heading id

**Expected behavior**
The link should go to the heading

**Comment by samajammin** [comment]
Mmmm I was a bit worried about this. I suspect the [addition of markdown-it-attrs](https://github.com/ethereum/ethereum-org-website/commit/8a115702638d6f0bd29a800facf50c9b66283edb) broke these header IDs since the use of bracket notation creates clashes.

We already use bracket notation on markdown headers to [set explicit header ids](https://github.com/ethereum/ethereum-org-website/pull/369) (in order to keep anchor tags consistent across languages. More context on that feature can be found in the [related issue](https://github.com/ethereum/ethereum-org-website/issues/272).

I wonder the best way to resolve this. @carlfairclough do you feel the `markdown-it-attrs` package is necessary? Perhaps we could use a symbol other than brackets to generate these markdown header IDs.

**Comment by carlfairclough** [comment]
I'd be keen to keep `markdown-it-attrs` or roll-our-own version of it, otherwise people won't be able to leverage styles so easily. An alternative _could_ be `classy` https://github.com/andrey-p/markdown-it-classy.

I'm unsure as to why manually adding IDs to each heading is necessary when it can be done automatically — why do anchor tags need to be consistent across languages, vs being relevant to the content on the page?

**Comment by samajammin** [comment]
I think I found a fix - PR coming shortly

**Comment by samajammin** [comment]
Re: the need for explicit IDs - does [this issue](https://github.com/ethereum/ethereum-org-website/issues/272) not answer that question? Happy to explain if it doesn't.
