### ISSUE TITLE
Incorrect spacing in Card component

### ISSUE THREAD

**Issue by pettinarip** [ethereum/ethereum-org-website#8697]
### Describe the bug

We tried to fix this issue on a [previous PR](https://github.com/ethereum/ethereum-org-website/pull/8132) but it looks like it is not covering correctly all the cases.

### To reproduce

1. Go to https://ethereum.org/en/staking/solo/#why-stake-solo
2. See incorrect spacing styles

### Expected behavior

The 3 cards should not have any spacing between the title and the content of the Card.

Like this:
![image](https://user-images.githubusercontent.com/468158/203077552-0c988378-2e6b-49b6-a639-ab04037139c9.png)

### Screenshots

Current styles:
![image](https://user-images.githubusercontent.com/468158/203076952-d8079fdb-9e46-4b3a-a59b-d6426bf39636.png)

### Additional context

Double check #8132 since it is related to this issue.

**Comment by TylerAPfledderer** [comment]
I have a couple of thoughts here! 😄 

I'm wondering, because there are components involved that are rendered in the `Card` via `children`, maybe they need to apply their own spacing styles versus letting `Card` do most of the heavy lifting.

Between the two site pages being referenced here and in the related GH Issue, the quick solution I see is to remove `justifyContent` within `Card` and apply `marginTop: 'auto'` to the buttons in the `/developers` page.

I'm also thinking that on survey of some other pages, that the button could be conditionally rendered within `Card`. And can have a `buttonOptions` prop to supply needed props straight to the button.

**Comment by corwintines** [comment]
Closing as PR has been merged
