### ISSUE TITLE
Use POAP to issue badges to contributors

### ISSUE THREAD

**Issue by samajammin** [ethereum/ethereum-org-website#872]
**Is your feature request related to a problem? Please describe.**

This was discussed in #362 as a way to recognize project contributors. We ended up starting with the [All Contributors](https://allcontributors.org/docs/en/overview) bot & spec which has been an easy first step. 

Distributing [POAP badges](https://www.poap.xyz/), though a more resource intensive process, could be a fun & novel way to show love & appreciation to our community contributors while leveraging Ethereum's unique capabilities.

**Describe the solution you'd like**

Issuing POAP badges would involve 3 primary steps
- [x] Design POAP badges
- [x] Figure out a way to collect ETH addresses from [our list of contributors](https://github.com/ethereum/ethereum-org-website/blob/dev/.all-contributorsrc )
- [x] Mint POAP badges (ERC721 tokens) for each contributor's contribution type & distribute to our contributor's ETH addresses

**Which also begs the question: what kind of POAP badges should we issue? What contribution types should we include?**
Open to ideas here but I propose we start by creating badges for the [same contribution types as All Contributors](https://allcontributors.org/docs/en/emoji-key), which [we already have already have documented records of](https://github.com/ethereum/ethereum-org-website#contributors). From there we may eventually decide to create badges within those categories, e.g. instead of just a badge for "translation", a badge for "Arabic translation" & each language individually but I feel the top-level categories of [All Contributors](https://allcontributors.org/docs/en/emoji-key) is a solid starting point.

**Describe alternatives you've considered**

We considered [All Contributors](https://allcontributors.org/docs/en/overview) in #362 & implemented in #405

**Additional context**

https://www.poap.xyz/

**Comment by samajammin** [comment]
The POAP folks have kindly created icons for our first round of badges 🎉 
https://drive.google.com/drive/folders/11sqONNnPUaBijBcrtHAx_KRmMPIVV1vd?usp=sharing

**Comment by samajammin** [comment]
Note from Patricio of POAP:

> To be compliant with the POAP spec (not a real spec) we must set a date when all the tokens are issued and a post is published. After that we still can issue backdated tokens for accounts we missed or for other reasons. What we couldn’t do is to use the same token in on-going manner with new contributors getting it. For new contributors that became awardees after the cut-off date we should issue a new token later in time. The reasoning behind this mechanic is that all POAP tokens are meant to be a recollection of some event, physical or virtual, that happened in the past.

**Comment by poapxyz** [comment]
(Patricio Worthalter here) We improved the POAP NFT claiming process lately and we can offer a new alternative that doesn't require gathering the Ethereum addresses of all the contributors.

The token awardees should be sent a link to http://poap.xyz/claim/web42h (varying the six digits at the end of the url) and that would lead them to a wizard for getting the token.

Unfortunately GitHub doesn't have an internal messaging system so they can't be sent straight from their profiles.

I'm open to iterate this further to move it forward.

**Comment by samajammin** [comment]
@poapxyz that's great! Are the links one-time use? So now it's just a matter of getting contributor contact information in order to privately send them these links?

**Comment by poapxyz** [comment]
The links are one-time use, yes. Only caveat is that is one link per token so if someone contributed in two categories, we would send two links and awardee would have to run the claim process for each token. Not much of a problem really. Besides that, we are ready to produce the links immediately.

Requirements:
* Amount of links to be created for each category
* Designation of a trusted individual to deliver the links to contributors privately.

**Comment by samajammin** [comment]
Hey @poapxyz - this is still on our radar but currently not a top priority.

We do not have personal contact information for any of our contributors, but we do have a list of their Github profiles here: https://github.com/ethereum/ethereum-org-website#contributors

If your team has capacity, you're welcome to conduct a trial run of this. That list of contributors will show you how many POAP tokens are needed to issue for each category. Then you could reach out to folks (via their email address in their GH profile) & send them a link to claim their tokens. Perhaps we start with a small subsection of the contributors & see if anyone is able to successfully claim their badge?

**Comment by poapxyz** [comment]
To keep POAP relevant while no physical events are happening I started on boarding virtual meetup organizers. The model was quickly validated and for the past three weeks I found myself working around the clock to make sure everything goes well. Every day someone new reaches out to learn how to issue POAPs for their events.
This means I can't take the responsibility of this distribution. 

From our side everything is ready. Whenever someone is ready to start, we make the codes available for distribution right away.

**Comment by samajammin** [comment]
@poapxyz totally understandable. Glad to hear you're getting traction there!

I'll update here if this becomes something we have capacity for. Please let us know as well.

**Comment by poapxyz** [comment]
Sam, ﻿your answer telegraphs certain disinterest and at this point, and, after you made me put so much work in this, I feel mistreated.

Since November 2019 when this started you commanded me to a disproportionate amount of work, making me jump thru wearing hoops (Started on Telegram, moved to red-tapish emails with different people, then Github) always passing the ball and barely taking responsibility on the project. You even made me learn the hierarchies of the Ethereum website contributors and others peculiarities of your job, so I could create a proposal for you. As if I didn’t have better things to do. Figure it was you who engaged to me to start this project and POAP is a product that’s been used by 10s of people around the community with a typical on boarding consisting on 10 of my time. I not only created the best proposal I could with the shitty supporting materials I was given. To make it better I hired from my own pocket a professional $200/hour illustrator to come up with 3 sets of badges for you to chose from. Only after I expressed my disappointment and frustration about working with you to third parties, you appeared again just to do nothing after.

In all honesty:

1) I wish you wouldn’t have reached out in the first place and all this unpleasant experience I had of dealing with you until now hasn’t happened.
2) You were very disrespectful and inconsiderate putting me to work on something you weren’t interested at all and that you were going to essentially block with your inaction.
3) Halfway thru the project it would have been better if you had taken a loss by putting it to death. By iterating indefinitely while keeping hands off you just added more pressure. You saw me in both ETHDenver and ETHcc and I would have accepted an apology if I was explained that this shouldn't' have been started because you weren’t going to be able to do your part.

All this off my chest, I try to be a pragmatic person, so:

1) I think the project conceptually makes sense.
2) From the POAP side everything is ready to be executed as it always was.
3) I’m open to work with you or anyone else to help this finally happen.
4) People from all around the world are using POAP for engaging with their communities and the outcomes of those engagements are all positive. Your organization can only benefit from it.

**Comment by samajammin** [comment]
@poapxyz I'm sorry (and surprised) that you feel this way but I appreciate your candor. I know this initiative has dragged on. I didn't anticipate that this project would continue to get de-prioritized for our team but I should have done a better job communicating with you & setting expectations around that.

That said, claiming that I "commanded" you to do anything feels a bit dramatic & offensive. From the outset, I tried to be clear that we are a small team without much capacity but if you were willing & able to drive it forward, it seemed like a potential win-win for both of our teams. You outright offered to put forward a proposal for this project & to take the lead. In your own words of the proposal (back in November):
> Sam suggested that I champion this effort because he was very busy with other tasks

I am sorry you feel disrespected through all this. That was never my intention. I admit it has been disappointing that it hasn't been an area of focus for us but please understand I'm not the only (or ultimate) decision-maker when it comes to the priorities of ethereum.org. I will continue to advocate for this project but I cannot make any promises on when we will have the capacity to accomplish this.

I do appreciate your willingness to still work with us to make this happen. Re: next steps, my understanding is that we still need to:
1. Issue a POAP token for each category & contributor combination
2. Generate URLs for contributors to claim their tokens
3. Send the URLs to contributors via email (if an email address is present in their Github profile)
Anything I'm missing or overlooking here? 

I believe we'll need you to execute steps 1 & 2. Is there anything you need from me on this?

Step 3 I can start on once I have the URLs but again, please realize I'm the sole developer & sole full-time member on this team. 

Thank you in advance for your patience & cooperation.

**Comment by samajammin** [comment]
Here's a breakdown of current contributor count by category:
- Translation: 46
- Content: 103
- Code: 25
- Review: 8
- Infrastructure: 1

Full breakdown here:
https://docs.google.com/spreadsheets/d/1DNCuxOlucUF_lN6tkqJJ8cb8RNUeSsjom9gUtMT4Euo/edit#gid=1421770461

**Comment by samajammin** [comment]
Update on this -  I've put together a spreadsheet with all the POAP claim URLs & contributor contact info that we can use to track our outreach efforts. The one holdup at the moment is gas fees... here's the blurb POAP pops when I tried to claim my NFT: https://share.getcloudapp.com/04uq5Rx4

I think we hold off on this until their scaling solution is in place @jjmstark @ryancreatescopy

**Comment by poapxyz** [comment]
My suggestion is to start the distribution ASAP.

Once the medalla testnet reaches 300000 blocks and people claim their validator POAPs we well be running a campaign with strong incentives. People that hold POAPs that represent commitment to the ecosystem will be randomly rewarded with juicy prizes. 

This is independent of the migration to a second layer.

**Comment by samajammin** [comment]
@ryancreatescopy @jjmstark - see comment above. Let's prioritize this initiative next sprint?

**Comment by poapxyz** [comment]
POAP now mints on xdai so the redemption process has no cost for the recipient. More info: https://twitter.com/poapxyz/status/1312068839199318016?s=21

**Comment by poapxyz** [comment]
I would like to know the status of this. I see some have been claimed already. We are wrapping up some campaigns on which this POAPs will be participating and it's important to know when is the distribution expected to end.

**Comment by wackerow** [comment]
Yes! The POAP experience since this xDai upgrade has been so much better, curious myself where this is at and if there is any way to help

**Comment by samajammin** [comment]
Thanks for your interest @poapxyz @wackerow!

@GeorgeTrotter could you please provide an update here? George has been leading our outreach initiative on this over the past few weeks. I know it's been a challenge to track down contact information of contributors but I believe a fair amount of folks we've contacted have claimed their POAPs.

@poapxyz - do you have access to analytics around claimed POAPs to help us measure the success of our outreach? Otherwise I noticed going to the claim URL will show if it's been claimed or not, so once our outreach is complete we could visit each URL to verify & calculate our "conversion" rate.

**Comment by GeorgeTrotter** [comment]
Yes! We have sent out quite a few but there's still a way to go. I'm happy to make it a priority over the coming days @poapxyz. We'll have them all sent out by the end of next week and probably before that, although I don't expect them all to be claimed at that time of course.

**Comment by poapxyz** [comment]
Very nice. Thanks everyone. My main concern was equality of opportunity. Meaning that we need to make sure that everyone who was elegible for a POAP got the chance of redeeming it. It would be totally unacceptable that someone missed his ability to participate/receive a benefit because his POAP deliver was in a backlog.

So based on this new information we assume that in 10 days everyone who was elegible got his redemption link.

George: if by November 3rd for some reason there are still links pending to be sent please post a warm in this thread.

**Comment by wackerow** [comment]
@GeorgeTrotter Is there a method in place to collect addresses?

**Comment by GeorgeTrotter** [comment]
@wackerow We're working off contributors on Github, using the contact info they provide here to send them claim URLs directly.

**Comment by wackerow** [comment]
@GeorgeTrotter Oh that's right, that lets them fill in their own address... done it myself, didn't even think about it 🙄
That's great though, thanks for heading this!

**Comment by GeorgeTrotter** [comment]
Hey @poapxyz, what happens to these links/the tokens when your related campaigns wrap up? We're giving some thought to people who don't open the email right away/we can't find contact info for, wondering if there are ways we can accommodate them or give us the ability to distribute later. P.S. still making good progress, will keep you updated this week!

**Comment by poapxyz** [comment]
The links don't have any sort of expiration functionality. This means that as long as our centralized backend engine is up, they will work fine.

**Comment by GeorgeTrotter** [comment]
Hey @poapxyz! We finished our first pass through distributing to contributors today. Some people have no contact info, some people have awkward contact info, we've been tweeting about including ways to contact on github in hopes of getting in touch with these people. All to say that we'll continue to reach out but most people ought to have received the links. We'll give it a few days and then check to see how many were opened!

Thanks for your patience with all of this, I know it took a while. Just to make sure there are no crossed wires here, you say the links don't have expiration functionality, so that as long as your centralized backend engine is up, they'll work. Do you have any plans to take the backend engine down in the future or do you expect the links will continue to work moving forward?

**Comment by poapxyz** [comment]
Great to hear this has moved forward. Your efforts are appreciated (by POAP and probably by the recipients).

We don't have plans for taking down the backend. The mention of that is just a formality to acknowledge that an unclaimed POAP code doesn't have the same availability guarantees that a blockchain-based NFT POAP does.

**Comment by wackerow** [comment]
@GeorgeTrotter just updated my GitHub settings 😉
Thanks again for this!

**Comment by poapxyz** [comment]
Lots of POAPs of this campaign have been claimed already. Statistics:

https://poap.gallery/event/219
https://poap.gallery/event/217
https://poap.gallery/event/218
https://poap.gallery/event/215

**Comment by GeorgeTrotter** [comment]
This is great! Thanks for sharing!

**Comment by samajammin** [comment]
Thanks for sharing that info @poapxyz! Amazing to see 🤩 

@GeorgeTrotter everyone has been contacted, correct? Can we call this a win & close out the issue? Or is there more action items left?

**Comment by GeorgeTrotter** [comment]
Not everyone has been contacted due to lacking contact info. But provided that the links will continue to function as @poapxyz indicated, we should be able to close this issue and follow up wherever possible at a later date.
