### ISSUE TITLE
EthHub resource being sunset

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#8862]
### Describe the bug

According to [this tweet](https://twitter.com/econoar/status/1600932091398529024) the EthHub project is being sunset. Currently the [ethhub.io](https://ethhub.io/) domain appears to already be down.

We have several links on ethereum.org that point to this resource.

### To reproduce

1. Go to https://ethhub.io
2. Notice domain is down

### Expected behavior

The links on our page should be removes or updated to make sure we're not pointing to broken links

### Screenshots

<img width="510" alt="image" src="https://user-images.githubusercontent.com/54227730/206732723-22206271-35b4-4cde-96f4-9f3721ac1018.png">

**Comment by wackerow** [comment]
https://web.archive.org/web/20221206144249/https://docs.ethhub.io/

^ Link to the latest web archive of the page. 

@jmcook1186 We may also want to peak at this and see what content we may have been linking out to that we aren't anymore, and see if there are gaps in our own content that we should consider filling.

**Comment by 0xKai27** [comment]
Found one on the "What is Ether" page that is being rendered via the `eth.tsx` and translation files.

UI:
![image](https://user-images.githubusercontent.com/104422522/210928230-8e83d2b1-3d3f-4564-882e-b342f247f1b1.png)

eth.tsx:
<img width="790" alt="image" src="https://user-images.githubusercontent.com/104422522/210928318-8dc85275-5578-43f0-ac5e-6901d8b2acf1.png">

**Comment by corwintines** [comment]
Would a good interim be using the wayback link, and then looking for alternative sources to update after?

**Comment by 0xKai27** [comment]
Based on your list above, did a run-through with comments below. In general, given the load times required for archive retrieval, recommend to migrate uncovered topics found in EthHub to ethereum.org. For the majority of topics which intersect, ethereum.org usually has more comprehensive and updated information but a side-by-side review can be done if there is value in integrating EthHub content into existing ethereum.org pages.

- `https://ethereum.org/en//community/get-involved/#write-content`: **Propose to remove as it points users to update EthHub which is being sunset**
- `https://ethereum.org/en/community/research/#background-reading-2`: Most of the scaling concepts are already covered in ethereum.org in greater depth. If needed, a review can be done to migrate EthHub resources but value add will be limited. **Propose to change link to point to the ethereum.org scaling [docs](https://ethereum.org/en/developers/docs/scaling/) instead**

- `https://ethereum.org/en/contributing/style-guide/#style-guide`: EthHub is being used as an example in a code block. **Propose to change this example to another well-known resource such as an article from the Consensys [blog](https://consensys.net/blog/)**

![image](https://user-images.githubusercontent.com/104422522/211129357-5d98da13-0165-4a92-8cad-d193d66f70c7.png)

- `https://ethereum.org/en/defi/#main-content`: The EthHub DeFi resources are largely revolving around specific implementations rather than concepts. ethereum.org has greater details regarding the concepts. **Propose to add EthHub examples to the ethereum.org dapps [page](https://ethereum.org/en/dapps/?category=finance) if still relevant**

![image](https://user-images.githubusercontent.com/104422522/211130033-97386800-702a-46b8-adb2-e0c6cf70a972.png)

- `https://ethereum.org/en/deprecated-software/`: Note that this page is not indexed by ethereum.org search. **No changes required**

- `https://ethereum.org/en/developers/docs/consensus-mechanisms/pow/mining/#further-reading`: EthHub mining resources has additional technical info around block generation and uncle blocks. External links on EthHub are mostly dead. **To consider value add of migrating block generation and uncle blocks to ethereum.org**

- `https://ethereum.org/en/developers/docs/gas/#further-reading`: ethereum.org page on gas already addresses the concerns in greater detail. **Propose to remove link**

![image](https://user-images.githubusercontent.com/104422522/211130486-49526643-87aa-40aa-a128-8a1f9e7817c1.png)

- `https://ethereum.org/en/developers/docs/nodes-and-clients/#running-your-own-node`: ethereum.org staking [page](https://ethereum.org/en/staking/) is comprehensive enough to achieve the desired outcome. **Propose to remove link to avoid confusion**

- `https://ethereum.org/en/developers/docs/oracles/#further-reading`: ethereum.org doc on oracles is more comprehensive. **Propose to remove link**

- `https://ethereum.org/en/developers/docs/scaling/optimistic-rollups/`: To review resources and consider migration of EthHub resource. **Propose to remove link as ethereum.org is more comprehensive**

- `https://ethereum.org/en/developers/docs/scaling/plasma/`: To review resources and consider migration of EthHub resource. EthHub resources have a few helpful tables that goes into greater depth on Plasma. **Propose to integrate EthHub content**

- `https://ethereum.org/en/developers/docs/scaling/sidechains/`: ethereum.org resource covers all the points raised on EthHub. **Propose to remove link**

- `https://ethereum.org/en/developers/docs/scaling/state-channels/`: EthHub has additional details surrounding specific implementations. Concept-wise, ethereum.org is easier to follow and more comprehensive. **Propose to migrate examples to ethereum.org**

![image](https://user-images.githubusercontent.com/104422522/211130863-fa979336-8371-4d43-9aca-6f013913c233.png)

- `https://ethereum.org/en/developers/docs/scaling/zk-rollups`: ethereum.org ZK Rollup page is more comprehensive and detailed. **Propose to remove link**

- `https://ethereum.org/en/governance/#on-chain-vs-off-chain`: EthHub goes into greater detail on on-chain vs off-chain governance but lacks details surrounding EIPs & DAOs when compared to ethereum.org **Propose to migrate on/off-chain resource to ethereum.org governance page**

**Comment by 0xKai27** [comment]
I can work on the above if it makes sense. Will be a good refresher on the concepts while migrating the resources
