### ISSUE TITLE
Staking Page Quiz

### ISSUE THREAD

**Issue by Gandalf-Dust-Wizard** [ethereum/ethereum-org-website#9018]
Quiz relates to this page: https://ethereum.org/en/staking/

Questions:
Ethereum Quiz

**Q1:** What consensus algorithm does Ethereum use?
https://ethereum.org/en/staking/

A) Proof of Work
B) Proof of Stake
C) Delegated Proof of Stake
D) Practical Byzantine Fault Tolerance

Answer: B) Proof of Stake

Explanation: Ethereum currently uses a consensus algorithm called "Proof of Stake" (PoS). This approach is more energy efficient and scalable than Proof of Work (PoW), as it does not require miners to expend vast amounts of computational power to mine blocks.

A) Proof of Work is incorrect because, while Ethereum did originally use a PoW consensus algorithm, it has since transitioned to PoS.

C) Delegated Proof of Stake is incorrect because, while it is a variant of PoS, it is not the algorithm that Ethereum currently uses.

D) Practical Byzantine Fault Tolerance is incorrect because, while it is a consensus algorithm used by some cryptocurrencies, it is not used by Ethereum.

**Q2:** How does Proof of Stake (PoS) work?
https://ethereum.org/en/developers/docs/consensus-mechanisms/pos/

A) Miners must solve complex mathematical problems to validate transactions and create new blocks.
B) Miners must hold a certain amount of cryptocurrency to participate in the mining process.
C) Miners must be chosen through a voting process to validate transactions and create new blocks.
D) Miners must perform a certain amount of work, such as completing a task or providing a service to validate transactions and create new blocks.

Answer: B) Miners must hold a certain amount of cryptocurrency to participate in the mining process.

Explanation: In a Proof of Stake (PoS) system, the process of validating transactions and creating new blocks is determined by the amount of cryptocurrency a miner holds or their "stake" in the network.

A) This is incorrect because that is how a Proof of Work system works, not a Proof of Stake system.

C) This is incorrect because, while some PoS systems may have a voting component, it is not the primary factor in determining who is able to mine a block.

D) This is incorrect because this is not a factor in PoS systems.

**Q3:** How much can you earn from staking ETH?
https://ethereum.org/en/staking/

A) There is no way to earn from staking ETH.
B) The amount you can earn from staking ETH depends on how much ETH you hold and how long you stake it.
C) The amount you can earn from staking ETH is fixed and does not depend on how much ETH you hold or how long you stake it.
D) The amount you can earn from staking ETH is based on the market price of ETH at the time you begin staking.

Answer: B) The amount you can earn from staking ETH depends on how much ETH you hold and how long you stake it.

Explanation: Staking is the process of holding a certain amount of ETH in a wallet and participating in the validation of transactions to earn a reward in the form of additional ETH. The amount of ETH that can be earned through staking depends on several factors, including the amount of ETH that is staked and the length of time it is staked for.

A) This is incorrect because staking ETH allows users to earn a reward in the form of additional ETH.

C) This is incorrect because the reward earned from staking does depend on these factors.

D) This is incorrect because the reward earned from staking is not directly tied to the market price of ETH.

**Q4:** What is the minimum amount of ETH required for staking?
https://ethereum.org/en/staking/

A) There is no minimum amount of ETH required for staking.
B) The minimum amount of ETH required for staking is 1 ETH.
C) The minimum amount of ETH required for staking is 32 ETH.
D) The minimum amount of ETH required for staking varies depending on the specific staking service or platform being used.

Answer: D) The minimum amount of ETH required for staking varies depending on the specific staking service or platform being used.

Explanation: The minimum amount of ETH required for staking, also known as the "staking threshold," can vary depending on the specific staking service or platform being used. It is important to carefully review the requirements and terms of a specific staking service or platform before beginning the staking process.

A) This is incorrect because most staking services or platforms will have a minimum amount of ETH required in order to participate in the staking process.

B) This is incorrect because the minimum amount can vary depending on the specific staking service or platform being used.

C) This is incorrect because the minimum amount can vary depending on the specific staking service or platform being used.

**Q5:** What is the minimum amount of ETH you have to stake to become a validator?
https://ethereum.org/en/staking/

A) There is no minimum amount of ETH required to become a validator.
B) The minimum amount of ETH required to become a validator is 1 ETH.
C) The minimum amount of ETH required to become a validator is 32 ETH.
D) The minimum amount of ETH required to become a validator varies depending on the specific staking service or platform being used.

Answer: C) The minimum amount of ETH required to become a validator is 32 ETH. 

Explanation: The minimum amount of ETH required to become a validator, also known as the "validator threshold," is 32 ETH, allowing one to activate a validator/solo home staking or to utilize ‘staking as a service’ where the technical part of operating a node is delegated while one earns the native block rewards.

A) This is incorrect because most PoS systems will have a minimum amount of ETH required to participate in the validation process.

B) The minimum amount of ETH required to become a validator is only 1 ETH when you are not using solo home staking involving a dedicated computer connected to the internet ~24/7.

D) This option would have been correct if you were to use pooling staking solutions or a centralized cryptocurrency exchange. In such cases, the minimum amount of ETH required depends on the specific platform being used.

**Comment by konopkja** [comment]
Hello, thank you for the ideation!

1. is Q2 related to https://ethereum.org/en/developers/docs/consensus-mechanisms/pos/  or  https://ethereum.org/en/staking/ ? 
2. small tip on the length of the text: while explanations can be a bit longer, it would be better to have concise answers to questions. This is proven to drive better engagement with the quizzes as long answers might be somewhat tiring to read through.

Otherwise looking good! @wackerow  any comments on the content of these?

**Comment by Gandalf-Dust-Wizard** [comment]
Hey Jakub,

Thanks for our response! 

1. Question 2, although is focused on staking has its information taken from the PoS page. I can replace it with a different question if you’d like. I included it as I felt it critical understanding when it comes to staking. Maybe it is worth adding some info on ETH running PoS on the staking page?

2. Got it! I’ve shortened most of them. Let me know if you’d like me to shorten some of the explanations further?

**Comment by wackerow** [comment]
> Q1: What consensus algorithm does Ethereum use?
> C) Delegated Proof of Stake is incorrect because, while it is a variant of PoS, it is not the algorithm that Ethereum currently uses.

Would suggest maybe reworking this explanation to not sound so much like DPoS may be something we go to in the future. Though possible, not currently something in the pipeline, and the decision with fairly intentional. 
would suggest just "Ethereum does not natively support delegation of stake."

> Q2: How does Proof of Stake (PoS) work?
> Answer: B) Miners must hold a certain amount of cryptocurrency to participate in the mining process.

Note in this question that "miners" no longer exist on Ethereum, nor is there a "mining process." This is a specific term used in reference to proof-of-work hashing, which is no longer performed under PoS. I understand if we want to reference this in the wrong answers, but in the correct answer, this should state something like:
"Validators must lock up a certain amount of cryptocurrency to participate in consensus and produce blocks"
The explanation should also be updated to remove use of "mining" with PoS.

> Q3: How much can you earn from staking ETH?
> Answer: B) The amount you can earn from staking ETH depends on how much ETH you hold and how long you stake it.

The actual rate of return is also dependent upon the total amount of ETH staked. More ETH staked means lower APY each.

> Q4: What is the minimum amount of ETH required for staking?
> Answer: D) The minimum amount of ETH required for staking varies depending on the specific staking service or platform being used.

I'm not sure I love this answer, but I do understand where you're coming from. The Ethereum protocol itself is actually quite strict with this. To activate one set of validator keys, 32 ETH must be deposited. As touched on in another question, Ethereum does not natively support delegated proof-of-stake. All of the pooled staking services and liquid staking derivatives that exists were build separately to the core protocol, using various on-and-off-chain mechanisms. 

As I'm writing this, I'm realizing the next question (Q5) specifically contrasts this with ETH requirement for a validator node specifically. Maybe we just reword Q4 slightly to be "Q4: What is the minimum amount of ETH required to earn rewards from staking?" or "... to participate in staking?"

---

Nice job @Gandalf-Dust-Wizard! Thanks for posting this

**Comment by corwintines** [comment]
Hey @Gandalf-Dust-Wizard, thanks for opening this. Adding new learn quizzes is awesome to see. The idea behind them is to help reinforce content on the page they exist on, so with that lens in mind, I think we can refine these questions.

---

>Q1: What consensus algorithm does Ethereum use?
> https://ethereum.org/en/staking/
> 
> A) Proof of Work
> B) Proof of Stake
> C) Delegated Proof of Stake
> D) Practical Byzantine Fault Tolerance
> 
> Answer: B) Proof of Stake
> 
> Explanation: Ethereum currently uses a consensus algorithm called "Proof of Stake" (PoS). This approach is more energy efficient and scalable than Proof of Work (PoW), as it does not require miners to expend vast amounts of computational power to mine blocks.
> 
> A) Proof of Work is incorrect because, while Ethereum did originally use a PoW consensus algorithm, it has since transitioned to PoS.
> 
> C) Delegated Proof of Stake is incorrect because, while it is a variant of PoS, it is not the algorithm that Ethereum currently uses.
> 
> D) Practical Byzantine Fault Tolerance is incorrect because, while it is a consensus algorithm used by some cryptocurrencies, it is not used by Ethereum.

This wouldn't fit on the staking page since there isn't really content that touches on this. But, I could see this in https://ethereum.org/en/developers/docs/consensus-mechanisms/ if we expand to developer docs

> Q2: How does Proof of Stake (PoS) work?
> https://ethereum.org/en/developers/docs/consensus-mechanisms/pos/
> 
> A) Miners must solve complex mathematical problems to validate transactions and create new blocks.
> B) Miners must hold a certain amount of cryptocurrency to participate in the mining process.
> C) Miners must be chosen through a voting process to validate transactions and create new blocks.
> D) Miners must perform a certain amount of work, such as completing a task or providing a service to validate transactions and create new blocks.
> 
> Answer: B) Miners must hold a certain amount of cryptocurrency to participate in the mining process.
> 
> Explanation: In a Proof of Stake (PoS) system, the process of validating transactions and creating new blocks is determined by the amount of cryptocurrency a miner holds or their "stake" in the network.
> 
> A) This is incorrect because that is how a Proof of Work system works, not a Proof of Stake system.
> 
> C) This is incorrect because, while some PoS systems may have a voting component, it is not the primary factor in determining who is able to mine a block.
> 
> D) This is incorrect because this is not a factor in PoS systems.

Same as Q1, but this could be on https://ethereum.org/en/developers/docs/consensus-mechanisms/#proof-of-stake if we expand to developer docs. Also, as @wackerow mentioned, this isn't quite right, but we could fix the answers, this question is still a good one.

> Q3: How much can you earn from staking ETH?
> https://ethereum.org/en/staking/
> 
> A) There is no way to earn from staking ETH.
> B) The amount you can earn from staking ETH depends on how much ETH you hold and how long you stake it.
> C) The amount you can earn from staking ETH is fixed and does not depend on how much ETH you hold or how long you stake it.
> D) The amount you can earn from staking ETH is based on the market price of ETH at the time you begin staking.
> 
> Answer: B) The amount you can earn from staking ETH depends on how much ETH you hold and how long you stake it.
> 
> Explanation: Staking is the process of holding a certain amount of ETH in a wallet and participating in the validation of transactions to earn a reward in the form of additional ETH. The amount of ETH that can be earned through staking depends on several factors, including the amount of ETH that is staked and the length of time it is staked for.
> 
> A) This is incorrect because staking ETH allows users to earn a reward in the form of additional ETH.
> 
> C) This is incorrect because the reward earned from staking does depend on these factors.
> 
> D) This is incorrect because the reward earned from staking is not directly tied to the market price of ETH.

I think these answers are a bit misleading. It sounds like the validator reward is dependent on how much you stake. This isn't quite right. APY is the same whether you run 1 or 1000 validators. This should be discussed in terms of APY, and not more money === more ETH.

> Q4: What is the minimum amount of ETH required for staking?
> https://ethereum.org/en/staking/
> 
> A) There is no minimum amount of ETH required for staking.
> B) The minimum amount of ETH required for staking is 1 ETH.
> C) The minimum amount of ETH required for staking is 32 ETH.
> D) The minimum amount of ETH required for staking varies depending on the specific staking service or platform being used.
> 
> Answer: D) The minimum amount of ETH required for staking varies depending on the specific staking service or platform being used.
> 
> Explanation: The minimum amount of ETH required for staking, also known as the "staking threshold," can vary depending on the specific staking service or platform being used. It is important to carefully review the requirements and terms of a specific staking service or platform before beginning the staking process.
> 
> A) This is incorrect because most staking services or platforms will have a minimum amount of ETH required in order to participate in the staking process.
> 
> B) This is incorrect because the minimum amount can vary depending on the specific staking service or platform being used.
> 
> C) This is incorrect because the minimum amount can vary depending on the specific staking service or platform being used.

I understand what the question is going for, but this question needs rewording to be more specific about pooled staking or staking-as-a-service.

> Q5: What is the minimum amount of ETH you have to stake to become a validator?
> https://ethereum.org/en/staking/
> 
> A) There is no minimum amount of ETH required to become a validator.
> B) The minimum amount of ETH required to become a validator is 1 ETH.
> C) The minimum amount of ETH required to become a validator is 32 ETH.
> D) The minimum amount of ETH required to become a validator varies depending on the specific staking service or platform being used.
> 
> Answer: C) The minimum amount of ETH required to become a validator is 32 ETH.
> 
> Explanation: The minimum amount of ETH required to become a validator, also known as the "validator threshold," is 32 ETH, allowing one to activate a validator/solo home staking or to utilize ‘staking as a service’ where the technical part of operating a node is delegated while one earns the native block rewards.
> 
> A) This is incorrect because most PoS systems will have a minimum amount of ETH required to participate in the validation process.
> 
> B) The minimum amount of ETH required to become a validator is only 1 ETH when you are not using solo home staking involving a dedicated computer connected to the internet ~24/7.
> 
> D) This option would have been correct if you were to use pooling staking solutions or a centralized cryptocurrency exchange. In such cases, the minimum amount of ETH required depends on the specific platform being used.

Needs a bit of rewording to be good, but we can work on this. 

---

Overall, I like the idea @Gandalf-Dust-Wizard. Generally, a learn quiz should be 5-7 questions, so will need to create a few more questions from the content on the staking page. Let me know if you have any questions! :)

**Comment by corwintines** [comment]
Going to close this out as this seems abandoned.
