### ISSUE TITLE
Categorising Tutorial Tags: Framing Web3 Technologies - Suggestions Wanted

### ISSUE THREAD

**Issue by 0xKai27** [ethereum/ethereum-org-website#9063]
## Description

Related to the Q4 2022 roadmap (Epic #8491) and PR #8631 , propose the following changes to the tutorial tags for better clarity. 

The main goal is to abstract specific implementations and categorise according to concepts for better contextualisation of specific use cases. As categorical names are constantly evolving with the industry, it is envisioned that the list below is sufficiently generalised to function as a framework to approach the tutorials. If implemented, it is expected that there will be a guide page specifically on how these categories are determined.

This issue was created with the intention of standardising tags and by extension, categorical standards in the Web3 space. As such, the below acts as guide points for the community to arrive at a preferred conceptual framework.

### BLOCKCHAIN ANALYSIS
- **Description**: Applications and tools which help to make sense of blockchain transaction data. These are read only applications which help to increase transparency in the space.
- **Examples**: Etherscan, Coingecko, DefiLlama, Dune

### BRIDGES
- **Description**: Covers all cross-chain bridges that enable assets to be securely moved across various independent chains
- **Examples**: Multichain, RenBridge, Rubic

### CLIENT LIBRARIES
- **Description**: Libraries that enable rapid development of client side applications that interact with the Ethereum blockchain
- **Examples**: ethers.js, web3.js

### DAO
- **Description**: Any tutorials relating to collectively-owned, blockchain-governed organisations
- **Examples**: BitDAO, PleasrDAO, SyndicateDAO

### DEFI
- **Description**: Decentralised finance dapps that encompasses all non-custodial financial services on the Ethereum chain. While DeFi is extremely complex and varied, categorising all DeFi dapps under a single tag will aid in readability. Alternatively, tags can be expanded to specific financial functions if required: DEFI DEX, DEFI LENDING, DEFI DERIVATIVES, etc.
- **Examples**: Uniswap, Curve, Convex, Yearn, 1inch, DYDX, Nexus Mutual, 0x

### DESO
- **Description**: Decentralised social networks and related identity technologies where digital identities and social graphs are user owned.
- **Examples**: CyberConnect, Lens, Status, Skiff, Mirror, ENS, Spruce

### DEV TOOLS
- **Description**: Ethereum developer tools which optimises the development pipeline and developer workflow. This ranges from local development environment setup to backend IaaS providers.
- **Examples**: Hardhat, Truffle, Alchemy, Infura, Remix

### GAMING
- **Description**: Structured virtual environments with clearly defined goals and gamified play-to-earn economic incentives. This includes both GameFi as well as yield guilds.
- **Examples**: Axie Infinity, Splinterlands, Merit Circle, Yield Guild Games

### HARDWARE
- **Description**: Tutorials involving the installation of software on hardware devices. This can be for the purposes of contributing towards network resources or as user interfaces to the network.
- **Examples**: Node setup, Hardware wallets

### LAYER 2
- **Description**: Scaling solutions which focus on reducing or off-loading compute requirements while settling the final state on the base chain.
- **Examples**: Polygon, Optimism, Aztec, Raiden

### METAVERSE
- **Description**: Tutorials involving virtual worlds where users have the freedom to form personal networks and take ownership of digital assets. This covers avatar creation, virtual worlds, as well as extended reality.
- **Examples**: OSUVOX, Decentraland, Sandbox, Mattereum

### NFT
- **Description**: While NFT refers to a specific token interface, mainstream adoption of this terminology has extended to cover cultural assets. Consequently, this is a catch-all tag for culturally significant tokenised assets as well as the tokenisation of real world assets. Possible alternatives: COLLECTIBLES, CULTURAL
- **Examples**: BAYC, Meebits, POAP, Propy

### ORACLES
- **Description**: Data providers that enable DeFi protocols to ingest external data for logic processing within their smart contracts. This includes data feed and indexing applications.
- **Examples**: Chainlink, Band, UMA, Graph, API3, Push

### PRIVACY
- **Description**: Privacy focused tutorials focusing on third party privacy applications implemented through smart contracts.
- **Examples**: Tornado Cash, Railgun

### PROTOCOL
- **Description**: Tutorials which cover Ethereum protocol specific functionalities and implementations. Intention is for users to navigate to the official ethereum.org dev docs where required. This tag includes guides around Consensus, Logging, Public Key Cryptography, the EVM, gas fees, etc.
- **Examples**: Staking, Events, ECDSA, Hashes, PKC, Calculating Gas

### STORAGE
- **Description**: Decentralised storage solutions which enable data to be reliably and securely stored across a network of nodes.
- **Examples**: IPFS, Arweave, Sia, Storj

### TOKEN STANDARDS
- **Description**: Standard representation of asset ownership/rights that enable interoperability of tokens across decentralised applications.
- **Examples**: ERC20, ERC721, ERC1155

### WALLETS
- **Description**: User owned wallets which stores and manages the private keys of the user. This covers all kind of wallet user interfaces: browser, desktop, mobile, hardware security modules, paper
- Examples: Metamask, Argent, Trust, Ledger, Trezor, Exodus

## Other Considerations

- Removed references to specific coding languages. While this is definitely useful in narrowing the search, it is not directly related to the Ethereum protocol and might be better separated from Web3 specific concepts.
- To consider further whether specific development workflows should be used as tags: TESTING, DEPLOYMENT, etc.
- _Smart Contracts_ is less helpful as a tag due to all dapps meeting this requirement. I find it personally more helpful to have a **PROTOCOL** tag and those that does not meet this filter will most likely be related to smart contracts.
- To consider whether content type should be included: VIDEO, etc.

## Related Issues

#8491 
#8631

**Comment by corwintines** [comment]
This is a great idea! Will bring this up with the team to get a bit more input, but this is a direction I think makes sense to go with for tagging tutorials.

**Comment by wackerow** [comment]
Thanks for posting @0xKai27! Appreciate the well thought out proposal.

Overall I really like what you've laid out. I do think the current tags are far too messy, and we need a way to trim these down.

I would be really curious to see how our current tutorials would look if these tags were to be applied. As the tutorials stand, they live specifically as "developer tutorials". As such, I do wonder if being a little more granular with some of these could be beneficial, such as expanding out "Dev Tools", or "Client Libraries"

I also suspect a handful of these, such as Metaverse, Gaming, Hardware, would probably be fairly low usage.

Curious what others think, but I think with a few small adjustments this would likely be a nice upgrade for user experience.

**Comment by 0xKai27** [comment]
Definitely agree with your sentiment on the granularity of the "developer tutorials" related tags. I think the tricky part here is the level of assumed knowledge that a reader will have with regards to the Ethereum stack. 

In the optimistic scenario (i.e. they've read through the ethereum.org getting started, etc.), breaking down the toolings based on the below would definitely have more value add:
- Infrastructure-as-a-Service (eg. Alchemy, Infura)
- Ethereum Clients (eg. geth, besu, openethereum)
- Web3 Frameworks (eg. hardhat, truffle)
- Client Libraries (eg. web3.js, ethers.js)
- Backend Frameworks (eg. express, node)
- Dapp SDKs (Dapp specific client integration)
- Frontend Frameworks (eg. angular, vue, react)
- Wallets (eg. metamask, ledger, exodus)

Will likely also have to arrive a decision while taking into account how the "User Guides" (#8757) will relate to these tutorials. For example, if "Developer Tutorials" and "User Guides" flow is separate, we can maintain a more narrow set of tags specific to developer content. Additionally, this will also reduce the confusion for non-developer personas.

**Comment by corwintines** [comment]
I agree with this, removing project-specific tags for something more general is a great idea. I think a start we can have for this could be:
- Blockchain Analytics
- Bridges
- Clients
- DAO
- Defi
- Dev tools
- Layer 2
- NFT
- Client Libraries
- Oracle
- Protocol
- Smart contract
- Storage
- UI

If there are any others you think would be fitting @0xKai27, then I think we can test them out and see on review. I do think there are going to be some tags suggested here which won't have a place at the moment as @wackerow mentioned, but leaving what I think will be high impact for now.

What do you suggest for next steps? Would you like to work on going through the tutorials and updating these tags?

**Comment by 0xKai27** [comment]
Yeah, I can run through the tutorials and categorize them accordingly. Will collate them here first as a comment then we can discuss further whether the above tags are sufficient.

**Comment by 0xKai27** [comment]
First run of categorising the tutorials according to the tags suggested:

| Tutorial | Tags |
|---|---|
|[All you can cache](https://ethereum.org/en/developers/tutorials/all-you-can-cache/)| `Smart Contract`, `Storage`, `Layer 2`|
|[ERC-20 with Safety Rails](https://ethereum.org/en/developers/tutorials/erc20-with-safety-rails/)| `Smart Contract`, `DeFi`|
|[HOW TO TURN YOUR RASPBERRY PI 4 INTO A NODE JUST BY FLASHING THE MICROSD CARD](https://ethereum.org/en/developers/tutorials/run-node-raspberry-pi/)| `Protocol`, `Clients` |
[Learn Blockchain, Solidity, and Full Stack Web3 Development with JavaScript](https://www.youtube.com/watch?v=gyMwXuJrbJQ)| `DeFi`, `Dev Tools`, `DAO`, `NFT`, `Client Libraries`, `Smart Contract`, `UI`, `Oracle`, `Blockchain Analytics`|
|[UNDERSTANDING THE YELLOW PAPER'S EVM SPECIFICATIONS](https://ethereum.org/en/developers/tutorials/yellow-paper-evm/)| `Protocol` |
|[How to develop an NFT Smart Contract (ERC721) with Alchemy](https://www.youtube.com/watch?v=veBu03A6ptw)| `Dev Tools`, `NFT`, `Client Libraries`, `Smart Contract` |
|[SHORT ABIS FOR CALLDATA OPTIMIZATION](https://ethereum.org/en/developers/tutorials/short-abi/)| `Layer 2`, `Protocol` |
|[OPTIMISM STANDARD BRIDGE CONTRACT WALKTHROUGH](https://ethereum.org/en/developers/tutorials/optimism-std-bridge-annotated-code/)| `Layer 2`, `Bridges` |
|[Intro to Foundry](https://www.youtube.com/watch?v=fNMfMxGxeag)| `Smart Contract`, `Dev Tools` |
|[How to build an on-chain DAO](https://www.youtube.com/watch?v=AhJtmUqhAqg)| `Smart Contract`, `DAO` |
|[How to build an on-chain DAO](https://betterprogramming.pub/how-to-code-an-on-chain-dao-e525e13a57be)| `Smart Contract`, `DAO` |
|[How to Connect your Smart Contracts to Metamask](https://www.youtube.com/watch?v=pdsYCkUWrgQ)| `Smart Contract`, `Client Libraries`, `Dev Tools` |
|[FullStack Web3 — Everything You Need to Know](https://betterprogramming.pub/everything-you-need-to-know-about-fullstack-web3-94c0f1b18019)| `Client Libraries`, `UI`,  |
|[MERKLE PROOFS FOR OFFLINE DATA INTEGRITY](https://ethereum.org/en/developers/tutorials/merkle-proofs-for-offline-data-integrity/)| `Protocol`, `Storage` |
|[REVERSE ENGINEERING A CONTRACT](https://ethereum.org/en/developers/tutorials/reverse-engineering-a-contract/)| `Protocol`, `Smart Contract` |
|[Events and Logging in Solidity](https://blog.chain.link/events-and-logging-in-solidity/)| `Protocol`, `Smart Contract`, `Dev Tools` |
|[How to Become a Blockchain Engineer](https://www.youtube.com/watch?v=e1N4aWIJMN0)| More of a process guide |
|[]()|  |
|[]()|  |
|[]()|  |
|[]()|  |
|[]()|  |
|[]()|  |

Some comments:
- Still unsure about the value-add of the `Smart Contract` tag. Conscious that this is what most people will search by but the concept itself is quite general and therefore doesn't really help with the filtering process. This is especially given the nature of most tutorials which focus on application level use cases. 
- `Client` tag used protocol clients (e.g. geth, besu, lighthouse, teku, etc.)

**Comment by corwintines** [comment]
Hey @0xKai27,

Overall like your thinking here. MY main concern like you had mentioned is the smart contract tag. It is very overused as you mentioned, and doesn't serve much of a purpose if basically everything has it. I think we maybe just get rid of it for now and see how it goes? Let me know what you think. I left some changes to the table you provided with this, and adding a few tags that I felt were missing, or removed ones that seemed unnecessary. 

| Tutorial | Tags | 
|---|---|
|[All you can cache](https://ethereum.org/en/developers/tutorials/all-you-can-cache/)|`Storage`, `Layer 2`|
|[ERC-20 with Safety Rails](https://ethereum.org/en/developers/tutorials/erc20-with-safety-rails/)|`Token standard`|
|[HOW TO TURN YOUR RASPBERRY PI 4 INTO A NODE JUST BY FLASHING THE MICROSD CARD](https://ethereum.org/en/developers/tutorials/run-node-raspberry-pi/)| `Protocol`, `Clients` |
[Learn Blockchain, Solidity, and Full Stack Web3 Development with JavaScript](https://www.youtube.com/watch?v=gyMwXuJrbJQ)| `DeFi`, `Dev Tools`, `DAO`, `NFT`, `Client Libraries`, `Smart Contract`, `UI`, `Oracle`, `Blockchain Analytics`|
|[UNDERSTANDING THE YELLOW PAPER'S EVM SPECIFICATIONS](https://ethereum.org/en/developers/tutorials/yellow-paper-evm/)| `Protocol` |
|[How to develop an NFT Smart Contract (ERC721) with Alchemy](https://www.youtube.com/watch?v=veBu03A6ptw)| `Dev Tools`, `NFT`, `Client Libraries`, `Smart Contract` |
|[SHORT ABIS FOR CALLDATA OPTIMIZATION](https://ethereum.org/en/developers/tutorials/short-abi/)| `Layer 2`, `Protocol` |
|[OPTIMISM STANDARD BRIDGE CONTRACT WALKTHROUGH](https://ethereum.org/en/developers/tutorials/optimism-std-bridge-annotated-code/)| `Layer 2`, `Bridges` |
|[Intro to Foundry](https://www.youtube.com/watch?v=fNMfMxGxeag)|`Dev Tools` |
|[How to build an on-chain DAO](https://www.youtube.com/watch?v=AhJtmUqhAqg)|`DAO` |
|[How to build an on-chain DAO](https://betterprogramming.pub/how-to-code-an-on-chain-dao-e525e13a57be)| `DAO` |
|[How to Connect your Smart Contracts to Metamask](https://www.youtube.com/watch?v=pdsYCkUWrgQ)| `Client Libraries`, `Dev Tools`, `UI` |
|[FullStack Web3 — Everything You Need to Know](https://betterprogramming.pub/everything-you-need-to-know-about-fullstack-web3-94c0f1b18019)| `Client Libraries`, `UI`, `Dev Tools` |
|[MERKLE PROOFS FOR OFFLINE DATA INTEGRITY](https://ethereum.org/en/developers/tutorials/merkle-proofs-for-offline-data-integrity/)| `Protocol`, `Storage` |
|[REVERSE ENGINEERING A CONTRACT](https://ethereum.org/en/developers/tutorials/reverse-engineering-a-contract/)| `Protocol`, `Smart Contract` |
|[Events and Logging in Solidity](https://blog.chain.link/events-and-logging-in-solidity/)| `Dev Tools` |
|[How to Become a Blockchain Engineer](https://www.youtube.com/watch?v=e1N4aWIJMN0)| More of a process guide, agree with take here, this should be removed at this point I think |
|[HELLO WORLD SMART CONTRACT FOR BEGINNERS - FULLSTACK](https://ethereum.org/en/developers/tutorials/hello-world-smart-contract-fullstack/)| `Dev Tools`, `Client Libraries`, `UI`  |
|[What is Multicall](https://www.youtube.com/watch?v=EXas4uBqQr8)| `Client Libraries` |
|[NFT MINTER TUTORIAL](https://ethereum.org/en/developers/tutorials/nft-minter/)| `NFT`, `Storage`, `UI` |
|[Solidity, Blockchain, and Smart Contract Course](https://www.youtube.com/watch?v=M576WGiDBdQ)| `Protocol`, `DeFi`, `NFT`, `Client Libraries`, `Oracle`, `DAO`, `Blockchain Analytics`  |
|[How to make NFT Art with On-Chain Metadata](https://www.youtube.com/watch?v=9oERTH9Bkw0)| `NFT`, `Oracle`,  |
|[The Complete Guide to Full Stack Ethereum and EVM Development](https://dev.to/dabit3/the-complete-guide-to-full-stack-ethereum-development-3j13)| `Dev Tools`, `Client Libraries` |
|[Decentralized Staking App](https://github.com/scaffold-eth/scaffold-eth-challenges/tree/challenge-1-decentralized-staking)| More of a step-by-step challenge rather than a guide?  Agree here, should remove.|
|[Simple NFT Example](https://github.com/scaffold-eth/scaffold-eth/tree/simple-nft-example)| `NFT`, `UI` |
|[HOW TO SET UP TELLOR AS YOUR ORACLE](https://ethereum.org/en/developers/tutorials/how-to-use-tellor-as-your-oracle/)| `Oracle` |
|[Leveraged Trading in DeFi](https://www.youtube.com/watch?v=TmNGAvI-RUA)| `Dev Tools`, `DeFi` |
|[[Hardhat's tutorial for beginners](https://hardhat.org/tutorial#hardhat's-tutorial-for-beginners)](https://hardhat.org/tutorial)| `Dev Tools`|
|[Aave Flash Loan Tutorial](https://www.youtube.com/watch?v=Aw7yvGFtOvI)| `DeFi` |
|[Create your own Blockchain ERC20 Token](https://www.youtube.com/watch?v=8rpir_ZSK1g)| `Token standards` |
|[LEARN FOUNDATIONAL ETHEREUM TOPICS WITH SQL](https://ethereum.org/en/developers/tutorials/learn-foundational-ethereum-topics-with-sql/)| `Blockchain Analytics`, `Protocol` |
|[NFT/ERC-721/Collectible TUTORIAL](https://www.youtube.com/watch?v=p36tXHX1JD8)| `NFT`, `Dev Tools`, `Storage` |
|[UNISWAP-V2 CONTRACT WALK-THROUGH](https://ethereum.org/en/developers/tutorials/uniswap-v2-annotated-code/)| `Smart Contract`, `DeFi` |
|[Upgrading your Smart Contracts](https://www.youtube.com/watch?v=bdXJmWajZRY)| `Smart Contract`, `Protocol`, `Dev Tools` |
|[HOW TO MINT AN NFT (PART 2/3 OF NFT TUTORIAL SERIES)](https://ethereum.org/en/developers/tutorials/how-to-mint-an-nft/)|  `NFT`, `Client Libraries` |
|[HOW TO VIEW YOUR NFT IN YOUR WALLET (PART 3/3 OF NFT TUTORIAL SERIES)](https://ethereum.org/en/developers/tutorials/how-to-view-nft-in-metamask/)| `NFT`, `UI` |
|[HOW TO WRITE & DEPLOY AN NFT (PART 1/3 OF NFT TUTORIAL SERIES)](https://ethereum.org/en/developers/tutorials/how-to-write-and-deploy-an-nft/)|  `Dev Tools`, `NFT` |
|[SENDING TOKENS USING ETHERS.JS](https://ethereum.org/en/developers/tutorials/send-token-etherjs/)| `Client Libraries` |
|[VYPER ERC-721 CONTRACT WALKTHROUGH](https://ethereum.org/en/developers/tutorials/erc-721-vyper-annotated-code/)| `NFT` |
|[HELLO WORLD SMART CONTRACT FOR BEGINNERS](https://ethereum.org/en/developers/tutorials/hello-world-smart-contract/)|  `Dev Tools`, `Client Libraries` |
|[ERC-20 CONTRACT WALK-THROUGH](https://ethereum.org/en/developers/tutorials/erc20-annotated-code/)| `Token standards` |
|[TESTING SIMPLE SMART CONTRACT WITH WAFFLE LIBRARY](https://ethereum.org/en/developers/tutorials/waffle-test-simple-smart-contract/)| `Dev Tools` |
|[MONITORING GETH WITH INFLUXDB AND GRAFANA](https://ethereum.org/en/developers/tutorials/monitoring-geth-with-influxdb-and-grafana/)| `Client` |
|[How to Fetch the Current Price of Ethereum in Solidity](https://blog.chain.link/fetch-current-crypto-price-data-solidity/)| `Oracle` |
|[CREATE AND DEPLOY A DEFI APP](https://ethereum.org/en/developers/tutorials/create-and-deploy-a-defi-app/)| `Dev Tools` |
|[USING WEBSOCKETS](https://ethereum.org/en/developers/tutorials/using-websockets/)| `Client Libraries` |
|[WAFFLE: DYNAMIC MOCKING AND TESTING CONTRACT CALLS](https://ethereum.org/en/developers/tutorials/waffle-dynamic-mocking-and-testing-calls/)| `Dev Tools`, `Testing` |
|[SENDING TRANSACTIONS USING WEB3](https://ethereum.org/en/developers/tutorials/sending-transactions-using-web3-and-alchemy/)| `Client Libraries` |
|[GETTING STARTED WITH ETHEREUM DEVELOPMENT](https://ethereum.org/en/developers/tutorials/getting-started-with-ethereum-development-using-alchemy/)| `Client Libraries`, `Dev Tools` |
|[WAFFLE SAY HELLO WORLD TUTORIAL WITH HARDHAT AND ETHERS](https://ethereum.org/en/developers/tutorials/waffle-say-hello-world-with-hardhat-and-ethers/)| `Dev Tools`, `Client Libraries`, `Testing` |
|[TESTING ERC-20 TOKENS WITH WAFFLE](https://ethereum.org/en/developers/tutorials/testing-erc-20-tokens-with-waffle/)| `Testing`, `Dev Tools` |
|[A PYTHON DEVELOPER'S INTRODUCTION TO ETHEREUM, PART 1](https://ethereum.org/en/developers/tutorials/a-developers-guide-to-ethereum-part-one/)| `Client Libraries`, `Protocol` |
|[A GUIDE TO SMART CONTRACT SECURITY TOOLS](https://ethereum.org/en/developers/tutorials/guide-to-smart-contract-security-tools/)| `Dev Tools`, `Security` |
|[SMART CONTRACT SECURITY CHECKLIST](https://ethereum.org/en/developers/tutorials/secure-development-workflow/)| `Security` |
|[SMART CONTRACT SECURITY GUIDELINES](https://ethereum.org/en/developers/tutorials/smart-contract-security-guidelines/)| `Security` |
|[THE GRAPH: FIXING WEB3 DATA QUERYING](https://ethereum.org/en/developers/tutorials/the-graph-fixing-web3-data-querying/)| `Blockchain Analytics`, `Client Libraries` |
|[TOKEN INTEGRATION CHECKLIST](https://ethereum.org/en/developers/tutorials/token-integration-checklist/)| `Security` |
|[DOWNSIZING CONTRACTS TO FIGHT THE CONTRACT SIZE LIMIT](https://ethereum.org/en/developers/tutorials/downsizing-contracts-to-fight-the-contract-size-limit/)| `Storage` |
|[HOW TO USE SLITHER TO FIND SMART CONTRACT BUGS](https://ethereum.org/en/developers/tutorials/how-to-use-slither-to-find-smart-contract-bugs/)| `Dev Tools`, `Security` |
|[SOLIDITY AND TRUFFLE CONTINUOUS INTEGRATION SETUP](https://ethereum.org/en/developers/tutorials/solidity-and-truffle-continuous-integration-setup/)| `Dev Tools` |
|[HOW TO MOCK SOLIDITY SMART CONTRACTS FOR TESTING](https://ethereum.org/en/developers/tutorials/how-to-mock-solidity-contracts-for-testing/)| `Dev Tools`, `Testing` |
|[KICKSTART YOUR DAPP FRONTEND DEVELOPMENT WITH CREATE-ETH-APP](https://ethereum.org/en/developers/tutorials/kickstart-your-dapp-frontend-development-wth-create-eth-app/)| `Client Libraries`, `UI` |
|[CALLING A SMART CONTRACT FROM JAVASCRIPT](https://ethereum.org/en/developers/tutorials/calling-a-smart-contract-from-javascript/)| `Client Libraries` |
|[SET UP WEB3.JS TO USE THE ETHEREUM BLOCKCHAIN IN JAVASCRIPT](https://ethereum.org/en/developers/tutorials/set-up-web3js-to-use-ethereum-in-javascript/)| `Client Libraries` |
|[HOW TO USE ECHIDNA TO TEST SMART CONTRACTS](https://ethereum.org/en/developers/tutorials/how-to-use-echidna-to-test-smart-contracts/)| `Dev Tools`, `Testing` |
|[TRANSFERS AND APPROVAL OF ERC-20 TOKENS FROM A SOLIDITY SMART CONTRACT](https://ethereum.org/en/developers/tutorials/transfers-and-approval-of-erc-20-tokens-from-a-solidity-smart-contract/)| `Token standards` |
|[INTERACT WITH OTHER CONTRACTS FROM SOLIDITY](https://ethereum.org/en/developers/tutorials/interact-with-other-contracts-from-solidity/)| `Dev Tools` |
|[UNDERSTAND THE ERC-20 TOKEN SMART CONTRACT](https://ethereum.org/en/developers/tutorials/understand-the-erc-20-token-smart-contract/)| `Token standard` |
|[DEPLOYING YOUR FIRST SMART CONTRACT](https://ethereum.org/en/developers/tutorials/deploying-your-first-smart-contract/)|  `Dev Tools` |
|[LOGGING DATA FROM SMART CONTRACTS WITH EVENTS](https://ethereum.org/en/developers/tutorials/logging-events-smart-contracts/)| `Protocol` Not really sure we need this tutorial |
|[HOW TO IMPLEMENT AN ERC-721 MARKET](https://ethereum.org/en/developers/tutorials/how-to-implement-an-erc721-market/)| `NFT` |
|[HOW TO USE MANTICORE TO FIND BUGS IN SMART CONTRACTS](https://ethereum.org/en/developers/tutorials/how-to-use-manticore-to-find-smart-contract-bugs/)| `Dev Tools` , `Security` Remove because this is in maintenance mode|

**Comment by corwintines** [comment]
Just some initial thoughts above, let me know what you think @0xKai27

**Comment by corwintines** [comment]
I believe we have finished this last year. Going to close this out for now.
