### ISSUE TITLE
Two ethereum.org staking sites with different metrics causing user confusion

### ISSUE THREAD

**Issue by mortimerprime** [ethereum/ethereum-org-website#9232]
Hello there,
I noticed that there are 2 different "official" staking sites on "ethereum.org":

https://ethereum.org/en/staking/
https://launchpad.ethereum.org/en/

The 3 topline metrics shown are materially different across sites (i.e. total eth staked; total validators; current apr).

While I'm sure there is a reason (i.e. one site is not including execution layer rewards), it is massively confusing and doesn't seem to be addressed in the comments. I have personally been referring to the launchpad version of the site, and 3.8% APR (vs 5.1%) has led me to draw certain conclusions which I would not have drawn, had I used the other site. 

Please consider unifying under one page, or giving reasons for the differences.

Thank you,
Alex
![Capture](https://user-images.githubusercontent.com/57038268/213307355-59535e30-61c6-4608-a227-bbc62f80a553.PNG)

**Comment by wackerow** [comment]
Thanks @mortimerprime! I agree with your sentiment, and tl;dr I think we should use the total validator count from Launchpad, and use the total ETH staked and APR from the endpoint being used on e.org/staking. 

The ethereum.org/staking stats are pulled from a slightly different endpoint from Beaconcha.in and calculated in slightly different ways when compared to the Launchpad.

| | Launchpad | Ethereum.org |
| --- | --- | --- |
| Endpoint | https://mainnet.beaconcha.in/api/v1/epoch/latest | https://beaconcha.in/api/v1/ethstore/latest |
| Total stake | `totalvalidatorbalance` $*10^{-9}$ | `effective_balances_sum_wei` $*10^{-18}$ |
| Validator count | `validatorscount` | Total_stake / 32 |
| APR | [`calculateStakingRewards`](https://github.com/ethereum/staking-launchpad/blob/b8af56634189cbd4a2b88571c1acf6860df297f5/src/utils/calculateStakingRewards.ts#L14) | `apr` |

"Total ETH staked"
**Launchpad**: represents the sum total of _account_ balances, which _does_ includes rewards above 32 ETH
**Ethereum.org**: represents the sum total of _effective_ balances, which _does not_ include rewards above 32 ETH

"Total validators"
Launchpad: This is pulled directly from the latest epoch API endpoint, and just spot testing this now, it 
Ethereum.org: Underestimates this value, as the true average effective balance is just below 32 ETH (And it should be rounded to an integer.. that's a bug)

"Current APR"
Launchpad: This is calculated using a function written within the Staking Launchpad website repo [(source code here)](https://github.com/ethereum/staking-launchpad/blob/b8af56634189cbd4a2b88571c1acf6860df297f5/src/utils/calculateStakingRewards.ts#L14). It has many assumptions about network state, and is at best an estimate. It has also not been updated since The Merge, and does not take into account fee tips and MEV that are earned by validators.
Ethereum.org: Taken from Beaconcha.in's "ethstore" endpoint which performs it's own calculation on the backend, and serves this. This is a more accurate estimate as it takes into consideration fee tips/MEV rewards that validators have been receiving. I'm not sure the details of exactly how this is calculated though beyond that.

---

Again, I think we should update e.org to use the "latest epoch" endpoint matching the Launchpad, and I think we should open this as an issue on the Staking Launchpad repo to update the endpoint for "Total ETH staked" and "Current APR" to match that of ethereum.org.

**Comment by mortimerprime** [comment]
Thanks for the quick response @wackerow.
Two quick comments:
1) It would be nice / intuitive if whichever amounts are displayed for "Total ETH stake" & "validator count" have the property that multiplying "validator count" by 32 = "Total ETH stake". As you seem to allude to, ethereum.org currently has this property. If this property doesn't hold in the upcoming version, maybe place a comment nearby explaining how this calc is done / the logic behind it? Just to avoid any confusion.
2) Do I need to open this (separate) issue you allude to in your concluding sentence?
Thanks!

**Comment by corwintines** [comment]
Thanks for opening this @mortimerprime 

@wackerow I think your suggestion here is good.

@mortimerprime if you want to open that issue you can. Ill add this to github grooming as well.

**Comment by mortimerprime** [comment]
@corwintines @wackerow thank you both!
I went ahead and filed this on the Staking Launchpad repo, as per your suggestion:
https://github.com/ethereum/staking-launchpad/issues/597
Thanks for all you do!
