### ISSUE TITLE
[Design system V2] Complete forms UI components

### ISSUE THREAD

**Issue by nloureiro** [ethereum/ethereum-org-website#9435]
## Intro
This issue is a part of the [Design System V2 Epic](https://github.com/ethereum/ethereum-org-website/issues/9431) and can be assigned to anyone who wants to collaborate. 
You can use the comments to sign that you want to work on this, and this issue can be assigned to you.
If you have any questions about it, please don't hesitate to reach out on the comments or on our discord

<br>
<br>

## Description
On the V1 part, we introduced some small pieces of what is known to be a complete set to be able to build a form. 

We have covered Buttons, Drop-downs, Switches, and inputs to start, and at the very end, we added checkboxes and radio buttons. 

Even knowing that [[ethereum.org](http://ethereum.org/)](http://ethereum.org/) doesn’t use much more UI elements, we feel that a future-proof Design system should cover more. 

The list should include text areas, file upload, error, and success messages, as well as additional UI elements such as date pickers and sliders. It should also cover more sizes to be more aligned with the chakra UI.

- Type: new design
- Difficulty: 3 out of 10

[Link to the Figma file](https://www.figma.com/file/XCz2dijiDihs9ldADumWbK/V2%2FComplete-forms-components?node-id=0%3A1&t=dBV4S8KBQAMpNUtL-1) to be worked on 

<br>
<br>

## workflow
These are the main steps for each task.

1. #### Use a separate [Figma file](https://www.figma.com/file/XCz2dijiDihs9ldADumWbK/V2%2FComplete-forms-components?node-id=0%3A1&t=dBV4S8KBQAMpNUtL-1).
    - made by the team and liked here should be
2. #### Identify on which pages the component is used.
    - This can be made collaboratively and consists of screenshots/links to the pages where these components are already in use. Note that we can propose the unification of similar components in one if we find that the UX/UI justifies that’s the core unification goal of the Design system V2.
3. #### Identify the chakra component to be used as a base (if any)
    - We use chakra UI as a base framework, and if we can match the new design with an existing UI component in chakra, it’s a good call. If not, we can build one, but this should be something to identify now that will ease the implementation.
4. #### Work on the design.
    - This is where we build the new proposal that will be a new component in the design system, never forgetting the different screen sizes, behavior states, and themes.
5. #### Test and validate the new component on Figma.
    - Before closing the design, we need to test some real use cases. I suggested having some production screenshot as the base and building it on a Figma page with real content to test the live application of the new design.
6. #### Validation and feedback.
    - At this point, we are ready to validate and collect feedback. We should act upon this and have the best proposal possible.
7. #### Spec to handover to code.
    - This will be the final step, where we review the file from the perspective of a handover to the design system master file and to the code or storybook for code development.
8. #### Merge with the master Figma file of the Design system.
    - This step will be made by someone from the core team because there are some things that could be improved in how we can onboard external contributors to the Figma team. It’s a Figma thing that we can’t change for now.
9. #### Close the issue and publish the Design system update on the Figma community**.
    - For the last action, we need to close the issue and update the Design system on the Figam community file. At this point, another issue might need to be created to update the storybook and the code to reflect this new design.

<br>
<br>

**Comment by Dotcom0x** [comment]
Hello! can iwork on this?

**Comment by nloureiro** [comment]
> Hello! can i work on this?

Hey. Thank you for reaching out. I will assign this to you.

The next steps will be on Figma > when ever you can jump into this Figma file and make a comment to et to know your Figma user

https://www.figma.com/file/XCz2dijiDihs9ldADumWbK/V2%2FComplete-forms-components?type=design&node-id=1%3A48&mode=design&t=YiQIgeKSJGHxB20e-1

And then I can assist you there.

Thank you

**Comment by Dotcom0x** [comment]
Great thank you :)

**Comment by nloureiro** [comment]
> Great thank you :)

hey, Happy new year! Any update here?

**Comment by ddannehh** [comment]
Hey guys, decided to pick this one up :)

## Components created
- Text area (Regular & Small)
- Upload / Drop Zone (Regular & Small)
- File list
- Datepicker (Single & Double)
- Slider (Regular & Small)

###Screenshots

<img width="696" alt="Text Area" src="https://github.com/ethereum/ethereum-org-website/assets/109203827/345746cb-29d6-4d38-9935-d5e443403a0d">
<img width="920" alt="Upload Dropzone" src="https://github.com/ethereum/ethereum-org-website/assets/109203827/0a1b9a6d-1fb7-4877-9edc-f605996d9f53">
<img width="856" alt="File Item" src="https://github.com/ethereum/ethereum-org-website/assets/109203827/238647aa-1fbc-46e6-be82-e5394acdd1de">
<img width="1452" alt="Date Picker" src="https://github.com/ethereum/ethereum-org-website/assets/109203827/3f4748be-fdfb-445b-a1fa-758702143511">
<img width="560" alt="Slider" src="https://github.com/ethereum/ethereum-org-website/assets/109203827/805a7345-ab58-4d38-9420-598ce9f7ec5c">

Components laid out on the Design page of the figma file here: https://www.figma.com/file/XCz2dijiDihs9ldADumWbK/V2%2FComplete-forms-components?type=design&node-id=1%3A135&mode=design&t=cOE20HNlxo7B3ShW-1

## In Use
Some mockups and layouts of the components in use. Note that these are freewheeled and the content doesn’t exist on the current website.

<img width="1490" alt="Event Page Validation (LM)" src="https://github.com/ethereum/ethereum-org-website/assets/109203827/854175ab-1b39-45db-8c5d-82bfec510afd">

<img width="1490" alt="Event Page Validation (DM)" src="https://github.com/ethereum/ethereum-org-website/assets/109203827/db92c7c8-0869-4f6a-8e86-c52db690311c">

<img width="1490" alt="Event Submitted (LM)" src="https://github.com/ethereum/ethereum-org-website/assets/109203827/10bca040-002d-41b4-9c92-d9cba373fbd6">

<img width="1490" alt="Event Submitted (DM)" src="https://github.com/ethereum/ethereum-org-website/assets/109203827/88c2b4e2-9374-4c85-bd0e-24149a429493">

<img width="1340" alt="Submit Issue Default (LM)" src="https://github.com/ethereum/ethereum-org-website/assets/109203827/792e69f5-871f-43cc-ba27-cb2b29052249">

<img width="1340" alt="Submit Issue Default (DM)" src="https://github.com/ethereum/ethereum-org-website/assets/109203827/157ddb9b-0139-44da-96c4-1366165dc67c">

<img width="1100" alt="Submit Issue Small (LM)" src="https://github.com/ethereum/ethereum-org-website/assets/109203827/8e8151cd-022e-40cf-99eb-b00711690928">

<img width="1100" alt="Submit Issue Small (DM)" src="https://github.com/ethereum/ethereum-org-website/assets/109203827/393bc4b8-1c45-4767-a866-4c3e0d771ffe">

These designs can be found on the Final Proposal page in the figma file here: https://www.figma.com/file/XCz2dijiDihs9ldADumWbK/V2%2FComplete-forms-components?type=design&node-id=1%3A143&mode=design&t=cOE20HNlxo7B3ShW-1

## Additional notes
A list of things I noticed or came to mind while working on this.
- Designs made without access to already made assets from general ethereum.org Design System and it’s components/variables, so component links and values will be broken and need to be relinked. I guess Figma requires a user to be a team member of the DS account to be able to use linked assets.
- Consider extending the color palette to support better readability for semantic colors. (E.g. $error on $background.base in darkmode )
- Skipped mobile since this set of form components won’t be impacted much by viewport width. Only exception would maybe be the single-day datepicker visualisation where perhaps we can show OS native pickers for better UX, but support seems [wonky](https://caniuse.com/input-datetime).
- Not sure what the latest styling is for floating element shadows (see datepicker). Looks like there have been some changes and are a bit inconsistent across the DS, to review.
- Datepicker is on Chakra roadmap, so for now will have to be another implementation? See [Research](https://www.figma.com/file/XCz2dijiDihs9ldADumWbK/V2%2FComplete-forms-components?type=design&node-id=1-123&mode=design) page.
- No real guidelines on icons available, just used a mix from Chakra- & Feather- icons.
- Consider right-side icon/button visibility toggle on standard input field component (e.g. show/hide password/datepicker/clock/...)
- Missing default -non active- filled state on standard input field component.
- DS Button height changes depending on value (label vs icon only), should be consistent no matter the contents.

If there's anything I missed or misinterpreted, let me know. Feedback welcome ✌️✌️

**Comment by nloureiro** [comment]
@ddannehh this looks great!!!! great work! Thank you!

**Comment by konopkja** [comment]
whoah thank you for the contribution!  @ddannehh

**Comment by ddannehh** [comment]
My pleasure guys. Fun stuff. Let me know if there are any changes required.

**Comment by nloureiro** [comment]
> My pleasure guys. Fun stuff. Let me know if there are any changes required.

for sure, I haven had time to review it yet, will do it as soon as I can. Thank you again!

**Comment by ddannehh** [comment]
I've imported the components into the [main file](https://www.figma.com/file/NrNxGjBL0Yl1PrNrOT8G2B/ethereum.org-Design-System?type=design&node-id=258%3A636&mode=design&t=JbV4BmRzw8XI2iPN-1) and refactored them so all the system styles/vars are linked.

Did place some additional remarks in the file both with feedback and/or questions.
I suppose @nloureiro will further incorporate them in the current DS artboard layout setup when reviewing and approving?
If something isn't as expected let me know 😘

**Comment by nloureiro** [comment]
@ddannehh, thank you so much for your collaboration!
I will review on Figma the changes but I think I can close this issue.
