### ISSUE TITLE
Design regression for staking product icons

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#9765]
## Issue
Product/brand icons on the staking sub-pages are designed to be white, on a colored background, _both_ in light and dark mode.

At some point this has changed to have the icons change to black when in light mode, which hurts the contrast ratio and does not match the neighboring text

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/54227730/226604949-cc2a3b9c-d5e1-4c24-9c85-c9b54472fa78.png">

## To replicate
1. Go to https://ethereum.org/en/staking/solo/#node-and-client-tools
2. See icon color compared to text color
3. Try toggling light/dark mode to see difference

(Also applies to `/saas` and `/pools` staking subpages)

## Suggested options to fix
- Force icons to white on both light/dark mode. This allows us to keep the existing brand-color theming behind the product name
- Update these product cards in conjunction with design system to form more universal approach to theming these. This could limit our ability to provide brand coloring

**Comment by vishal590** [comment]
@wackerow assign this issue to me 🙏🙏

**Comment by corwintines** [comment]
@wackerow I think since @nloureiro is still working on cards for the design system, we could just start with doing the white icons for now. Then once we have the new design system cards, probably would make sense then to migrate over to that second option. 

@nloureiro does this seem reasonable to you?

@vishal590 just want to wait for confirmation from @nloureiro, then we can get a path forward here. Will assign to you once we scope this.

**Comment by wackerow** [comment]
Hey folks, apologies on missing those comments. Ended up tossing up #10294 to patch this with just the white text until there is anything further on the design system. Closing out
