### ISSUE TITLE
Energy consumption chart label overflow bug

### ISSUE THREAD

**Issue by corwintines** [ethereum/ethereum-org-website#9857]
### Describe the bug

In some languages, for example German, the labels for the energy consumption chart overflow past their columns making it hard to read.

### To reproduce

1. Go to [energy consumption page in German for example](https://ethereum.org/de/energy-consumption)
2. Scroll down to the energy consumption chart
3. Notice the overflow on the labels

### Expected behavior

Labels shouldn't overflow into each other making it hard to read

### Screenshots

<img width="519" alt="229147298-3ed982ee-9e5f-4fad-806f-7db4aeffd77e" src="https://user-images.githubusercontent.com/15589226/229192307-254284e5-760d-425d-894e-1442850b3f8c.png">

### Would you like to work on this issue?

- [ ] Yes
- [ ] No

**Comment by corwintines** [comment]
@konopkja @nloureiro would be great to have you input here

cc: @nhsz

**Comment by pettinarip** [comment]
For more context: currently, we have this distribution across the different breakpoints:

- base (**4 columns**): youtube, btc-pow, eth-pow, eth-pos
- sm (**6 columns**): youtube, btc-pow, netflix, eth-pow, paypal, eth-pos
- md (**10 columns**): youtube, gold-mining-galaxy, global-data-centers, gold-mining-cbeci, btc-pow, netflix, eth-pow, gaming-us, paypal, eth-pos

Maybe a potential solution could be to decrease the amount of columns we have on the `md` breakpoint to 8 columns instead of 10.

====
Note: this would be a good case to use the new Container Queries for CSS because we depend on the size of the chart's container rather than the screen resolution. But I wouldn't use it yet for the lack of [browser support](https://caniuse.com/css-container-queries). cc @wackerow

**Comment by vishal590** [comment]
@corwintines can I work on this issue ?

**Comment by corwintines** [comment]
@vishal590 are you still interested in this?

**Comment by vishal590** [comment]
Yes, I am interested
