### ISSUE TITLE
Layout bug on staking withdrawals page

### ISSUE THREAD

**Issue by wackerow** [ethereum/ethereum-org-website#9996]
### Describe the bug

At specific screen widths, we lose the top margin on the "When's it shipping" box being displayed on the Withdrawals page, which is the only "staking" template page that uses this. Also seeing the "Staking options" not displaying full width just below the tablet breakpoint.

### To reproduce

1. Go to https://ethereum.org/en/staking/withdrawals on desktop
2. Adjust window width between 990 and 1024px
3. See layout of "When's it shipping" box and "Staking options" dropdown menu width

### Expected behavior

Would expect a single breakpoint to switch from desktop to tablet view, without multiple layout shifts. Would expect "Staking options" dropdown to always be full width on tablet or smaller (when located at the bottom of the display). Also should not lose the top margin on the "When's it shipping" box.

### Screenshots

1024px wide:
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/54227730/232920037-047305d2-a596-452e-b47d-784a73c374fc.png">

1023px wide:
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/54227730/232920086-ae6d37ee-d9d2-4a94-9797-a0ec66d88dfd.png">

991px wide:
<img width="992" alt="image" src="https://user-images.githubusercontent.com/54227730/232920160-6555750d-7aec-40d5-b64f-ee7784e83de5.png">

### Desktop (please complete the following information)

macOS Ventura 13.2.1
Brave latest (112.0.5615.121)

### Would you like to work on this issue?

- [ ] Yes
- [X] No

**Comment by MrJithil** [comment]
https://github.com/ethereum/ethereum-org-website/blob/a2da905d1fd65ec8a898d87ff5a59517b6d1fb04/src/components/ButtonDropdown.tsx#L143

**Comment by MahendraBishnoi29** [comment]
@MrJithil why are mentioning this line? 🤔

**Comment by amit-ksh** [comment]
Hey @wackerow, I would like to work on this issue, please assign it to me.

**Comment by amit-ksh** [comment]
Hey @wackerow, I've fixed the "Staking options" dropdown button width and the other two issues have been mentioned *multiple layout shifts* and losing the `margin-top` of "When's it shipping" are happening because the `staking.tsx` template still using the **emotion**, and breakpoints used in it little smaller than the Chakra ones. This will probably get fixed once the `staking.tsx` template migrated to Chakra, there is already a [PR raised for this](#10019)

So, I'm raising a PR only fixing the width of the Dropdown button, let me know your thought on this.

**Comment by amit-ksh** [comment]
Hey @wackerow! This issue has been fixed by this PR [#10019].

**Comment by wackerow** [comment]
Awesome, thanks @amit-ksh! And thank you @soheil555 for the patch! LGTM =)
